Feat/1039 update seedlot related tests to use stored variable
bcgov/nr-spar pull request #1084
Opened 2024-04-30 23:45 UTC by ngunner15

# Description
Closes #1039 

### Changelog
#### New
-

#### Changed
- Made the following tests more dynamic by removing hardcoded values
- seedlot-dashboard
- edit-applicant-seedlot-info

#### Removed
-

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExeDZyd2FvNm51YnhjMDIzdWlncW91Ymo1czlsMDg3NmVpeGM3ZHQ0NCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/YbXLZ6dymH758xSEbM/giphy.gif" width="200"/>

2024-05-01 16:55 UTC, RMCampos approved these changes
LGTM! Great job 💯

2024-05-01 17:24 UTC, craigyu requested changes

2024-05-01 17:24 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/seedlot-dashboard.cy.ts
![image](https://github.com/bcgov/nr-spar/assets/25162561/2d673037-4434-4d3d-b654-87756285e7d3)

This test isn't following the specification. Use seedlot number in the element id to get the species and status text. Do not make assumption that the seedlot in a specific row will be under a species. If there are existing seedlots or the test ran multiple times, how can we know for sure that the first row is what we just registered?

2024-05-02 17:32 UTC, craigyu approved these changes
Amazing loop

2024-05-02 17:32 UTC, merged

2024-05-02 17:34 UTC, ngunner15 commented
> Amazing loop

Finally able to loop some tests :)