Fix:1038 update the agency selection input
bcgov/nr-spar pull request #1096
Opened 2024-05-08 14:56 UTC by mgaseta

# Description
Closes #1038

### Changelog
#### New
- Added new validation to the agency selection field
- Added new error banner
- Added new error messages
- Added new loading display inside the input

#### Changed
- Changed the agency selection method from a dropdown to an input
- Changed helper texts

#### Removed
- Nothing :)

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?
<img width="250" src="https://media3.giphy.com/media/pHWFj7mt7qyBs2XYC6/giphy.gif"/>

2024-05-15 17:37 UTC, ngunner15 approved these changes
LGTM! 👍🏼

2024-05-15 17:53 UTC, RMCampos approved these changes
Great job! No changes other then the ones Craig is requesting 🎉 

<img width="200" src="https://media0.giphy.com/media/3o7Z4tNIWOQWTlfGN2/giphy.gif"/>

2024-05-15 18:02 UTC, craigyu requested changes
Good work! ✅
As discussed earlier, a few things needs to be updated:
- leading 0 on single digit location code
- cy.wait() usage
- Green and red circle appearing at the same time

2024-05-15 18:49 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/create-a-class-seedlot.cy.ts
> +    cy.wait(FIVE_SECONDS);
Fixed here: https://github.com/bcgov/nr-spar/pull/1096/commits/258028721957ae15a14cb5b6e9a1278bb48242b5

2024-05-16 16:51 UTC, craigyu approved these changes
Good job! Surprisingly there is no conflict with Nisarg changes ✌️

2024-05-16 17:25 UTC, merged