Feat/my seedlot cypress test 3
bcgov/nr-spar pull request #1131
Opened 2024-05-15 16:48 UTC by ngunner15

# Description
Closes #934 
Created a duplicate branch of `feat/934-my-seedlot-page-cypress-test` with cleaner commit history.

### Changelog
#### New
- My seedlot page test

#### Changed
- Create A class seedlot test
- Added more entries of rows by looping fixture data

#### Removed
- Intercepts from the tests

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExb25udXM0aW0xcjA1cHluZHFqbXZ0dG4wa2tmajhrMWJtazZ1bjY5ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/HLIsuOVZewzoNQz0yB/giphy.gif" width="200"/>

2024-05-15 18:13 UTC, craigyu requested changes

2024-05-15 18:13 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/my-seedlots.cy.ts
> +      .find('td:nth-child(3)').then(($seedlotSpecies) => {
I think improvements can be made here, the usage of `td:nth-child()` is not robust enough, since the order of the columns might change as we might be adding new columns in the future.

![image](https://github.com/bcgov/nr-spar/assets/25162561/5b2dc938-41b6-4b31-9857-d6a1ec6fff16)

Let's get the seedlot number in the first column, the use the get by id method to get the text.

2024-05-16 16:04 UTC, craigyu approved these changes
Good work!

2024-05-16 16:20 UTC, RMCampos approved these changes
Good job!! 💯 

\\o
o//
\o/

2024-05-16 16:23 UTC, merged