Feat/1040 seedlot reg form step 1 and 3 tests
bcgov/nr-spar pull request #1186
Opened 2024-05-27 22:07 UTC by ngunner15

# Description
Closes #1040

### Changelog
#### New
- A class registration form cypress test
- Fixture for description of A class registration form

#### Changed
- cypress.config.ts

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExc3A3MmN1bDVycXdmY2xhdjZrdGJsa204cmp1bnRvYnFjYzljdXEzNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/V2ojLo7PvhVug/giphy.gif" width="200"/>

2024-05-28 18:39 UTC, RMCampos approved these changes
What a great job! Thank you!! 🥇 🚀

2024-05-29 16:09 UTC, craigyu requested changes

2024-05-29 16:09 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +      .should('have.value', seedlotData.cw.agencyAcronym);
why should it have `cw`'s agency acronym? when writing any code it's a good practice to constantly think about if other people can understand what you're doing here, if you think people might be confused then you need to add some comments. It might be easier to use `cw`'s acronym here but it doesn't make sense when reading the code. I have to find the code on line 317 to see you're changing the agency to the `cw`'s

2024-05-29 16:09 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  it('check interim storage information section details are correct', () => {
![image](https://github.com/bcgov/nr-spar/assets/25162561/51a4ee6b-95e0-42bc-a191-4ef41e28e9f9)

At what point are you testing the stuff described in the second checkbox? Specifically with the linkage between step 1 and 3's agency acronym?

2024-05-29 18:31 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +    const regData = regFormData.collector;
Oooh it's the section's title and subtitle, my bad, perhaps name them `agencyTitle` and `agencySubtitle`?

2024-05-30 18:56 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  it('check interim storage information section details are correct', () => {
Added new test with linkage description

2024-05-30 18:56 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +      .should('have.value', seedlotData.cw.agencyAcronym);
Added a test variable

2024-05-30 18:57 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  it('check collector information section details are correct', () => {
created multiple it blocks

2024-05-30 18:57 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  it('check collector agency section details are correct', () => {
created multiple its

2024-05-30 18:57 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +      .type(seedlotData.dr.agencyAcronym, { force: true })
removed some of the force option, added test variable

2024-05-30 18:58 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  });
use cy.task to get seedlot number, removed before block

2024-05-30 19:59 UTC, craigyu requested changes

2024-05-30 19:59 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  });
why do we need a before and beforeEach? Let's use one or the other

2024-05-30 20:07 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  });
I thought it would be better as the same code would not have to run repeatedly

2024-05-30 21:36 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  it('interim storage popup test', () => {
`it('Interim Storage client search modal')`

2024-05-30 21:36 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  it('interim storage popup test', () => {
https://github.com/spotify/should-up

2024-05-30 21:38 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  it('interim storage popup test', () => {
`it('[Interim Storage] client search modal')`

2024-05-30 21:38 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  it('interim storage date test', () => {
`it('[Interim Storage] date inputs')`

2024-05-30 21:40 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
Rename file to `a-class-seedlot-reg-form-collection-interim.cy.ts`

2024-05-30 21:41 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
remember to update the describe's string

2024-05-30 21:46 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  });
https://github.com/bcgov/nr-spar/pull/1186/commits/7d679d8ab08798c9a6ffde625bb1921d9ad26096

2024-05-30 23:59 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  });
https://github.com/bcgov/nr-spar/pull/1186/commits/f4692e95ae165de0bfc94f4fdcda38d393975413

2024-05-31 00:00 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  it('interim storage popup test', () => {
https://github.com/bcgov/nr-spar/pull/1186/commits/91663921827103fdec34bf0e2260eeb9cfb0b8d9

2024-05-31 00:00 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
> +  it('interim storage date test', () => {
https://github.com/bcgov/nr-spar/pull/1186/commits/91663921827103fdec34bf0e2260eeb9cfb0b8d9

2024-05-31 00:02 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
https://github.com/bcgov/nr-spar/pull/1186/commits/4368d350c1d6caf9faca18ebc5aebf451c7343fd

2024-05-31 00:02 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form.cy.ts
https://github.com/bcgov/nr-spar/pull/1186/commits/0d455257d0719b94839c12e6c093ec5319d10dd2

2024-06-05 04:46 UTC, craigyu approved these changes
APPROVED! just need to fix the typo in the comment below

2024-06-05 04:48 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-collection-interim.cy.ts
> +describe('A Class Seedlot Registration form, Container and Interim storage', () => {
Collection not "Container" 😉

2024-06-05 15:53 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-collection-interim.cy.ts
> +describe('A Class Seedlot Registration form, Container and Interim storage', () => {
https://github.com/bcgov/nr-spar/pull/1186/commits/a1ac495fd4ec92299cd7373289f0b8c927dd524c

2024-06-05 21:56 UTC, merged