feat: 855 development of seedlot review step 3 area of use
bcgov/nr-spar pull request #1199
Opened 2024-06-05 04:33 UTC by craigyu

# Description
Closes #855

KNOWN ISSUE:
The delete button in edit mode is giving off errors in console, but it's because of this:
https://github.com/carbon-design-system/carbon/pull/11893
Will talk to designers about it

### Changelog
#### New
- Area of Use read and edit function

#### Changed
- A-Class context to store the users' input data for this section, this section does not exist in the registration forms so it have to be created. the context file for a-class is becoming too large, might need to find a way to streamline it, but it works for now
- The Review Seedlot button can only be seen with seedlot that aren't in "PND" or "INC" status
- Refactored GET seedlot by seedlot number endpoint so it returns additional values rather than just the row in the `seedlot` table

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

2024-06-06 17:41 UTC, RMCampos approved these changes
it looks great and works nicely! Good job 🥇 🚀

2024-06-06 17:43 UTC, RMCampos commented
BTW, It's so nice to see all those TS types and null comparisions. Make Javascript looks so professional 😆

2024-06-06 18:43 UTC, craigyu commented
> BTW, It's so nice to see all those TS types and null comparisions. Make Javascript looks so professional 😆

Thank you! without them it works still but it's easier to do dev work this way

2024-06-06 18:48 UTC, craigyu commented
forgot to fix the carbon button issue from yesterday

2024-06-06 19:31 UTC, mgaseta requested changes
Nice job! :1st_place_medal: :100: 
Added a few markups, but nothing major :)

2024-06-06 19:31 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedlotDto.java
> +  private SeedPlanZoneDto priamrySpz;
Typo in `primary` (annotation and variable name).

2024-06-06 19:31 UTC, mgaseta commented on frontend/src/components/SeedlotReviewSteps/AreaOfUse/Read/index.tsx
> +              richSeedlotData?.priamrySpz
Fix field name :)

2024-06-06 19:31 UTC, mgaseta commented on frontend/src/components/SeedlotReviewSteps/AreaOfUse/Read/index.tsx
> +          Elevation, Latitude and longitude
Shouldn't `longitude` be capitalized?

2024-06-06 19:31 UTC, mgaseta commented on frontend/src/types/SpzDtoType.ts
> +
Remove empty file.

2024-06-06 19:31 UTC, mgaseta commented on frontend/src/views/Seedlot/ContextContainerClassA/utils.ts
> +  }
Should we create an object or array with all fields names and transform this bunch of ifs in a for? Or something similar, make it more elegant :monocle_face:

2024-06-06 19:48 UTC, craigyu commented on frontend/src/views/Seedlot/ContextContainerClassA/utils.ts
> +  }
Good idea but I think this way is easier to maintain personally, i don't like the idea that we have to maintain a list of properties to traverse to,  I also changed the some properties name so they are less confusing such as `latitudeMinMin` -> `minLatMinute`, in this case we'll have to maintain a map object instead. Regardless, I'll try to see what this solution looks like

2024-06-06 19:49 UTC, craigyu commented on frontend/src/components/SeedlotReviewSteps/AreaOfUse/Read/index.tsx
> +          Elevation, Latitude and longitude
Yea, bad figma, will fix
![image](https://github.com/bcgov/nr-spar/assets/25162561/9636f76c-d698-41cd-bc08-64fc6838956c)

2024-06-06 19:52 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedlotDto.java
> +  private SeedPlanZoneDto priamrySpz;
funny how a typo got propagated to the frontend too

2024-06-06 22:38 UTC, craigyu commented on frontend/src/views/Seedlot/ContextContainerClassA/utils.ts
> +  }
It's too much TypeScript gymnastic for me to spend more time on this, I'm going to keep the`if` blocks

Solution 1:
could work, but typescript complains
![image](https://github.com/bcgov/nr-spar/assets/25162561/eaabc351-7ff6-4eb3-ad65-e8e9e4db6868)
![image](https://github.com/bcgov/nr-spar/assets/25162561/1b33ca69-9b2d-4b5a-8d68-79bc37823420)

Solution 2:
Could work, but typescript complains
![image](https://github.com/bcgov/nr-spar/assets/25162561/c662690b-ce19-4ad8-8599-43f98b5ba30c)
![image](https://github.com/bcgov/nr-spar/assets/25162561/348a5bf4-c034-4b87-8e79-48d240f875f5)

Solution 3:
Could work, but typescript COMPLAINS
![image](https://github.com/bcgov/nr-spar/assets/25162561/01031154-097b-440f-bdae-424002e29fd6)
![image](https://github.com/bcgov/nr-spar/assets/25162561/327984c2-6377-4788-a90e-514b5bf21725)

2024-06-07 11:42 UTC, mgaseta commented on frontend/src/views/Seedlot/ContextContainerClassA/utils.ts
> +  }
OK, let's leave the ifs, thanks for the effort!
<img width="250" src="https://media1.giphy.com/media/mx0rj9sZRBcGTwEIX1/giphy.gif"/>

2024-06-07 23:33 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedlotDto.java
> +  private SeedPlanZoneDto priamrySpz;
https://github.com/bcgov/nr-spar/pull/1199/commits/c6a911d6360663dec0af157871ad88033bc2d2d2

2024-06-07 23:33 UTC, craigyu commented on frontend/src/components/SeedlotReviewSteps/AreaOfUse/Read/index.tsx
> +              richSeedlotData?.priamrySpz
https://github.com/bcgov/nr-spar/pull/1199/commits/c6a911d6360663dec0af157871ad88033bc2d2d2

2024-06-07 23:33 UTC, craigyu commented on frontend/src/components/SeedlotReviewSteps/AreaOfUse/Read/index.tsx
> +          Elevation, Latitude and longitude
https://github.com/bcgov/nr-spar/pull/1199/commits/c6a911d6360663dec0af157871ad88033bc2d2d2

2024-06-07 23:33 UTC, craigyu commented on frontend/src/types/SpzDtoType.ts
> +
https://github.com/bcgov/nr-spar/pull/1199/commits/c6a911d6360663dec0af157871ad88033bc2d2d2

2024-06-07 23:34 UTC, craigyu commented
@mgaseta 
sorry I didn't make separate commits for your requested changes, they all in here https://github.com/bcgov/nr-spar/pull/1199/commits/c6a911d6360663dec0af157871ad88033bc2d2d2

2024-06-11 12:28 UTC, mgaseta approved these changes
Nice job! :100: :rocket: :robot:

2024-06-11 12:28 UTC, mgaseta commented on frontend/src/components/SeedlotReviewSteps/AreaOfUse/utils.ts
> +export const validateElevatioRange = (inputObj: StringInputType): StringInputType => {
Typo on `validateElevationRange` (Missing n on elevation)

2024-06-11 12:28 UTC, mgaseta commented on frontend/src/components/SeedlotReviewSteps/AreaOfUse/AddtionalSpzItem.tsx
> +                className="danger-tertiary-btn"
Nice!

2024-06-11 17:02 UTC, craigyu commented on frontend/src/components/SeedlotReviewSteps/AreaOfUse/utils.ts
> +export const validateElevatioRange = (inputObj: StringInputType): StringInputType => {
fixed!

2024-06-11 20:35 UTC, DerekRoberts commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +              .toList();
This isn't right.  GitHub has no default vomit emoji!!  I need to use a comment!  :vomiting_face:

2024-06-11 22:28 UTC, merged