feat: 1141 ownership cypress test
bcgov/nr-spar pull request #1204
Opened 2024-06-05 21:48 UTC by ngunner15

# Description
Closes #1141

### Changelog
#### New
- cypress test for Ownership(Step 2) of seedlot form

#### Changed
- cypress.config

#### Removed
-

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

2024-06-06 15:11 UTC, craigyu reviewed
I know it's in draft mode, leaving a couple comments here just in case, please ignore if they are irrelevant

2024-06-06 15:11 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
> +      .blur();
is `.blur()` needed for button click?

2024-06-06 15:11 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
> +      .blur();
what's this for 🤔

2024-06-06 16:47 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
> +      .blur();
To get the error msg after adding 3 sections of owner agencies.

2024-06-06 21:52 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
> +      .blur();
https://github.com/bcgov/nr-spar/pull/1204/commits/4b573f97dc2e1445b285bd148008bbc7e0371329

2024-06-06 21:53 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
> +      .blur();
removed blur - https://github.com/bcgov/nr-spar/pull/1204/commits/4572409fb5e8cccb16dd7c8a5dd234771271ad2c

2024-06-11 17:09 UTC, craigyu requested changes
Good job Nisarg! 
As discussed, we should add one more test to check if the accordion title will change if the an owner's agency changes

2024-06-11 17:14 UTC, mgaseta approved these changes
Besides Craig's comments, LGTM!

2024-06-12 16:08 UTC, craigyu requested changes

2024-06-12 16:08 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
> +      .should('have.text', '80% owner portion');
This addition is great! but what about the title with the agency acronym, they change when agency is cleared and filled, there will be two cases to cover
1. Empty agency selection should display "... some values" on the accordion title,
2. With an agency selection should "dislay "... some value with the agency acronym" on the accordion title

2024-06-12 17:00 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
> +      .should('have.text', regFormData.ownership.accordionSubtitle);
@craigyu You can see the empty agency selection test here

2024-06-12 17:03 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
> +      .should('have.text', initialAccordionTitle);
@craigyu You can see an agency selection should "display "... some value with the agency acronym" on the accordion title

2024-06-12 17:09 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
> +      .should('have.text', '80% owner portion');
Those tests are in another it block

2024-06-12 17:45 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-ownership.cy.ts
> +      .should('have.text', initialAccordionTitle);
nice!

2024-06-12 17:46 UTC, craigyu approved these changes

2024-06-12 18:16 UTC, RMCampos approved these changes
After updating this branch code with `main`'s branch code, it works! Great job 💯

2024-06-12 18:46 UTC, merged