feat: 815 seedlot review table for tsa admin
bcgov/nr-spar pull request #1205
Opened 2024-06-05 22:34 UTC by mgaseta

# Description
Closes #815

### Changelog
#### New
- Created new API call to TSC admin endpoints
- Added new variable to authentication context to check if user is admin or not
- Added new columns to seedlot tables and the logic to display them when necessary

#### Changed
- Nothing :)

#### Removed
- Nothing :)

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media1.giphy.com/media/11shDO8NnZDYpa/giphy.gif"/>

2024-06-06 17:49 UTC, RMCampos commented
You should win a badge for the great skills on gifs choice

2024-06-06 18:12 UTC, RMCampos requested changes
Great job 🥇.

It seems the "not TSC Admin" version is still being displayed, instead of the right one, though. Let's take a look.

2024-06-07 11:35 UTC, mgaseta commented
On the new Review Seedlots screen, there is no endpoint to search for seedlots by their status.
![Screenshot from 2024-06-07 08-32-07](https://github.com/bcgov/nr-spar/assets/105936322/dec01c34-4ee0-4e34-8af5-1ca5785de124)
 I suggest we create a separate task to implement the endpoint and then update the new screen.

2024-06-11 17:08 UTC, craigyu requested changes
Looking good! left one suggestion for discussion

2024-06-11 17:22 UTC, craigyu commented on frontend/src/api-service/ApiConfig.ts
> +  tscAdmin: `${serverHost}/api/tsc-admin`,
Suggestion
Have this defined more specific, e.g.
```javascript
{
  ...,
  tscAdminSeedlots: `${serverHost}/api/tsc-admin/seedlots`,
}

2024-06-11 17:32 UTC, mgaseta commented on frontend/src/api-service/ApiConfig.ts
> +  tscAdmin: `${serverHost}/api/tsc-admin`,
Hmmm, I like the idea of having more specific paths, but other paths are not designed like this, `orchardAPI.ts` for instance,  and on the future we will have more data to fetch from the admin endpoint. Maybe we can leave like this and create a backlog task to re-design our endpoints paths on the FE?

2024-06-11 22:13 UTC, craigyu commented on frontend/src/api-service/ApiConfig.ts
> +  tscAdmin: `${serverHost}/api/tsc-admin`,
yea sure, maybe something that can accept query params instead of building it ourselves

2024-06-11 22:13 UTC, craigyu approved these changes

2024-06-12 20:50 UTC, RMCampos approved these changes
Great job! 💯 

Only one question, non blocking.

2024-06-12 20:50 UTC, RMCampos commented on frontend/src/routes/constants.ts
> +  REVIEW_SEEDLOTS: '/seedlots/review-seedlots',
question (non-blocking): why REVIEW_SEEDLOTS instead of SEEDLOTS_REVIEW?

2024-06-12 23:03 UTC, craigyu commented on frontend/src/routes/constants.ts
> +  REVIEW_SEEDLOTS: '/seedlots/review-seedlots',
good catch!

We actually have a Review Seedlot page
![image](https://github.com/bcgov/nr-spar/assets/25162561/010d559b-6fd0-487f-a08b-b25898ae6dc3)

So to avoid confusions, can we name it `TSC_SEEDLOT_TABLE: '/seedlots/tsc-all'` 

Kinda bad naming for the path, need some brainstorming

2024-06-12 23:04 UTC, craigyu requested changes
We need to find a solution for a better path for TSC admin's seedlot table

2024-06-13 12:53 UTC, RMCampos commented on frontend/src/routes/constants.ts
> +  REVIEW_SEEDLOTS: '/seedlots/review-seedlots',
Yeah, that works for me. Or something like `TSC_SEEDLOTS_REVIEW: '/seedlots/tsc-seedlots-review'`?

2024-06-13 14:21 UTC, mgaseta commented on frontend/src/routes/constants.ts
> +  REVIEW_SEEDLOTS: '/seedlots/review-seedlots',
Good catch! How about `TSC_SEEDLOTS_TABLE: '/seedlots/tsc-seedlots-review'`? 
(Just unifying both of your ideas >.<)

2024-06-18 18:03 UTC, merged