Feat/1222 spu endpoint
bcgov/nr-spar pull request #1224
Opened 2024-06-12 21:40 UTC by craigyu

# Description
Closes #1222

Fetch primary SPU information if a seedlot has a primary orchard, append that spu data to the seedlotDto 

### Changelog
#### New
- Oracle Endpoint GET `/api/seed-plan-unit/{spuId}`

#### Changed
- Postgres Endpoint GET `/api/seedlots/{seedlotNumber}`, added `primarySpu: spuDto` to the response dto

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media1.giphy.com/media/dV3GXudtLAbTi/giphy.gif" width="100"/>

2024-06-17 13:02 UTC, mgaseta approved these changes
Nice job! :1st_place_medal: :100: 
Added only a few non-blocking comments :)
<img width="150" src="https://media1.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif"/>

2024-06-19 20:44 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/oracle/SpuDto.java
> +  private Integer latitudeMinutesMax;
Good question and great eyes!
The longitude data does not exist on the SPU table, we'll have to use the collection latitude data as a fall back

2024-06-20 18:54 UTC, RMCampos requested changes
Good job Craig! 💯 

Some minor changes, though 🤓

2024-06-20 18:54 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedPlanUnitEndpoint.java
> +  @GetMapping(path = "/{spuId}")
suggestion (non-blocking): no need to define `path`, you can pass only the string.

2024-06-20 18:54 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedPlanUnitEndpoint.java
> +              + " additional data such as SPZ code.")
issue: prefer text blocks with for multi-line strings, with three double quote marks.

2024-06-20 18:54 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedPlanUnitEndpoint.java
> +                    schema = @Schema(implementation = SpuDto.class))),
issue: no need to define `content` when the content is the same as the return type.

2024-06-20 18:54 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedPlanUnitEndpoint.java
> +      @PathVariable("spuId") @Parameter(description = "The Seed Plan Unit Id") String spuId) {
issue: missing `required = true` for the `@Parameter()` definition.

2024-06-20 18:54 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedPlanUnitEndpoint.java
> +      @PathVariable("spuId") @Parameter(description = "The Seed Plan Unit Id") String spuId) {
Also, this line it's not compliant with the maximum length of 100.

2024-06-20 18:54 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/service/SeedPlanUnitService.java
> +   */
issue: missing Javadoc variables. The return description has its own section :)

2024-06-20 18:54 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +      SparLog.info("No seedlot orchard found for seedlot: {}", seedlotNumber);
suggestion: how about adding that "No primary orchard" was found, instead of only orchard? (Add 'primary' word)?

2024-06-20 18:54 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +    // Find the active SPU id associated with this seedlot ochard
typo: ochard

2024-06-21 23:48 UTC, craigyu commented
Thanks for the review, @RMCampos all comments should be addressed here: https://github.com/bcgov/nr-spar/pull/1224/commits/c7233a6e1922fab5d72ca6e05847cbb3adfdadcb

2024-06-24 18:37 UTC, RMCampos approved these changes
It looks great! All good!

2024-06-24 22:51 UTC, merged