Feat/1221 spz list endpoint modification
bcgov/nr-spar pull request #1225
Opened 2024-06-12 22:58 UTC by craigyu

# Description
Closes #1221 

### Changelog
#### New
- None

#### Changed
-  `/api/area-of-use/tested-parent-trees/spz-list` is now`/api/area-of-use/spz-list/vegetation-code/{vegCode}` The old SPAR lets users select any spz they want then deny them once a user submits the data if it's invalid. This modified endpoint provides users with valid options to begin with so TSC admins should can age slower. 
- moved `/api/orchards/area-of-use/spu/{spuId}` under its own Area Of Use section as`/api/area-of-use/spu/{spuId}` so it makes more sense

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media1.giphy.com/media/C6JQPEUsZUyVq/giphy.gif" width="200"/>

2024-06-19 20:41 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/AreaOfUseEndpoint.java
> +    SparLog.info("Recevied request to fetch all SPZs for vegetation code: {}", vegCode);
https://github.com/bcgov/nr-spar/pull/1225/commits/9a97a48d3a3a9eddfd1a624a9c86e45765fe0ee3
fixed

2024-06-20 20:13 UTC, RMCampos requested changes
Great job as always! 🥇

Minor requests though.

2024-06-20 20:13 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/AreaOfUseEndpoint.java
> +      @Parameter(description = "The SPU (Seed Planning Unit) ID") @PathVariable("spuId")
issue: missing `required = true`. Sorry for bug you this much about it. if possible, having an example would be good 🚀

2024-06-20 20:13 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/service/AreaOfUseService.java
> +    result.setAreaOfUseSpuGeoDto(setCalculatedSpuGeoData(spuList));
praise: very nice adding a separate method. We could do that more often. 🥇

2024-06-20 20:13 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/service/AreaOfUseService.java
> +    List<SeedPlanUnit> filteredMinLatMiunteSpu =
typo: filteredMinLat**Miunte**Spu instead of filteredMinLat**Minute**Spu

2024-06-20 20:13 UTC, RMCampos commented on frontend/src/shared-constants/shared-constants.ts
> +export const PLACE_HOLDER = '--';
praise: Like a pro 😎

2024-06-21 23:30 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/AreaOfUseEndpoint.java
> +  @GetMapping(path = "/spu/{spuId}", produces = MediaType.APPLICATION_JSON_VALUE)
Yes, I'll keep this in mind, usually when I need to add an endpoint I just copy one from somewhere then change it

2024-06-21 23:35 UTC, craigyu commented
thanks for the review @RMCampos, all issues should be addressed in this commit https://github.com/bcgov/nr-spar/pull/1225/commits/141103444da582adcccfe177485fb266d472fba9

2024-06-24 18:55 UTC, RMCampos approved these changes
Awesome! All good! 🚀

2024-06-24 22:21 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/AreaOfUseEndpoint.java
> +  @GetMapping(path = "/spu/{spuId}", produces = MediaType.APPLICATION_JSON_VALUE)
LOL what do you mean by sound personal, I see nothing personal here! these good suggestions

2024-06-24 22:21 UTC, merged