feat: 1142 orchard step cypress test
bcgov/nr-spar pull request #1227
Opened 2024-06-17 17:09 UTC by ngunner15

# Description
Closes #1142 
Testing for this step
![image](https://github.com/bcgov/nr-spar/assets/31422051/2f5dcb91-a3a9-42d7-861a-339f1411c3c3)

### Changelog
#### New
- Cypress test for Orchard step

#### Changed
- cypress.config
- A class seedlot fixture

#### Removed
-

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

2024-06-19 18:04 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +  it('store second Parent Tree Number in an array', () => {
Second orchard's parent tress

2024-06-25 23:12 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +  it('store second Parent Tree Number in an array', () => {
https://github.com/bcgov/nr-spar/pull/1227/commits/346e20d74f8e2877ada02c40afaa0cdface299b4

2024-06-25 23:14 UTC, craigyu approved these changes
Good job!

2024-06-25 23:44 UTC, craigyu requested changes
![image](https://github.com/bcgov/nr-spar/assets/25162561/f8bd8936-a2d0-4376-8102-de768385bd74)

it's failing

2024-06-26 00:04 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +      .should('have.value', 'F2 - Measured Cone Volume');
Also I noticed some things that can be improved on, let's have a discussion tomorrow. 

How can we know for sure that the first gametic-combobox is the female one, and how do we know the second option you click will always be `F2 - Measured Cone Volume`?

2024-06-26 18:35 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +  });
need to update this method, use ownership as a reference

2024-06-26 21:21 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +      .should('have.value', 'F2 - Measured Cone Volume');
https://github.com/bcgov/nr-spar/pull/1227/commits/a24c2984605e6699c7f5f8e2fe137caac8704941

2024-06-27 18:32 UTC, craigyu requested changes

2024-06-27 18:32 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +  it.only('Change gamete information', () => {
mistake

2024-06-27 18:32 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +      .should('have.value', 'M3 - Pollen Volume Estimate by 100% Survey');
how is this different than your previous implementation? 
it's still clicking on an item in a list with an arbitrary position number, then checking if has the correct value.
As we discussed before, we shouldn't assume an item will be at a specific position in a list dynamically generated with backend data

What needs to be done instead:

1. open the combobox
2. find a specific element, for example, find the M3 in the list, then click on it
3. Verify M3 has been selected

2024-06-27 18:42 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +  it.only('Change gamete information', () => {
https://github.com/bcgov/nr-spar/pull/1227/commits/874c8cdb080b3cbc62ae2e97dc0754134133b5ec

2024-06-27 18:42 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +      .should('have.value', 'M3 - Pollen Volume Estimate by 100% Survey');
https://github.com/bcgov/nr-spar/pull/1227/commits/874c8cdb080b3cbc62ae2e97dc0754134133b5ec

2024-07-04 19:05 UTC, RMCampos approved these changes
LGTM

2024-07-04 19:19 UTC, craigyu commented
#1329 has been merged, can you replace the save functions here? +1 🍺 virtual beer for effort

2024-07-08 17:30 UTC, DerekRoberts commented
Two and three weeks is a long time to keep PRs open, mostly due to sitting on resources.  Please reopen this and #1273 when needed.

2024-07-23 18:19 UTC, craigyu approved these changes

2024-07-23 18:19 UTC, merged