Feat/1421 refactor text
bcgov/nr-spar pull request #1427
Opened 2024-07-22 18:39 UTC by ngunner15

# Description
Closes #1421 

### Changelog
#### New
- None

#### Changed
- Text updates
- Sorting checkbox alphabetically

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExMjd1NXRmZjBnODRrODlrYXV0Nm1hMzZ4MGh6YThxZzM2czNsYnluMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/12qffSWzrRGphu/giphy.webp" width="200"/>

2024-08-01 19:07 UTC, mgaseta approved these changes
LGTM!

2024-08-02 02:41 UTC, DerekRoberts commented
Closing to free resources.  Reopen when ready!

2024-08-02 19:37 UTC, craigyu commented
I will reopen this when I review the PR

2024-08-06 17:15 UTC, craigyu requested changes

2024-08-06 17:15 UTC, craigyu commented on frontend/src/components/PageTitle/index.tsx
> +  subtitle?: string | React.ReactNode;
Adding a question mark meaning `subtitle` can be potentially `undefined`, check line 83 of this file `<Subtitle text={subtitle} />`, the Subtitle expects a text prop which can't be undefined. You could something like this:
```javascript
{
  subtitle
      ? <Subtitle text={subtitle} />
      : null
}
```

2024-08-06 17:15 UTC, craigyu commented on frontend/src/types/FavActivityTypes.ts
> +  description?: string;
same thing, be careful when you make a prop optional.

Check the usage here `frontend/src/components/Card/FavouriteCard/index.tsx`

line 88

```javascript
 <p className="fav-card-content-description">{favObject.description}</p>
```

What will happen here if description is undefined?

Check if other places that use `FavActivityType` will reference the `description` value

2024-08-06 17:21 UTC, craigyu commented on frontend/src/types/FavActivityTypes.ts
> +  description?: string;
![image](https://github.com/user-attachments/assets/5417808b-8275-4182-954c-7a89c9c21a54)

As we can see the element <p> is still rendered even though it's not needed, generally speaking, we should try to avoid render unused elements

2024-08-07 18:05 UTC, ngunner15 commented on frontend/src/types/FavActivityTypes.ts
> +  description?: string;
https://github.com/bcgov/nr-spar/pull/1427/commits/c75c9c20dcf7f39b84404ab76853756283807ec8

2024-08-07 18:05 UTC, ngunner15 commented on frontend/src/types/FavActivityTypes.ts
> +  description?: string;
https://github.com/bcgov/nr-spar/pull/1427/commits/e08e82bd8d554979050b8e4ca73e22bd663edf83

2024-08-07 18:06 UTC, ngunner15 commented on frontend/src/components/PageTitle/index.tsx
> +  subtitle?: string | React.ReactNode;
https://github.com/bcgov/nr-spar/pull/1427/commits/c6cd0dc9a571f7fb41a74218504f437c151a94a4

2024-08-07 18:06 UTC, ngunner15 commented on frontend/src/components/PageTitle/index.tsx
> +  subtitle?: string | React.ReactNode;
https://github.com/bcgov/nr-spar/pull/1427/commits/d3448e2fba6f482c93d7bf97b659555d47530e6c

2024-08-07 19:47 UTC, craigyu commented on frontend/src/types/FavActivityTypes.ts
> +  description?: string;
nice

2024-08-07 19:49 UTC, craigyu requested changes

2024-08-07 19:49 UTC, craigyu commented on frontend/src/views/Seedlot/CreateAClass/index.tsx
> +          subtitle={null}
you don't have to do a null, you can just remove this line now and not provide PageTitle with a subtitle prop, since it's optional, same goes to the other `subtitle={null}`

2024-08-07 19:51 UTC, craigyu commented
your front-end build failed, please check out the error in the action run

2024-08-07 20:06 UTC, ngunner15 commented on frontend/src/views/Seedlot/CreateAClass/index.tsx
> +          subtitle={null}
I haven't made the subtitle prop optional, should I do that?

2024-08-07 20:12 UTC, craigyu commented on frontend/src/views/Seedlot/CreateAClass/index.tsx
> +          subtitle={null}
oh did you revert that change? yea let's make it optional

2024-08-07 23:30 UTC, ngunner15 commented on frontend/src/views/Seedlot/CreateAClass/index.tsx
> +          subtitle={null}
https://github.com/bcgov/nr-spar/pull/1427/commits/55c78e8c51660f87fd4fddd40f68f1a21e0680ae

2024-08-07 23:30 UTC, ngunner15 commented on frontend/src/views/Seedlot/CreateAClass/index.tsx
> +          subtitle={null}
https://github.com/bcgov/nr-spar/pull/1427/commits/2a6e74681250bc36cbbb64d5268798e8b3be2f09

2024-08-08 16:43 UTC, craigyu commented
@ngunner15  your frontend build is still failing, please check the error in the action

2024-08-08 17:40 UTC, DerekRoberts commented
> @ngunner15 your frontend build is still failing, please check the error in the action, it's not an issue with GitHub btw

@ngunner15 Try locally with `cd frontend && docker build . -t frontend`.

It appears to be failing during transpilation (ts -> js conversion).  Looks like FavActivityType needs a description property added.

```
> nr-spar-webapp@0.9.4 build
> tsc && vite build

src/config/FavouriteActivitiyMap.ts(10,5): error TS2353: Object literal may only specify known properties, and 'description' does not exist in type 'FavActivityType'.
src/config/FavouriteActivitiyMap.ts(27,5): error TS2353: Object literal may only specify known properties, and 'description' does not exist in type 'FavActivityType'.
src/config/FavouriteActivitiyMap.ts(36,5): error TS2353: Object literal may only specify known properties, and 'description' does not exist in type 'FavActivityType'.
src/config/FavouriteActivitiyMap.ts(45,5): error TS2353: Object literal may only specify known properties, and 'description' does not exist in type 'FavActivityType'.
```

2024-08-08 19:57 UTC, craigyu commented on frontend/src/views/Seedlot/CreateAClass/index.tsx
> +          subtitle={null}
nice

2024-08-08 19:59 UTC, craigyu requested changes
good work, just need to fix some components that are making build fail

2024-08-09 01:08 UTC, ngunner15 commented
> > @ngunner15 your frontend build is still failing, please check the error in the action, it's not an issue with GitHub btw
> 
> @ngunner15 Try locally with `cd frontend && docker build . -t frontend`.
> 
> It appears to be failing during transpilation (ts -> js conversion). Looks like FavActivityType needs a description property added.
> 
> ```
> > nr-spar-webapp@0.9.4 build
> > tsc && vite build
> 
> src/config/FavouriteActivitiyMap.ts(10,5): error TS2353: Object literal may only specify known properties, and 'description' does not exist in type 'FavActivityType'.
> src/config/FavouriteActivitiyMap.ts(27,5): error TS2353: Object literal may only specify known properties, and 'description' does not exist in type 'FavActivityType'.
> src/config/FavouriteActivitiyMap.ts(36,5): error TS2353: Object literal may only specify known properties, and 'description' does not exist in type 'FavActivityType'.
> src/config/FavouriteActivitiyMap.ts(45,5): error TS2353: Object literal may only specify known properties, and 'description' does not exist in type 'FavActivityType'.
> ```

Thanks for the info 👍

2024-08-09 15:35 UTC, RMCampos approved these changes
LGTM

2024-08-12 16:15 UTC, craigyu approved these changes

2024-08-12 16:15 UTC, merged