Feat/1361 add cancel button at seedlot review page
bcgov/nr-spar pull request #1452
Opened 2024-07-25 22:54 UTC by craigyu

# Description
Closes #1361 
!mportant:
Need to nuke the a-class-seedlot-save table, or these changes will cause trouble with existing drafts

Not described in the issue:
Refactored the behaviour of A-Class seedlot Context and ApplicantAgencyFields, the idea is let one component to handle the data fetching, the component displays the client acronym but stores client number. Renamed things from agency to client so it's consistent with forest client api. 
- Renamed to ClientAndCodeInput
- default checkbox prop is now optional

### Changelog
#### New
- [react-beforeunload](https://www.npmjs.com/package/react-beforeunload) allows confirmation before url change
- Back to review / Back button on Seedlot Review page
- Modal that confirms user's action
- shameless plugin with my own photo 🥷

#### Changed
- ApplicantAgencyFields -> ClientAndCodeInput
- New pictogram for Review Seedlot card (NOT Seedlot Review)

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media3.giphy.com/media/oWUuipyxfBYGuvEn2K/giphy.gif"/>

2024-07-29 17:45 UTC, craigyu commented
fixing Cypress test atm

2024-07-31 13:03 UTC, mgaseta approved these changes
LGTM!
Added only one small mark-up.

2024-07-31 16:55 UTC, craigyu commented on frontend/src/views/Seedlot/ContextContainerClassA/index.tsx
> +      // let clientAgencies: ClientAgenciesByCode = {};
it's dead

2024-07-31 17:00 UTC, RMCampos requested changes
Great job! Some typos, nothing more.

🥇 🚀

2024-07-31 17:00 UTC, RMCampos commented on frontend/src/components/LotApplicantAndInfoForm/constants.ts
> +export const clientAndCodeInputText = (isReview: boolean | undefined): ClientAndCodeInputTextType => ({
lint issue:
```
~/Projects/nr-spar/frontend/src/components/LotApplicantAndInfoForm/constants.ts
  5:1  error  This line has a length of 103. Maximum allowed is 100  max-len
```

2024-07-31 17:00 UTC, RMCampos commented on frontend/src/components/ClientAndCodeInput/index.tsx
> +  const formatDisplayedLocCode = (formatedCode: string) => {
typo: formated instead of formatted

2024-07-31 17:00 UTC, RMCampos commented on frontend/src/components/ClientAndCodeInput/index.tsx
> +  const formatDisplayedAcronym = (formatedAcronym: string) => {
typo: formated instead of formatted

2024-07-31 17:00 UTC, RMCampos commented on frontend/src/components/ClientAndCodeInput/index.tsx
> +    const formatedCode = value ? formatLocationCode(value) : '';
typo: formated instead of formatted

2024-07-31 17:00 UTC, RMCampos commented on frontend/src/components/SeedlotReviewSteps/AuditInfo/index.tsx
> +              seedlotData?.auditInformation.updateTimestamp
typo: uptated instead of updated (twice, lines 47 and 55. Not changed by you, tho)

2024-07-31 17:00 UTC, RMCampos commented on frontend/src/views/Seedlot/SeedlotReview/styles.scss
> +
question (non-blocking): I'm getting a warning at line 46, asking to define: `Also define the standard property 'appearance' for compatibilityscss(vendorPrefix)`

2024-07-31 17:05 UTC, craigyu commented on frontend/src/views/Seedlot/SeedlotReview/styles.scss
> +
hmm, what's the suggested fix? does it have one?

2024-07-31 18:39 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +    // Intercept the call before step 5 monuts
typo: mounts

2024-07-31 18:40 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +    // Intercept the call before step 5 monuts
typo: mounts

2024-07-31 18:40 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +    // Intercept the call before step 5 monuts
typo: mounts

2024-07-31 18:40 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/a-class-seedlot-reg-form-orchard.cy.ts
> +    // Intercept the call before step 5 monuts
typo: mounts

2024-08-01 04:56 UTC, craigyu commented
@RMCampos @ngunner15 

Alright guys, it looks like I can't spell for 💩
here are the updates:
- Typo and lint: https://github.com/bcgov/nr-spar/pull/1452/commits/50ba26630740e258ee549d39d6d863f169e3d872
- Back modal update https://github.com/bcgov/nr-spar/pull/1452/commits/2851cf9623d330f061764652a3bcc4de27b61ecd
- Confirm modal when saving and update the status https://github.com/bcgov/nr-spar/pull/1452/commits/f6533f4a5031ff10b16373e11b5412c1d157ada0
- Also fixed a problem where ownership's default method of payment is sometimes not filled

2024-08-01 21:07 UTC, RMCampos approved these changes
LGTM 🚀

2024-08-01 22:02 UTC, merged