fix: 1387 update date rules in seedlot registration screens
bcgov/nr-spar pull request #1465
Opened 2024-08-01 18:37 UTC by mgaseta

# Description
Closes #1387

### Changelog
#### New
- Added limitation to date fields on seedlot registration form
- Added validation to interim step end date field

#### Changed
- Nothing :)

#### Removed
- Nothing :)

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?
<img width="250" src="https://media2.giphy.com/media/pHWFj7mt7qyBs2XYC6/giphy.gif"/>

2024-08-08 16:58 UTC, craigyu requested changes
Good work! Added a few suggestions 

Do you think we need to check the dates before data is changed in methods such as `handleStorageDates`?  I like the idea of double checking since the `maxDate` only limit the user's selection but does not specifically invalidate an input

2024-08-08 16:58 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +    }
use Luxon instead of moment, let's phase out moment since it's not recommended by their own devs anymore.

2024-08-08 16:58 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx
> +
Can we have this as a method in `src/utils/DateUtils.ts` ?

You might be able to do this with luxon so it's more readable than regex

```javascript
import { DateTime as luxon } from 'luxon';

// Get today's date and time
const now = luxon.now().setZone('America/Vancouver').toFormat('yyyy-MM-dd');

// should give you now = '2024-08-07'
```

2024-08-08 16:58 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx
> +            maxDate={!isReview ? maxDate : null}
I recently learned that in React, when dealing with optional props, it is generally better to pass undefined rather than null if you want to indicate that the prop is not provided. This is because undefined more clearly conveys the absence of a value, whereas null represents an explicitly empty value. 

In this case it would be 
`maxDate={!isReview ? maxDate : undefined}`

2024-08-09 14:01 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx
> +
Sure, good idea! Here it is: https://github.com/bcgov/nr-spar/pull/1465/commits/a7b391412de3c65d27d09e306186d1db55ef65c1

2024-08-09 14:01 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx
> +            maxDate={!isReview ? maxDate : null}
Nice to know!
Fixed here: https://github.com/bcgov/nr-spar/pull/1465/commits/a7b391412de3c65d27d09e306186d1db55ef65c1

2024-08-09 14:07 UTC, mgaseta commented
> Do you think we need to check the dates before data is changed in methods such as `handleStorageDates`? I like the idea of double checking since the `maxDate` only limit the user's selection but does not specifically invalidate an input

I don't it's necessary, I think the message is quite clear by not letting them select the dates, and if they input a future date manually, it'll trigger the error and show the invalid message.

2024-08-12 19:48 UTC, RMCampos approved these changes
LGTM 💯 

Great job

2024-08-13 21:58 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +    }
nice

2024-08-13 22:17 UTC, craigyu requested changes
good changes, just a couple things to modify

2024-08-13 22:17 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx
> +    const isInvalid = isoEndDate < isoStartDate;
the `utcToIsoSlashStyle` actually converts time from UTC-0 to Vancouver time, it will assume the input is in UTC-0, in this case you'll need to convert local date to local date, but it looks like the value is already formatted, so there's no conversion needed

2024-08-13 22:17 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +
same here, the dates are converted when the payload is generated for backend

2024-08-14 17:59 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx
> +    const isInvalid = isoEndDate < isoStartDate;
Fixed here: https://github.com/bcgov/nr-spar/pull/1465/commits/592827c88649dfa27cbe8580d300d4fe315a0393

2024-08-14 17:59 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +
Fixed here: https://github.com/bcgov/nr-spar/pull/1465/commits/592827c88649dfa27cbe8580d300d4fe315a0393

2024-08-14 21:57 UTC, craigyu approved these changes

2024-08-16 06:24 UTC, merged