feat: 1435 different parent tree gw values and date update
bcgov/nr-spar pull request #1491
Opened 2024-08-09 06:24 UTC by craigyu

# Description
Closes #1435
!!! **Needs to wipe the draft table after merge** !!!
ETL should be unaffected

I will fix and add tests on Monday, let's get changes in so we can test and spot issues. Currently, affected tests are commented out but marked with `TODO`.

I will also remove the oracle-api endpoint `/api/orchards/parent-trees/vegetation-codes/{vegCode}`, the new endpoint is now `/api/parent-trees/vegetation-codes/{vegCode}` 

### Changelog
#### New
- Migration file that adds default bv values

#### Changed
- how parents are fetched by a vegetation code
- genetic worth values are filled by matching primary SPU id, use default for everything else
- parent tree's genetic worth value is displayed in red and with brackets if it's using default value
- Frontend now fetches orchards from backend API instead of Oracle-api so it can have an spu id
- Stores UTC on backend, display Vancouver date/time on frontend

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media0.giphy.com/media/3ohjUS0WqYBpczfTlm/giphy.gif" width="200"/>

2024-08-09 17:49 UTC, mgaseta approved these changes
Nice job @craigyu!
<img width="200" src="https://media3.giphy.com/media/joeRYmOkLaj2U6hwdj/giphy.gif"/>
Added a few markups, but nothing major, I'll tag them as resolved so we can merge the PR as soon as possible, but you can take a look at them later.

2024-08-09 19:17 UTC, RMCampos requested changes
Great job Craig! Only a few items. 💯 🥇

2024-08-09 19:17 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/entity/GeneticWorthEntity.java
> +  @Column(name = "default_bv")
issue: missing some props `nullable = false, precision = 3, scale = 1`

2024-08-09 19:17 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/oracleapi/entity/projection/ParentTreeProj.java
> +  void setGeneticQualityValue(BigDecimal geneticQualityValue);
issue: No need to create `setters`, only `getters`. Sorry for don't noticing before.

2024-08-09 19:17 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/oracleapi/service/ParentTreeService.java
> +  /** Find all parent trees under a vegCode. */
issue: missing parameters and return keys.

2024-08-09 19:17 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/oracleapi/repository/ParentTreeRepository.java
> +        """,
issue: this query is giving too much records. (~ 6 thousands for FDC,~ 11 thousands for PLI). Let's discuss and find a way of improving it.

2024-08-09 19:17 UTC, RMCampos commented on frontend/src/utils/SeedlotUtils.ts
> +  approvedAt: utcToLocalFormat(seedlot.approvedTimestamp)
question (non-blocking): I'm not sure we're actually displaying the time. I can see only dates here. That's the way it should be?

2024-08-12 16:43 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/OrchardService.java
> +  public List<ActiveOrchardSpuEntity> findAllSpu(Boolean active) {
Yes, i made it so that when it's null it will fetch everything regardless the active status

2024-08-12 16:57 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/entity/GeneticWorthEntity.java
> +    this.defaultBv = defaultBv;
It's to set the default breeding value, it doesn't work without it

![image](https://github.com/user-attachments/assets/63865964-7e99-4314-878f-eeaa618d79b7)

2024-08-12 17:00 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/oracleapi/entity/projection/ParentTreeProj.java
> +  void setGeneticQualityValue(BigDecimal geneticQualityValue);
![image](https://github.com/user-attachments/assets/b8ef39d7-7540-4d0e-9a19-73208e84e1be)

Without them the tests won't work, it's the only usage though, let's leave them in?

2024-08-12 17:05 UTC, craigyu commented on frontend/src/utils/SeedlotUtils.ts
> +  approvedAt: utcToLocalFormat(seedlot.approvedTimestamp)
I don't recall seeing time on Figma, i think adding time the column will be too wide in tables, let's consult @mmarsoleta later in the standup

2024-08-12 17:06 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/OrchardService.java
> +    List<OrchardDto> list = oracleApiProvider.findOrchardsByVegCode(vegCode);
https://github.com/bcgov/nr-spar/pull/1491/commits/6e39131f9d884f72ffeb1f275a3b2d68b069ff56

2024-08-12 17:06 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +                // We cannot know this for sure, see explaination down below.
https://github.com/bcgov/nr-spar/pull/1491/commits/9842dc8a13cd8121efd17a62ab365866406275a5

2024-08-12 17:07 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/index.tsx
> +import ClassAContext from '../../../../views/Seedlot/ContextContainerClassA/context';
https://github.com/bcgov/nr-spar/pull/1491/commits/8e434e7bd2ebdc0c1b5d59bfb8678def116f4b78

2024-08-12 17:08 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/entity/GeneticWorthEntity.java
> +  @Column(name = "default_bv")
https://github.com/bcgov/nr-spar/pull/1491/commits/44382a0fd2d98ff5c93151900f824d9f9c81a89f
thanks for providing a solution

2024-08-12 17:08 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/oracleapi/service/ParentTreeService.java
> +  /** Find all parent trees under a vegCode. */
https://github.com/bcgov/nr-spar/pull/1491/commits/6ae622c58904f0060250b681511dd9b85fb6aed9

2024-08-12 17:16 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/oracleapi/repository/ParentTreeRepository.java
> +        """,
![image](https://github.com/user-attachments/assets/5a3070fa-12f1-4a18-9311-37857fbe8f46)

https://github.com/bcgov/nr-spar/pull/1491/commits/ae4b5658f079d0c14735ad4bf384003f113a0430 should be fixed with Ron's edition shown in the screenshot

2024-08-12 18:00 UTC, RMCampos approved these changes
LGTM

2024-08-13 00:29 UTC, merged