feat: add go to seedlot button in seedlot dashboard
bcgov/nr-spar pull request #1643
Opened 2024-09-25 22:25 UTC by xiaopeng0202

# Description
Closes #1626 

### Changelog
#### New
- added go to seedlot button in seedlot dashboard

#### Changed
- refactored and created seedlot navigator component

### How was this tested?
- [ ] 🧠 Not needed
- [ ] 👀 Eyeball
- [ ] 🤖 Added tests

<img src="https://media3.giphy.com/media/oUuTdH8aEUE5fWKUcM/giphy.gif"/>

2024-09-26 15:05 UTC, mgaseta requested changes
I think this task was to add the seedlot navigator to "My Seedlots" page, not to the "Seedlot Dashboard", can you confirm @SLDonnelly and @kevinginley ?

2024-09-26 16:07 UTC, kevinginley commented
> I think this task was to add the seedlot navigator to "My Seedlots" page, not to the "Seedlot Dashboard", can you confirm @SLDonnelly and @kevinginley ?

Yes that's right @mgaseta

2024-09-26 22:46 UTC, xiaopeng0202 commented
> I think this task was to add the seedlot navigator to "My Seedlots" page, not to the "Seedlot Dashboard", can you confirm @SLDonnelly and @kevinginley ?

We will add the component in both my seedlot and seedlot dashboard page

2024-09-26 23:08 UTC, kevinginley commented
@xiaopeng0202 @mgaseta 

On my screen there are some finicky alignment issues (fyi I'm using Chrome)

![image](https://github.com/user-attachments/assets/f6b529b8-b982-4ad8-b87e-ee577530911d)

![image](https://github.com/user-attachments/assets/21105509-2b2e-459f-b4e1-6328720a4594)

Ideally the right edge of the "Go to seedlot" button would align with the right edge of the table, whereas here it is spilling outside of the table, which added a scrollbar to the bottom of my screen.

At the smallest breakpoint:
![image](https://github.com/user-attachments/assets/415f91a7-6dd5-462b-9eef-635447987f11)
- could you please add some padding between the "Go to seedlot" button and the field above it
- and align the left edge of the "Go to seedlot" button with the left edge of the "Register a new seedlot"

As I'm playing around with the responsiveness, is there a way to consistently make the right edge of the "Register a new seedlot" button align with the right edge of the "Go to seedlot" button
![image](https://github.com/user-attachments/assets/097d7492-a977-42cf-a143-bd60fa6d0bbd)

Thank you!

2024-10-01 18:47 UTC, RMCampos requested changes
Great job! Just a small suggestion for the regex and some styling issues :) 💯

2024-10-01 18:47 UTC, RMCampos commented on frontend/src/utils/NumberUtils.ts
> +export const isNumeric = (value: string) => /^-?\d+$/.test(value);
suggestion (non-blocking): how about having a simpler change and more readable? I'm thinking of something like this: `export const isNumeric = (value: string) => value.replace(/[0-9]/g, '').length === 0;`

2024-10-01 18:50 UTC, RMCampos commented
Styling issues

- My Seedlots

Can we improve this component on "My Seedlots" page? I can see it kind of sticking to the left menu, looking quite weird.
![image](https://github.com/user-attachments/assets/56cb08c4-a27d-4618-ae1b-bd385f49001a)

- Fix title and subtitle according to page

I'm at the Seedlots page, and I still can see the review title and subtitle:

![image](https://github.com/user-attachments/assets/dea2c10f-03ee-409e-b650-be5dc6094532)

That's all =D great job!

2024-10-02 22:12 UTC, kevinginley commented
The alignments are looking good, thank you!

Is there a way we could get consistent padding between the field and the "Go to seedlot button" between the different breakpoints?

Here we have quite a bit of space:
![image](https://github.com/user-attachments/assets/2e03dfe7-ffbf-4d70-9c8b-931a4060cdaa)

compared to:
![image](https://github.com/user-attachments/assets/09e7bb67-341c-45ab-9367-f4285327e8d3)

But if it's going to be super tricky then I wouldn't worry about it.

2024-10-03 14:03 UTC, RMCampos commented
@xiaopeng0202 nice. However I still can see "Review seedlot" at the Seedlots page.

2024-10-03 14:04 UTC, RMCampos requested changes
Need to fix the title.

2024-10-03 17:32 UTC, RMCampos approved these changes
All clear! Great job Xiao! 💯

2024-10-03 19:20 UTC, merged