feat: 1520 404 page not found screen development
bcgov/nr-spar pull request #1663
Opened 2024-10-08 22:09 UTC by ngunner15

# Description
Closes #1520 

### Changelog
#### New
- Route for 404
- Text for 404 page

#### Changed
- Route file

#### Removed
-

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExZHZsdjNqY3p4MXJod2ZhcnpodjNha3FnOWMyc3l5cXdkZ2plZTU2YSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/fUQ4rhUZJYiQsas6WD/giphy.webp" width="200"/>

2024-10-11 22:28 UTC, RMCampos approved these changes
Great job Nisarg! 💯 🥇 

LGTM!

2024-10-11 22:29 UTC, RMCampos commented
Working like a charm

2024-10-18 17:57 UTC, mgaseta requested changes
Looking good! Nice job!
Besides the markups, there are 2 issues:
1. On the design, the navigation header is still present on the 404 page ([here](https://www.figma.com/design/XpF15ggH9Gn7FeXa9zTNYm/SPAR---404-and-403-errors?node-id=4001-19343&node-type=frame&t=VyNolVOCxnnnMnsR-0))
2. The page is not being redirected to the 404, you can see that by looking at the URL, it doesn't change to `/404`, not exactly necessary, but it would be nice to change the URL to reflect the correct page.

2024-10-18 17:57 UTC, mgaseta commented on frontend/src/App.tsx
> +  // };
Remove this comment.

2024-10-18 17:57 UTC, mgaseta commented on frontend/src/App.tsx
> +    });
Why is this necessary? Shouldn't the `signedRoutes` const be enough to handle the 404 path? Also, you can use the ROUTES constant to get the `'*'` path.

2024-10-22 16:39 UTC, ngunner15 commented on frontend/src/App.tsx
> +    });
https://github.com/bcgov/nr-spar/pull/1663/commits/58b4202bcaa9010b696f0fdda1b12ecd2d68d268

2024-10-23 18:53 UTC, kevinginley commented
Looks good! Responsiveness working well. Thanks Nisarg

2024-10-24 14:15 UTC, mgaseta approved these changes
LGTM! Nice job @ngunner15!
<img width="150" src="https://media1.giphy.com/media/VwoJkTfZAUBSU/giphy.gif"/>

2024-10-24 17:06 UTC, merged