Feat/1694 lock ownership to read only
bcgov/nr-spar pull request #1712
Opened 2024-11-07 21:14 UTC by xiaopeng0202

This pull request introduces a new API endpoint to retrieve seedlot information by seedlot number and integrates this functionality into the frontend. The changes include updates to the API configuration, addition of a new endpoint in the backend, and modifications to the frontend components to utilize this new endpoint.

New
- lock ownership to read only when original qty is over 0
- added new endpoint on oracle db to expose original qty from seedlot table

### How was this tested?
- [ ] 🧠 Not needed
- [ ] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media3.giphy.com/media/CmQbcGL2arIyDMADXv/giphy.gif"/>

2024-11-07 22:32 UTC, DerekRoberts commented
@xiaopeng0202 Any sense writing a test to ensure write only?

2024-11-14 20:57 UTC, mgaseta requested changes
Nice job!
Added only a few markups, but nothing major.

2024-11-14 20:57 UTC, mgaseta commented on frontend/src/api-service/ApiConfig.ts
> +  seedlotBySeedlotNumber: `${oracleServerHost}/api/seedlot/{seedlotNumber}`
Maybe we should rename this to something like "getSeedlotFromOrableDb" or something like that, to better differentiate this path.

2024-11-14 20:57 UTC, mgaseta commented on frontend/src/api-service/seedlotAPI.ts
> +export const getSeedlotBySeedlotNumber = (seedlotNumber: string) => {
Same here, a different name to know this is coming from oracle.

2024-11-14 20:57 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/index.tsx
> +  const readOnly = originalSeedQty > 0;
I think this const can have a less generic name.

2024-11-14 20:57 UTC, mgaseta commented on oracle-api/config/application-local.yml
> +    password: default
Question: what is this? (And maybe remove one of the empty lines?)

2024-11-14 21:59 UTC, xiaopeng0202 commented on oracle-api/config/application-local.yml
> +    password: default
it's the config to running oracle db locally

2024-11-19 17:45 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx
> -      }
Shouldn't we keep this for historic seedlots that are CUS or UPT?

2024-11-19 17:53 UTC, xiaopeng0202 commented on frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx
>    });
sorry for that, it was a merge conflit, just made update

2024-11-19 17:53 UTC, xiaopeng0202 commented on frontend/src/views/Seedlot/SeedlotReview/SeedlotReviewContent.tsx
> -      }
https://github.com/bcgov/nr-spar/pull/1721

We have another PR to remove it

2024-11-19 17:56 UTC, mgaseta approved these changes
LGTM!

2024-11-19 18:01 UTC, merged