fix: 1704 Seedlots not updating BV values correctly
bcgov/nr-spar pull request #1716
Opened 2024-11-13 22:22 UTC by mgaseta

# Description
Closes #1704

These issues will be better tested on the test environment, due the statuses of the seedlots with issues.

### Changelog
#### New
- Nothing :)

#### Changed
- Changed a validation when populating the table
- Changed a validation when submitting the calculation data

#### Removed
- Nothing :)

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?
<img  width="300" src="https://media4.giphy.com/media/l1KVaj5UcbHwrBMqI/giphy.gif"/>

2024-11-13 23:11 UTC, SLDonnelly reviewed
The recalculation is working as expected in DEV, but I will need to test whether new BVs are being pulled in correctly in SPAR2 TEST

2024-11-19 18:16 UTC, xiaopeng0202 requested changes

2024-11-19 18:16 UTC, xiaopeng0202 commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
> +          ? Number(row.smpSuccessPerc.value)
if  row.smpSuccessPerc.value is 'null', Number(row.smpSuccessPerc.value) will be NaN, is that expected?

2024-11-19 18:35 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
> +          ? Number(row.smpSuccessPerc.value)
Fixed here: https://github.com/bcgov/nr-spar/pull/1716/commits/8b288bd746865cfde323b5020e8a23817e69fae5

2024-11-19 18:35 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
> +  debugger;
My bad... Fixed here: https://github.com/bcgov/nr-spar/pull/1716/commits/8b288bd746865cfde323b5020e8a23817e69fae5

2024-11-19 18:35 UTC, xiaopeng0202 approved these changes

2024-11-19 19:37 UTC, merged