feat: 1580 list favorite activities for consep
bcgov/nr-spar pull request #1771
Opened 2024-12-09 18:14 UTC by xiaopeng0202

# Description
Closes #1580

### Changelog
#### New
- Add a new page for consep favorite activities. The behavior will look like spar favorite activities.

### How was this tested?
- [ ] 🧠 Not needed
- [ ] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

---

Thanks for the PR!

Deployments, as required, will be available below:
- [Frontend](https://nr-spar-21-frontend.apps.silver.devops.gov.bc.ca/)
- [Backend](https://nr-spar-1771-backend.apps.silver.devops.gov.bc.ca/swagger-ui/index.html)
- [Oracle-API](https://nr-spar-1771-oracle-api.apps.silver.devops.gov.bc.ca/actuator/health)

Please create PRs in draft mode.  Mark as ready to enable:
- [Analysis Workflow](https://github.com/bcgov/nr-spar/actions/workflows/analysis.yml)

After merge, new images are deployed in:
- [Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge.yml)

2024-12-13 19:19 UTC, mgaseta requested changes
Nice job!
Added a few markups on the code.

Not sure if it's in the scope of this task, but there is no menu entry for this consep page... I had to access the new page via the URL.

2024-12-13 19:19 UTC, mgaseta commented on frontend/src/views/CONSEP/FavouriteActivity/index.tsx
I think the folder name should be all in lower case, to maintain the pattern we are using. And maybe a task for later, but now that we are starting CONSEP, we can try to re-arrange our project's folder organization.

2025-01-07 21:43 UTC, xiaopeng0202 commented
> Nice job! Added a few markups on the code.
> 
> Not sure if it's in the scope of this task, but there is no menu entry for this consep page... I had to access the new page via the URL.

We will miss the menu entry for now, only accessed by url

2025-01-07 22:19 UTC, xiaopeng0202 commented on frontend/src/components/FavouriteActivities/index.tsx
>                    />
it's in the other pr https://github.com/bcgov/nr-spar/pull/1794

2025-01-07 22:20 UTC, xiaopeng0202 commented on frontend/src/components/FavouriteActivities/index.tsx
> +                ) : favActQuery.data.filter((fav) => fav.isConsep === isConsep).map((favObject) => (
Adjusted the data model to inroduce isConsep. it wont impact spar

2025-01-07 22:20 UTC, xiaopeng0202 commented on frontend/src/components/PageTitle/index.tsx
> +    (act) => act.type === activity && act.isConsep === isConsep
as isConsep introduced, it's earsier to check so

2025-01-10 14:01 UTC, mgaseta reviewed
LGTM!
Only one topic I raised before was not addressed, I re-opened the conversation.

2025-01-14 12:43 UTC, mgaseta approved these changes

2025-01-14 17:11 UTC, merged