Feat/Parent tree step foundation
bcgov/nr-spar pull request #182
Opened 2023-06-02 02:46 UTC by craigyu

# Description
Fixes #166 

This PR provides the ground work implementation of the parent tree step of Registration Flow.
The parent tree step is NOT yet finished.

### Testing guide
- Create a seedlot that has genetic worth shown this this [table](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/tree-seed/seed-planning-use/spar#genetic_worth), I suggest using `FDC - Coastal Douglas-fir`
- Go to complete registration
- Go to Step 4 Orchard
- In the Orchard id field, type in `405` then wait for it to load
- Go to Step 5 Parent tree
- Table should be loaded (if the oracle-api is still working)
- Click on the eye icon to see special columns that you can toggle with in different tabs
- Table cell that has placeholder of `Add value` should accept user input and persist through tab changes
 
## Note:
This is not finished work so there might be some problems with some functionalities. I will be back to work on it.
The code in parent tree's `index.tsx` is quite spaghettish 🍝, the implementation will be improved and cleaned in the future. 
The registration flow test are failing because `ReferenceError: structuredClone is not defined` from Jest, I could not figure this out in time, assistance is needed or we skip these tests

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Manual as always

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

2023-06-08 21:46 UTC, mgaseta requested changes
Phew! It was quite a review hahaha. But really nice job, loved how it is implemented ❤. Added some markups, but nothing big.

2023-06-08 21:46 UTC, mgaseta commented on frontend/src/components/DescriptionBox/index.tsx
>      <div className="description-box-description">{description}</div>
Also, the type-style here is not looking right, if the `Subtitle` component doesn't work, use carbon's `@include type.type-style('body-01');` to make it look like the design.

2023-06-08 21:46 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +  const renderTabelCell = (rowData: RowItem, header: HeaderObj) => {
Typo here, should be `renderTableCell`.

2023-06-08 21:46 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                labelText={header.name}
This shouldn't be the `header.name`, I think a new field needs be added to the `HeaderObj` type, something like `displayText` or `displayValue` to keep the correct text to display on these options and on the headers of the table.

2023-06-08 21:46 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +            <TabList className="parent-tree-step-tab-list" aria-label="List of tabs">
Improve the `aria-label` here,maybe something that describes what this list of tabs do and their options?

2023-06-08 21:46 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                        </OverflowMenu>
I'm guessing this will change to the `Popover` component, right?

2023-06-08 21:46 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                          iconDescription="sss"
Change `iconDescription` here.

2023-06-08 21:46 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                          />
I'm assuming that theses options are yet to be implemented, I'm just adding this markup as a reminder :)

2023-06-08 21:46 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/styles.scss
> +}
Add a new empty line at the end of the file.

2023-06-08 21:46 UTC, mgaseta commented on frontend/src/theme/components-overrides.scss
> +// Why is this needed?
No idea and it doesn't make sense to be here, but just make sure that by removing it, nowhere else gets affected and if it is affected, open an issue so we can fix it later :)

2023-06-08 21:46 UTC, mgaseta commented on frontend/tsconfig.json
> +  "display": "Node 18",
I think this version bump should be made in a separate PR.

2023-06-09 11:53 UTC, RMCampos commented on frontend/tsconfig.json
> +  "display": "Node 18",
^ I second that.

2023-06-09 11:58 UTC, RMCampos commented on frontend/package.json
> +    "@types/node": "18.16",
Agreed!

2023-06-09 11:58 UTC, RMCampos commented on frontend/Dockerfile.dev
> +FROM node:18.16.0-alpine3.16
Agreed

2023-06-09 11:58 UTC, RMCampos commented on frontend/Dockerfile
> +FROM node:18.16.0-alpine3.16 AS build
Yep

2023-06-09 12:03 UTC, RMCampos commented
No deploy, since there's failing tests. As soon as they get fixed, just ask for a new review.

2023-06-09 12:46 UTC, RMCampos commented
@craigyu table working fine! Good job. Question: I wonder if we could finish editing a table cell when <enter> is pressed. Entes does nothing today. Tab works fine. May users are used to type and press enter to finish, or go to another cell. 

We may discuss this another time, or in another PR. 
cc: @mgaseta @SLDonnelly @mmarsoleta

2023-06-12 16:46 UTC, craigyu commented
closed to update PR

2023-06-12 17:06 UTC, craigyu commented on frontend/Dockerfile.dev
> +FROM node:18.16.0-alpine3.16
reverted

2023-06-12 17:06 UTC, craigyu commented on frontend/Dockerfile
> +FROM node:18.16.0-alpine3.16 AS build
reverted

2023-06-12 22:41 UTC, craigyu commented on frontend/src/components/DescriptionBox/index.tsx
>      <div className="description-box-description">{description}</div>
subtitle does not let me pass in React Node as props, so I made this

2023-06-13 00:13 UTC, craigyu commented on frontend/src/components/DescriptionBox/index.tsx
>      <h1 className="description-box-header">{header}</h1>
[fixed](https://github.com/bcgov/nr-spar/commit/dec64957215bb5c997a29253fcfad2d7eec0516a)

2023-06-13 00:20 UTC, craigyu commented on frontend/src/components/DescriptionBox/index.tsx
>      <h1 className="description-box-header">{header}</h1>
turns out it's h3 according to `figma`😅, [changed](https://github.com/bcgov/nr-spar/commit/7ea4a1bb359b036db0cc28b3d09821d2d6eb212f)

2023-06-13 00:21 UTC, craigyu commented on frontend/src/components/DescriptionBox/index.tsx
>      <div className="description-box-description">{description}</div>
[fixed](https://github.com/bcgov/nr-spar/commit/7ea4a1bb359b036db0cc28b3d09821d2d6eb212f)

2023-06-13 00:21 UTC, craigyu commented on frontend/tsconfig.json
> +  "display": "Node 18",
removed

2023-06-13 00:24 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                        </OverflowMenu>
no, the `Popover` component actually does not work well at all, I had some difficulties using it but i forgot what exactly happened after a week 😅

2023-06-13 00:26 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                        </OverflowMenu>
Oh check out. the commented out code at line 316, i left it there for you to see 😜

2023-06-13 00:31 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                labelText={header.name}
idk, it's we either use the header's column name `header.name`, or `header.description` which is too long. We don't have a design for all the checkboxes's name, so I'd say this is fine for now and we can bother the UI team later, what do you think

2023-06-13 00:38 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/styles.scss
> +}
[fixed](https://github.com/bcgov/nr-spar/commit/415eebbfc7045e845dc08f30a39286cfce66e366)

2023-06-13 00:38 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                          iconDescription="sss"
[fixed](https://github.com/bcgov/nr-spar/commit/415eebbfc7045e845dc08f30a39286cfce66e366)

2023-06-13 00:38 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                          />
[fixed](https://github.com/bcgov/nr-spar/commit/415eebbfc7045e845dc08f30a39286cfce66e366)

2023-06-13 00:39 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +  const renderTabelCell = (rowData: RowItem, header: HeaderObj) => {
[fixed](https://github.com/bcgov/nr-spar/commit/f94f45a68189df24d2ad7f72af22234d01617c78)

2023-06-13 13:07 UTC, mgaseta approved these changes
LGTM! Nice job 🚀🎉!

2023-06-13 13:10 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +            <TabList className="parent-tree-step-tab-list" aria-label="List of tabs">
I guess it's okay for now, we can come back to check a11y later.

2023-06-13 21:36 UTC, merged