Fix/175 frontend grid refactoring
bcgov/nr-spar pull request #197
Opened 2023-06-08 19:53 UTC by mgaseta

# Description

Fixed grid for all existing pages on SPAR.

Added some negative margins, which can be considered a bad practice, but since it is used only to bring elements closer together, I figured it is okay. Please shout out if you disagree and we can discuss other implementations. This practice is being used by Carbon too.

Fixes [#175](https://github.com/bcgov/nr-spar/issues/175)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manually tested and ran unit tests.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

2023-06-09 14:05 UTC, RMCampos requested changes
Great job! 💯 😄 only a question.

2023-06-09 14:05 UTC, RMCampos commented on frontend/src/views/Seedlot/CreateAClass/styles.scss
> +@use '../../../theme/variables.scss' as vars;
Do we need this import here?

2023-06-12 12:31 UTC, mgaseta commented on frontend/src/views/Seedlot/CreateAClass/styles.scss
> +@use '../../../theme/variables.scss' as vars;
No, we don't, forgot to remove it. Fixed [here](https://github.com/bcgov/nr-spar/pull/197/commits/ff7f2a5f53a98c95a5ba7868bdbe6aa0afa7f7a2)

2023-06-13 13:34 UTC, RMCampos approved these changes
LGTM. Great job!

2023-06-13 22:26 UTC, merged