Feat/my seedlots refactoring
bcgov/nr-spar pull request #207
Opened 2023-06-12 16:16 UTC by ArthurEncr

# Description

These changes in My Seedlot screen will be implemented in this issue:

Subtitle wrong should be "Check and manage your own seedlots"
Column wrong should be "Seedlot class", "Seedlot species" and "Last updated"
Hover doesn't change to clickable object on My seedlots table
Icons go/back next page on My seedlots page/table are misaligned
Background color on "table title" is wrong on My seedlots page
Line color above "table title" is wrong
Use constants.ts

Fixes # [FSADT2-616](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-616)
 [Github issue](https://github.com/bcgov/nr-spar/issues/206)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-spar-180-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-180-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-180-oracle-api.apps.silver.devops.gov.bc.ca/)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

2023-06-12 23:50 UTC, craigyu commented on frontend/src/views/Seedlot/MySeedlots/index.tsx
> +        setSeedlotsData(response.data.seedlotData.reverse());
why is `reverse()` used here? just curious what the desired behaviour is, the latest seedlot on top?

2023-06-13 12:38 UTC, ArthurEncr commented on frontend/src/views/Seedlot/MySeedlots/index.tsx
> +        setSeedlotsData(response.data.seedlotData.reverse());
yes, we can't sort by the most recent ones, in a good way, because we don't have the complete timestamp in the data, just the day and month... so talking to matheus, we decided to just invert the list, which is already sorted less recent to most recent, to have the same effect.

2023-06-13 13:30 UTC, RMCampos requested changes
Great job! ✅ I wonder if we can improve that `reverse` data, though.

2023-06-13 13:30 UTC, RMCampos commented on frontend/src/views/Seedlot/MySeedlots/index.tsx
> +        setSeedlotsData(response.data.seedlotData.reverse());
Do we have an ID or something? Could we use something more tangible for sorting? Trusting the response is not a good idea IMO.

2023-06-13 22:31 UTC, craigyu approved these changes

2023-06-13 22:41 UTC, craigyu requested changes
Always run local tests before opening a PR😃, please fix the the lower-case letter
![image](https://github.com/bcgov/nr-spar/assets/25162561/4ed88f30-12fe-418a-b142-e70caa4322dc)

2023-06-14 14:49 UTC, RMCampos approved these changes
LGTM! 💯

2023-06-15 00:03 UTC, craigyu approved these changes
🐞🔫

2023-06-15 00:18 UTC, merged