Fix/213 ownership fixes
bcgov/nr-spar pull request #248
Opened 2023-06-15 20:09 UTC by ArthurEncr

# Description

changes at ownership form step:
- Space after "collapse icon" should be 32px
- Arrow centered
- Applicant agency isn't "imported" (I made this fix for the other steps too)

Fixes #[213](https://github.com/bcgov/nr-spar/issues/213)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2023-06-15 20:54 UTC, DerekRoberts approved these changes

2023-06-16 11:42 UTC, mgaseta requested changes
Nice job! Added only a few small changes.

2023-06-16 11:42 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/styles.scss
> +button.bcgov--accordion__heading{
Use the `#{vars.$bcgov-prefix}` here instead of `bcgov` directly and adjust indentation.

2023-06-16 11:42 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/styles.scss
> +svg.bcgov--accordion__arrow{
Use the `#{vars.$bcgov-prefix}` instead of `bcgov` directly.

2023-06-16 11:42 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/styles.scss
> +
Leave only one empty line here.

2023-06-16 11:42 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx
> +      seedlotInfoQuery.data.seedlotApplicantInfo.applicant.number
Maybe adding these values to variables with smaller names? Just to look fancier 🧐🍸

2023-06-20 16:13 UTC, RMCampos approved these changes
LGTM 💯 ✅

2023-06-20 16:34 UTC, mgaseta requested changes
LGTM 🚀❤! Just need to fix the unit tests.

2023-06-20 19:00 UTC, craigyu approved these changes
**Decision :**
The unit tests for registration completion steps are proven to be more of a hurdle for developers. We decided to skip these tests for now as more changes are coming for these pages.

2023-06-21 13:06 UTC, mgaseta approved these changes
LGTM!

2023-06-21 18:13 UTC, merged