184 corrections for apiorchardsparent tree genetic qualityorchardidspuid
bcgov/nr-spar pull request #249
Opened 2023-06-16 18:56 UTC by RMCampos

# Description

Brings `Parent tree and Genetic Quality` data from `oracle-api` to `backend` through REST request, in order of validating the right SPU id number to an Orchard.

Fixes #184 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This change was tested locally and with lots of unit tests.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-spar-249-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-249-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-249-oracle-api.apps.silver.devops.gov.bc.ca/)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

2023-06-16 20:16 UTC, paulushcgcj commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/OrchardParentTreeDto.java
> +public class OrchardParentTreeDto {
This DTO can be a record

2023-06-16 20:17 UTC, paulushcgcj commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/ParentTreeDto.java
> +public class ParentTreeDto {
This DTO can be a record

2023-06-16 20:17 UTC, paulushcgcj commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/ParentTreeGeneticQualityDto.java
> +public class ParentTreeGeneticQualityDto {
This DTO can be a record

2023-06-16 20:22 UTC, paulushcgcj commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpoint.java
> +    Optional<OrchardParentTreeDto> parentTreeDto =
If the described behaviour is the default, It would be better to hide this `orElseThrow` within the service itself and throw a custom `ResponseStatusException`  from within it.

If other places will also consume this `findParentTreeGeneticQualityData` and they expect the optional, keep it as is, otherwise, I would recommend encapsulating this error into the service.

2023-06-16 20:22 UTC, paulushcgcj commented on backend/src/main/resources/application.properties
> +oracle-api.base-url = https://nr-spar-test-oracle-api.apps.silver.devops.gov.bc.ca
Don't forget to replace this with some variables to be able to replace it in the future

2023-06-16 20:23 UTC, paulushcgcj commented on backend/src/test/java/ca/bc/gov/backendstartapi/security/UserInfoTest.java
> +            new HashSet<>(),
Can be replaced with Java 17 initializers such as `List.of()` or `Set.of()`

2023-06-16 20:24 UTC, paulushcgcj commented on backend/src/test/java/ca/bc/gov/backendstartapi/security/UserServiceTest.java
> +            new HashSet<>(),
Can be replaced with Java 17 initializers such as `List.of()` or `Set.of()`

2023-06-16 20:25 UTC, paulushcgcj requested changes
I would suggest some changes, but overall good code.

2023-06-16 21:33 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/OrchardParentTreeDto.java
> +public class OrchardParentTreeDto {
👍🏻 [Done!](https://github.com/bcgov/nr-spar/pull/249/commits/6acdddd52e06cd638315dc076c4f027159106c9a)

2023-06-16 21:34 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/ParentTreeDto.java
> +public class ParentTreeDto {
👍🏻 [Done!](https://github.com/bcgov/nr-spar/pull/249/commits/5d43bbedb452ff73f8f822d4eb110c9a1cfe56e2)

2023-06-19 17:29 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/ParentTreeGeneticQualityDto.java
> +public class ParentTreeGeneticQualityDto {
👍🏻 [Done!](https://github.com/bcgov/nr-spar/pull/249/commits/60515a12b3f9a262a1af9b105f226cefa3cb510d)

2023-06-19 18:27 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpoint.java
> +    Optional<OrchardParentTreeDto> parentTreeDto =
Good catch! Also this way we're not keeping the code consistent!

2023-06-19 21:16 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpoint.java
> +    Optional<OrchardParentTreeDto> parentTreeDto =
👍🏻 [Done!](https://github.com/bcgov/nr-spar/pull/249/commits/7c4b956e8cc7cff1a867256557a6cd885da58dfe)

2023-06-19 21:16 UTC, RMCampos commented on backend/src/main/resources/application.properties
> +oracle-api.base-url = https://nr-spar-test-oracle-api.apps.silver.devops.gov.bc.ca
👍🏻 [Done!](https://github.com/bcgov/nr-spar/pull/249/commits/40086348a8391114fdfe49b2955d249cb488459f)

2023-06-19 21:17 UTC, RMCampos commented on backend/src/test/java/ca/bc/gov/backendstartapi/security/UserInfoTest.java
> +            new HashSet<>(),
👍🏻 [Done!](https://github.com/bcgov/nr-spar/pull/249/commits/0f98e82255043a0613d0a63f73a7eac4d67796c4)

2023-06-19 21:17 UTC, RMCampos commented on backend/src/test/java/ca/bc/gov/backendstartapi/security/UserServiceTest.java
> +            new HashSet<>(),
And 👍🏻 [Done!](https://github.com/bcgov/nr-spar/pull/249/commits/0f98e82255043a0613d0a63f73a7eac4d67796c4)

2023-06-20 01:01 UTC, paulushcgcj approved these changes
Looking good 👍

2023-06-21 21:24 UTC, craigyu approved these changes
awesome update, I will make the related update to my current parent tree task

2023-06-21 21:26 UTC, craigyu requested changes
![image](https://github.com/bcgov/nr-spar/assets/25162561/070d1fdd-6c1e-43ea-a692-37948d02d9d9)

Should we add this var to docker-compose.yml?

2023-06-21 21:31 UTC, RMCampos commented
> ![image](https://user-images.githubusercontent.com/25162561/247766592-070d1fdd-6c1e-43ea-a692-37948d02d9d9.png)
> 
> Should we add this var to docker-compose.yml?

Thanks @craigyu 
Well done! [Here!](https://github.com/bcgov/nr-spar/pull/249/commits/dfc30b4dd5e8f47707223263913d277f23f3487c)

2023-06-21 21:49 UTC, craigyu approved these changes

2023-06-21 21:49 UTC, merged