Feat/235 integrate conecollection endpoint
bcgov/nr-spar pull request #261
Opened 2023-06-20 13:48 UTC by mgaseta

# Description

Integrated the cone collection methods endpoint to the Collection step. 
Two important notes:
- The "Other" field functionality is yet to be decided if it is going to be implemented now or later, I left the code related to it commented for now. Also note that some changes are necessary on the API, either removing the "Unknown" option or changing it for the "Other" option.
- I decided to keep the API calls on the `SeedlotRegistrationForm` view, it may take a bit more time for the first load but there will be no loading time between steps, shout out if you disagree and we can discuss solutions :)

Fixes #235 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manual tests and unit tests.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

2023-06-20 17:28 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/definitions.ts
> +  [method: string]: boolean | string,
Can we improve on this type definition? 
what about:
`collectionMethod: MultiOptionsObj`
instead of:
`[method: string]: boolean | string`

2023-06-20 19:34 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/definitions.ts
> +  [method: string]: boolean | string,
Hmmm, I don't think we can (at least using the `MultiOptionsObj`), each collection method needs its own boolean field, so we can map them individually.

2023-06-21 23:21 UTC, craigyu requested changes
<img width="439" alt="image" src="https://github.com/bcgov/nr-spar/assets/25162561/80ecb297-7717-44b2-9b2c-98c362142563">

The `state` data looks false here, we have `squirrel05` set as `true` while `squirrelCache` is still false, maybe it's saving the id name instead.
I propose the following changes:
1. Add a new field `selectedCollectionCodes: string[]` in `CollectionForm`. This new field will save the checked method codes.
2. When a method is checked, add the code to this array
3. When a method is unchecked, remove the code from this array
4. Associate the `checked` prop with `state.selectedCollectionCodes.includes(method.code)`

2023-06-21 23:29 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/definitions.ts
> +  [method: string]: boolean | string,
> Ok perhaps we don't need to store all the options here, we just need to update the `collectionMethodName`'s value, let's change that to `collectionMehtodCode`

ignore this comment, please see the request changes comment below :)

2023-06-22 21:00 UTC, craigyu requested changes

2023-06-23 21:14 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/definitions.ts
>    collectionMethodName: string,
[fixed](https://github.com/bcgov/nr-spar/pull/261/commits/3bf3281be3ed311175cd5af2987e0775a9fe3999)

2023-06-26 17:25 UTC, merged