Feat/168 methodology integration
bcgov/nr-spar pull request #270
Opened 2023-06-23 14:24 UTC by ArthurEncr

# Description

Fetch MaleFemaleMethodology data from backend service then map options on the orchard Step

-  MaleFemaleMethodology data fetching
-  Male methodology data dynamically displayed
-  Female methodology data dynamically displayed
-  Special cases are accounted for: e.g. logepole pine having different options

Fixes # [168](https://github.com/bcgov/nr-spar/issues/168)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

manually tested

2023-06-23 17:23 UTC, craigyu commented
This will be reviewed after #261 is merged into `main`, #261 contains refactor of the `DropDownObj` and its util functions which will cause conflicts

2023-06-26 17:26 UTC, craigyu commented
@ArthurEncr it's conflict resolution time 🥳

2023-06-27 13:25 UTC, ArthurEncr commented
No more conflicts, it can now be revised :)

2023-06-27 16:45 UTC, mgaseta reviewed
LGTM! :rocket: :100:

2023-06-27 16:45 UTC, mgaseta approved these changes

2023-06-27 17:47 UTC, mgaseta requested changes
Forgot these two markups, sorry.

2023-06-27 17:47 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +                    ))}
Forgot about this, but there is a missing `key` prop within this map.

2023-06-27 17:47 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +                      />
Also here.

2023-06-27 18:27 UTC, mgaseta reviewed
LGTM! :100: :1st_place_medal:

2023-06-27 18:27 UTC, mgaseta approved these changes

2023-06-29 17:30 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +                    {maleGameticOptions.slice(0, -2).map((item) => (
How can we know for sure that the sliced objects are the correct ones>

2023-06-29 18:54 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +                    {maleGameticOptions.slice(0, -2).map((item) => (
there will be a backend task to handle this

2023-06-29 18:55 UTC, craigyu approved these changes
femaleGametic is stored as an object(multiOptionObj) while maleGametic is stored as a string(code), it would be nice if they are both storing the code for consistency but this is ok for now

2023-06-29 18:56 UTC, merged