Feat/217 parent tree step implementation
bcgov/nr-spar pull request #278
Opened 2023-06-28 17:14 UTC by craigyu

# Description
Implements #217 

### Summary of changes:
- add pagination function
- press `Enter` on a table cell input will un-focus(blur) from it
- add `InfoSection` component
    - ![image](https://github.com/bcgov/nr-spar/assets/25162561/80b42c92-85ee-4b7d-b5b5-5283b1098c57)
    - the example shows 2 InfoSections here
- add styling and functionalities to these buttons 👇
    - ![image](https://github.com/bcgov/nr-spar/assets/25162561/8ce8585b-7b8c-47c2-ac9d-e6081c781d47)
- add clean table functionality
- template files are downloadable 
- upload file will clean the table then replace/fill values
    - incorrect parent tree numbers in the csv will be shown in an `alert()` dialog, this is temporary until we get a design
- implements `EmptySection` when users have not yet selected an orchard(s)
 
 

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Local manual test

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2023-06-28 18:08 UTC, craigyu commented
Test file [405_valid.csv](https://github.com/bcgov/nr-spar/files/11898812/405_valid.csv)

2023-06-28 21:11 UTC, mgaseta requested changes
Nice job :1st_place_medal: :rocket: ! It may look like a lot of markups, but there were a lot of changes hahaha.

2023-06-28 21:11 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                            onClick={() => setIsCleanWarnOpen(true)}
The clean data table pop up is appearing even when the table is empty, which is not great, maybe add this option only when changes to the table were made?

2023-06-28 21:11 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +        // onSubmit={(file: File) => uploadFile(file)}
Remove this line.

2023-06-28 21:11 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +    sliceTableRowData(Object.values(state.tableRowData), page, pageSize, true);
Maybe we can add this pagination handler to an utils file, so we can use it on other pages when necessary. What do you think?

2023-06-28 21:14 UTC, mgaseta commented on frontend/public/downloads/Seedlot_composition_template.csv
> +Parent Tree number,Cone count,Pollen count,SMP success,Pollen contamination
Sorry, I added this before @craigyu pointed to the figma comment that changed it.

2023-06-28 22:26 UTC, craigyu commented on frontend/src/api-service/ApiConfig.ts
> +  uploadConeAndPollen: `${serverHost}/api/seedlots/{seedlotNumber}/parent-trees-contribution/cone-pollen-count-table/upload`,
created issue #280

2023-06-28 22:32 UTC, craigyu commented on frontend/src/components/InfoSection/index.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */
[fixed](https://github.com/bcgov/nr-spar/pull/278/commits/60f255fa470eb54747999abf692d55b07c8f39de)

2023-06-28 22:32 UTC, craigyu commented on frontend/src/api-service/ApiConfig.ts
> +  uploadSMPMix: `${serverHost}/api/seedlots/{seedlotNumber}/parent-trees-contribution/smp-calculation-table/upload`,
[fixed](https://github.com/bcgov/nr-spar/pull/278/commits/60f255fa470eb54747999abf692d55b07c8f39de)

2023-06-28 22:32 UTC, craigyu commented on frontend/src/components/InfoSection/index.tsx
> +        <Column>
I think a `Column` without breakpoints is default to take the entire row, so this should be ok?

2023-06-28 22:34 UTC, craigyu commented on frontend/src/components/InfoSection/index.tsx
> +        <Column>
![image](https://github.com/bcgov/nr-spar/assets/25162561/c39d33ee-9310-4b6b-a793-eea3041ebdb5)

We have 1 column inside 1 row here so it should be `100%`

2023-06-28 22:39 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/SingleOwnerInfo/index.tsx
> +                  (_event: React.ChangeEvent<HTMLInputElement>, { checked }: CheckboxType) => {
I moved the `CheckBoxValue` to the  more general `/types` folder and renamed it to `CheckboxType`, so it can be used it everywhere, let's just change it here instead of doing another PR just to get rid of `CheckBoxValue`

2023-06-28 22:46 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/index.tsx
> +            onClick={(e: React.ChangeEvent<any>) => toggleColumn(header.id, e.target.nodeName)}
[fixed](https://github.com/bcgov/nr-spar/pull/278/commits/6d7e1df9c830b88ab6a486d5e77b476d63229dd1)

2023-06-28 22:47 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/index.tsx
> +                onKeyDown={(event: React.KeyboardEvent<HTMLElement>) => {
great suggestion [fixed](https://github.com/bcgov/nr-spar/pull/278/commits/6d7e1df9c830b88ab6a486d5e77b476d63229dd1)

2023-06-28 23:02 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/index.tsx
> +                  headerConfig.map((header) => (
Didn't want to chain calls but it makes more sense to filter it first

fixed [here](https://github.com/bcgov/nr-spar/pull/278/commits/67d1c1f409752ec5daf158d1e0ad9d73b7608865) and [here](https://github.com/bcgov/nr-spar/pull/278/commits/43d090d28a73ed72a58074b6565b6f2dd739bfa9)

2023-06-28 23:12 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/UploadFileModal/index.tsx
> +          setFileUploadConfig(newFileUploadConfig);
I'm just modifying your file man 👀 
[updated](https://github.com/bcgov/nr-spar/pull/278/commits/ddaef678a75b41f87a74100edf696bb5afd7e613)

2023-06-28 23:13 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +        // onSubmit={(file: File) => uploadFile(file)}
👀 I'm just modifying your implementation
[updated](https://github.com/bcgov/nr-spar/pull/278/commits/ddaef678a75b41f87a74100edf696bb5afd7e613)

2023-06-28 23:17 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/constants.tsx
> +    downloadName = tabType;
![Screenshot 2023-06-28 at 4 15 30 PM](https://github.com/bcgov/nr-spar/assets/25162561/23303c73-9713-484e-947b-a2707da9b796)

@mmarsoleta @mariafernanda31 what do you two think? Capped vs uncapped 🤜💥🤛

2023-06-28 23:20 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
>                            }
Yes that's why I said in the roadmap meeting that we should filter the veg codes, but Sabina said it's not a priority, I think it's a simple change that leads to a big improvement

2023-06-28 23:22 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                            onClick={() => setIsCleanWarnOpen(true)}
Meh, it's fine, they can clean it again, no harm done, it's hard to keep track if a table is tainted (modified) or not, plus there's no business rule for it 🤪

2023-06-28 23:26 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                            onClick={() => setIsCleanWarnOpen(true)}
@mmarsoleta @mariafernanda31 any thoughts?

2023-06-28 23:29 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +        // onSubmit={(file: File) => uploadFile(file)}
[fixed](https://github.com/bcgov/nr-spar/pull/278/commits/85443cce419f636eedc66a22a0db31f8bee4dee3)

2023-06-28 23:30 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +    // Ctore parent tree numbers that does not exist in the orchards
[fixed](https://github.com/bcgov/nr-spar/pull/278/commits/85443cce419f636eedc66a22a0db31f8bee4dee3)

2023-06-28 23:30 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
>                            iconDescription="more options"
[fixed](https://github.com/bcgov/nr-spar/pull/278/commits/85443cce419f636eedc66a22a0db31f8bee4dee3)

2023-06-28 23:32 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +   * Each seedlot speicies has its own associated Genetic Worth values that users can toggle,
[fixed](https://github.com/bcgov/nr-spar/pull/278/commits/6dc353b9873df6306cb0e3b2df20b43a140ea989)

2023-06-28 23:40 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +
idk man, I tried my best re-ordering [here](https://github.com/bcgov/nr-spar/pull/278/commits/9c081a0b42cd9d3096c65baa50b8ca8becc4a5af) like suggested, it still looks messy af

2023-06-28 23:51 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/index.tsx
> +      />
[fixed here](https://github.com/bcgov/nr-spar/pull/278/commits/693616b1646d5cd9aed687d00cb98491f8f88d92)

2023-06-29 00:25 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +    sliceTableRowData(Object.values(state.tableRowData), page, pageSize, true);
[OOF](https://github.com/bcgov/nr-spar/pull/278/commits/4511def819f70c4d4e4b8b08ea522bca73b66ce0), this took a bit of work but it was worth it

2023-06-29 01:05 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/index.tsx
> +              <TextInput
good eye, [fixed](https://github.com/bcgov/nr-spar/pull/278/commits/a2060e829d4afb1fa9616542a7cd9bf4f41eb233)

2023-06-29 13:16 UTC, mgaseta commented on frontend/src/components/InfoSection/index.tsx
> +        <Column>
My bad, I thought the other column was in the same row.

2023-06-29 13:18 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/OwnershipStep/SingleOwnerInfo/index.tsx
> +                  (_event: React.ChangeEvent<HTMLInputElement>, { checked }: CheckboxType) => {
Okay, sounds good for me!

2023-06-29 13:21 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/index.tsx
> +                  headerConfig.map((header) => (
Nice touch removing the `currentTab` parameter.

2023-06-29 13:22 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/UploadFileModal/index.tsx
> +          setFileUploadConfig(newFileUploadConfig);
Yep, I know, but still looks better :laughing:

2023-06-29 13:26 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +
Yeah there are to many imports, but already looks better.

2023-06-29 13:29 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/TableComponents/index.tsx
> +      />
Fixed and reorganized some style rules, very nice!

2023-06-29 13:32 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
>                            }
Yeah, maybe we can leave as is and make the improvement in the future? What is your opinion @SLDonnelly ?

2023-06-29 18:50 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
>                            }
@SLDonnelly I made a simple filtering function [here](https://github.com/bcgov/nr-spar/pull/278/commits/6f5750a744158a55f5b5927edf40709918650ac9) on the front end, it took me less than 10 min I swear 😜

2023-06-29 18:50 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/constants.tsx
> +    downloadName = tabType;
[fixed here](https://github.com/bcgov/nr-spar/pull/278/commits/6f5750a744158a55f5b5927edf40709918650ac9)

2023-06-29 18:50 UTC, craigyu commented
@mgaseta should be ready to go

2023-06-29 19:08 UTC, SLDonnelly commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
>                            }
@craigyu woot woot awesome :)

2023-06-29 19:14 UTC, mgaseta approved these changes
Real nice job, congrats! :100: :1st_place_medal: :confetti_ball:

2023-06-29 19:29 UTC, merged