fix: disable box shadow when scrollbar appears
bcgov/nr-spar pull request #291
Opened 2023-07-03 13:54 UTC by ArthurEncr

# Description

fixing the bug that when the page height is decreased and the scrollbar appears, the borders of the panel section name keep showing.

Fixes #[198](https://github.com/bcgov/nr-spar/issues/198)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manualy tested.

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

2023-07-04 16:52 UTC, mgaseta requested changes
Nice job! :rocket: Added only 2 small markups.

2023-07-04 16:52 UTC, mgaseta commented on frontend/src/components/PanelSectionName/styles.scss
> +}
Adjust indentation here.

2023-07-04 16:52 UTC, mgaseta commented on frontend/src/components/PanelSectionName/styles.scss
> +@media only screen and (max-height: 877px) {
Add this `max-height` value to a var on `variables.scss` file, something like left-menu-height and use it in this case.

2023-07-04 22:41 UTC, craigyu commented on frontend/src/components/PanelSectionName/styles.scss
> +@media only screen and (max-height: 877px) {
@mgaseta are you referring to `frontend/src/theme/variables.scss`? we will be using this [nr-theme package](https://github.com/bcgov/nr-fsa-theme/tree/main) so we should not make edit to this file

2023-07-04 22:42 UTC, craigyu commented on frontend/src/components/PanelSectionName/styles.scss
> +}
missing empty line

2023-07-05 00:03 UTC, craigyu commented
@mgaseta @ArthurEncr 
The root cause of the missing border issue is caused by the `component-override.scss` file, because it's using `box-shadow` for some reason, changing it to `border-right` seem to have fixed the problem. 

Sorry to hijack your PR Arthur, I made a new commit [here](https://github.com/bcgov/nr-spar/pull/291/commits/a72c1c80234673f403028d8ca69fffab3cb063f0).

### Additional changes:
- replaced hard-coded css prefix
- replaced text styling by taking advantage of `@use '@carbon/type';`

2023-07-05 00:03 UTC, craigyu approved these changes

2023-07-05 13:21 UTC, mgaseta commented on frontend/src/components/PanelSectionName/styles.scss
> +@media only screen and (max-height: 877px) {
Forgot about that :sweat_smile: , I'll close this markup.

2023-07-05 13:29 UTC, mgaseta requested changes
Nice changes! Added only one small markup.

2023-07-05 13:29 UTC, mgaseta commented on frontend/src/theme/components-overrides.scss
>    background-color: var(--bcgov-background-left-panel);
Use the bcgov prefix variable here.

2023-07-05 16:51 UTC, craigyu commented on frontend/src/theme/components-overrides.scss
>    background-color: var(--bcgov-background-left-panel);
we actually found many hardcoded prefix like this one yesterday during an nr-theme meeting. I will be creating an issue to tackle all of them so we can start using the nr-theme package

2023-07-05 16:51 UTC, craigyu commented on frontend/src/theme/components-overrides.scss
>    background-color: var(--bcgov-background-left-panel);
actually I'll just fix it here

2023-07-05 18:19 UTC, craigyu commented on frontend/src/theme/components-overrides.scss
>    background-color: var(--bcgov-background-left-panel);
[fixed](https://github.com/bcgov/nr-spar/pull/291/commits/dcd20052f5634728bd69f9310b08701d675bbab4)

2023-07-05 22:44 UTC, merged