feat: refactor external api providers and code warnings
bcgov/nr-spar pull request #317
Opened 2023-07-10 21:47 UTC by RMCampos

# Description

- Remove all unnecessary `@Autowired`;
- Create a single `Provider` class to put all retrieving code in there and extend new providers from it;
- Create a ProviderConfig to put all api and related configurations in one place;

Fixes #316 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

These changes were tested locally with Swagger, Unit testing and Integration tests.

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2023-07-10 22:04 UTC, paulushcgcj requested changes

2023-07-10 22:04 UTC, paulushcgcj commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/ForestClientService.java
> +  private ForestClientApiProvider provider;
You can use SOLID principles and depend on the generic, and use `@Qualifier` to serve the correct one here

2023-07-12 18:38 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/provider/Provider.java
> +    logParams(uriVars);
Sorry. This what? I don't follow. @paulushcgcj

2023-07-12 21:22 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/provider/Provider.java
> +    logParams(uriVars);
I ended up changind all of this code. Now there's an Interface responsible for managing the providers.

2023-07-12 21:22 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/ForestClientService.java
> +  private ForestClientApiProvider provider;
Yup. [👍🏻 Done here](https://github.com/bcgov/nr-spar/pull/317/commits/c27d7486f76fe34426d5968fe2f229e1c75641d1)

2023-07-13 13:26 UTC, RMCampos commented
I tested all related endpoints, everything is working!

- ForestClient API
- Oracle API
- Others endpoints

2023-07-13 17:26 UTC, craigyu approved these changes
💯 Great changes, reviewed together in a meeting

2023-07-13 17:50 UTC, merged