Fix/205 recent activities refactor
bcgov/nr-spar pull request #322
Opened 2023-07-12 16:38 UTC by mgaseta

# Description

Fixed all small issues and refactored the component.

- [x] Change mouse icon to clickable when hover "view icon" on "My recent activities - request"
- [x] Update date format on "My recent activities - recents." table
- [x] Centralize icon on View column "My recent activities - recents."
- [x] Missing icon on Activity type "My recent activities - requests"
- [x] Update tip message to view icon on "My recent activities - recents.", validate the correct message, because on mock and hand-off notes the message is different
- [x] Scroll doesn't works to side on "My recent activities - recents." when screen is medium size
- [ ] Update tag name on column status on "My recent activities - recents.", validate the correct name, because on mock and hand-off notes the names are different
- This last one was not corrected, the status component will receive some new values that the UX team will define. So, to not extend this task longer, this will be made in a separate one.
- The changes on the activity and files types are not permanent, we still need to discuss how those features will work with the backend.
- Some changes may seem off with the design, but those were agreed with the UX team, there are comments on the figma file explaining them.

Fixes #205 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Manual tests and unit tests.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

2023-07-13 23:02 UTC, craigyu requested changes
👨🏻‍🔧 Great refactoring work here, I left a couple comments

2023-07-13 23:02 UTC, craigyu commented on frontend/src/components/RecentActivities/RecentActivitiesTable/index.tsx
> +                  docTable
Use boolean [naming convention](https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig) on this variable.
`hasDocTable`?

2023-07-14 19:49 UTC, mgaseta commented on frontend/src/components/RecentActivities/RecentActivitiesTable/index.tsx
> +                  docTable
Decided to go with `isDocTable`, sounds more right, fix is [here](https://github.com/bcgov/nr-spar/pull/322/commits/5905ca83715ef2a5c29850f0f71a412368618dff)

2023-07-14 19:50 UTC, mgaseta commented on frontend/src/components/RecentActivities/RecentActivitiesTable/index.tsx
> +              data-testid={`header-${header}-${idx}`}
Fixed [here](https://github.com/bcgov/nr-spar/pull/322/commits/c5d866cd146ee87a3635937e816ba57d60f48c6a)

2023-07-17 17:00 UTC, RMCampos approved these changes
LGTM

2023-07-17 17:02 UTC, RMCampos commented
@mgaseta @craigyu SonarCloud is failing due to low code coverage tests. Just highlighting. Besides that, it's all good. Great job 💯

2023-07-17 17:50 UTC, craigyu commented
> @mgaseta @craigyu SonarCloud is failing due to low code coverage tests. Just highlighting. Besides that, it's all good. Great job 💯

We can't disable the 80% requirement so I'll have to manually override it until we use cypress for coverage

2023-07-17 17:52 UTC, craigyu approved these changes
Great work! especially on taking the initiative to refactor the two tables 👊

2023-07-18 18:47 UTC, merged