fix: adjusting 'isPLI' flag name
bcgov/nr-spar pull request #330
Opened 2023-07-13 18:54 UTC by mgaseta

# Description

Adjusted the flag name on the frontend and swagger documentation. 

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Tested manually.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

2023-07-13 20:06 UTC, RMCampos requested changes

2023-07-13 20:23 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +  const [isPliSpecies] = useState<boolean>(seedlotSpecies.code === 'PLI');
The species code is in full caps, no need to change here.

2023-07-13 22:03 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +  const [isPliSpecies] = useState<boolean>(seedlotSpecies.code === 'PLI');
Might be a good idea to keep everything consistent by using `isPliSpecies`

2023-07-14 13:31 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +  const [isPliSpecies] = useState<boolean>(seedlotSpecies.code === 'PLI');
@craigyu you mean rename the flag everywhere to `isPliSpecies`?

2023-07-17 17:04 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +  const [isPliSpecies] = useState<boolean>(seedlotSpecies.code === 'PLI');
I meant the front-end but this is even better!

2023-07-17 17:11 UTC, RMCampos approved these changes
LGTM 🥳

2023-07-17 17:34 UTC, merged