Feat/315 fetch orchards by vegcode endpoint
bcgov/nr-spar pull request #333
Opened 2023-07-13 21:14 UTC by craigyu

# Description
Fixes #315 

This implementation of `/api/orchards/vegetation-code/{vegCode}` affects both `./backend` and `./oracle-api`
An endpoint has been created in both services

User should be able to fetch all the non-`"RET"` orchards with a given vegCode.

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
by adding tests to both backend and oracle-api

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

2023-07-17 18:10 UTC, RMCampos requested changes
Wonderful job! Small fixes only. 🥇

2023-07-17 18:10 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/service/OrchardService.java
> +          if (orchardLotTypeCode.isValid()) {
Optional improvement: this filter could be done before: `orchardList = orchardList.stream().filter(o -> o.getOrchardLotTypeCode().isValid()).toList();`

2023-07-17 23:29 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/provider/OracleApiProvider.java
> +  public Optional<List<OrchardDto>> findOrchardsByVegCode(String vegCode) {
[Optional Fix](https://github.com/bcgov/nr-spar/pull/333/commits/b90775ecff21fcc659972ec0849517ef9ba7ed4a)

2023-07-17 23:29 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/provider/OracleApiProvider.java
> +    return Optional.empty();
[Optional Fix](https://github.com/bcgov/nr-spar/pull/333/commits/b90775ecff21fcc659972ec0849517ef9ba7ed4a)

2023-07-17 23:29 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/provider/Provider.java
> +  default Optional<List<OrchardDto>> findOrchardsByVegCode(String vegCode) {
[Optional Fix](https://github.com/bcgov/nr-spar/pull/333/commits/b90775ecff21fcc659972ec0849517ef9ba7ed4a)

2023-07-17 23:29 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/OrchardService.java
> +    if (orchardList.isPresent() && orchardList.get().isEmpty()) {
[Optional Fix](https://github.com/bcgov/nr-spar/pull/333/commits/b90775ecff21fcc659972ec0849517ef9ba7ed4a)

2023-07-17 23:32 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/dto/SeedPlanUnitObjDto.java
> +    boolean spuNotAssigned) {}
I will be using it for my next task, #310. Hopefully this is ok since I'll be starting on that task tmr.

2023-07-17 23:39 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/service/OrchardService.java
> +          if (orchardLotTypeCode.isValid()) {
I like my way slightly better 😜
Filtering first then do something to the objects in the filtered array will access two lists, which is `O(2n)`.
By doing everything in 1 loop it's only `O(n)`. 
While `O(2n)` is basically `O(n)` in terms of run time growth rate, `O(n)` is still faster in run time even though it's not significant or will never have an actual impact at all

2023-07-18 21:46 UTC, RMCampos approved these changes
Good job Craig! 🚀 

There are two small changes on the readme, though.

2023-07-18 21:46 UTC, RMCampos commented on backend/CONTRIBUTING.md
> +You can check your code before submitting with `./mvnw --no-transfer-progress checkstyle:checkstyle -D checkstyle.skip=false --file pom.xml`
I'm not sure if this change was made by the linter. But we need them all together.

2023-07-18 21:46 UTC, RMCampos commented on oracle-api/CONTRIBUTING.md
> +You can check your code before submitting with `./mvnw --no-transfer-progress checkstyle:checkstyle -D checkstyle.skip=false --file pom.xml`
Same here. Get these two folks together again.

2023-07-18 22:00 UTC, craigyu commented on backend/CONTRIBUTING.md
> +You can check your code before submitting with `./mvnw --no-transfer-progress checkstyle:checkstyle -D checkstyle.skip=false --file pom.xml`
I'm the linter 👀, i thought those were typos

2023-07-18 22:07 UTC, RMCampos commented on backend/CONTRIBUTING.md
> +You can check your code before submitting with `./mvnw --no-transfer-progress checkstyle:checkstyle -D checkstyle.skip=false --file pom.xml`
No problem. In Java we often send parameters, in this case, to Maven, and those are sent with `-D` of `Define` and they should be put all together.

2023-07-18 23:40 UTC, craigyu commented on backend/CONTRIBUTING.md
> +You can check your code before submitting with `./mvnw --no-transfer-progress checkstyle:checkstyle -D checkstyle.skip=false --file pom.xml`
[restored](https://github.com/bcgov/nr-spar/pull/333/commits/19be8a84d5ef350e16480ec49b97b4edd594c67b), I will merge this now, thank you for reviewing.

2023-07-19 00:10 UTC, merged