Feat/350 create mock api for applicant agency
bcgov/nr-spar pull request #381
Opened 2023-07-27 13:54 UTC by mgaseta

# Description

Created the mock API for the applicant agency. Using only 5 sample agencies for now.

Fixes #350 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manually tested and ran unit tests

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Backend](https://nr-spar-381-backend.apps.silver.devops.gov.bc.ca/)
[Frontend](https://nr-spar-381-frontend.apps.silver.devops.gov.bc.ca/)
[Oracle-API](https://nr-spar-381-oracle-api.apps.silver.devops.gov.bc.ca/)

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar/actions/workflows/merge-main.yml)

2023-07-27 20:27 UTC, craigyu commented on frontend/src/api-service/applicantAgenciesAPI.ts
> +const getApplicantAgencies = (getEditedAgencies: boolean) => {
Please provide a comment on the usage of `getEditedAgencies`, what makes an agency edited and when do we need to get edited agencies instead of original ones

2023-07-27 20:37 UTC, craigyu requested changes
Good job! 💪
I would like to stop adding more endpoint to mock-server, it's adding necessary work and complexity to our front-end development. 
The filesAndDocs api was crashing on the test and prod environment last time from using mock server, and I don't think it's needed to spend more time on making it work. For this and future front-end development, let's just return the mock data directly through `/api-service`.

2023-07-27 20:37 UTC, craigyu commented on frontend/src/api-service/applicantAgenciesAPI.ts
> +    return res.data;
sort the data alphabetically by `clientName` before returning

2023-07-27 20:37 UTC, craigyu commented on frontend/src/components/ApplicantInformationForm/constants.ts
> +  id: 'applicant-info-combobox',
this has the same id as `applicantAgencyFieldProps`

2023-07-27 20:37 UTC, craigyu commented on frontend/src/mock-server/fixtures/ApplicantAgenciesItems.ts
> +  {
please return this array directly in `api-service/applicantAgenciesAPI.ts`

2023-07-27 20:37 UTC, craigyu commented on frontend/src/api-service/applicantAgenciesAPI.ts
> +    return res.data;
we could sort it with another property but I think `clientName` makes more sense

2023-07-27 20:40 UTC, craigyu commented on frontend/src/components/ApplicantInformationForm/index.tsx
>            <Column sm={4} md={2} lg={5}>
include this `<Column>` tag in `displayCombobox()`, so it won't take any space when no combobox is rendered

2023-07-28 17:30 UTC, mgaseta commented on frontend/src/api-service/applicantAgenciesAPI.ts
> +const getApplicantAgencies = (getEditedAgencies: boolean) => {
[fixed](https://github.com/bcgov/nr-spar/pull/381/commits/31269119661bbdadba8916bf522a496edc4a4131)

2023-07-28 17:30 UTC, mgaseta commented on frontend/src/api-service/applicantAgenciesAPI.ts
> +    return res.data;
Fixed [here](https://github.com/bcgov/nr-spar/pull/381/commits/31269119661bbdadba8916bf522a496edc4a4131)

2023-07-28 17:31 UTC, mgaseta commented on frontend/src/components/ApplicantInformationForm/constants.ts
> +  id: 'applicant-info-combobox',
Fixed [here](https://github.com/bcgov/nr-spar/pull/381/commits/2ceb25a7bd6f1ac1319a3ae25bf1be2df21b5562)

2023-07-28 18:04 UTC, mgaseta commented on frontend/src/components/ApplicantInformationForm/index.tsx
>            <Column sm={4} md={2} lg={5}>
Fixed [here](https://github.com/bcgov/nr-spar/pull/381/commits/ad93bfe6c812920a478dc265942dfc65934d5636)

2023-07-28 18:04 UTC, mgaseta commented on frontend/src/mock-server/fixtures/ApplicantAgenciesItems.ts
> +  {
Yep, done [here](https://github.com/bcgov/nr-spar/pull/381/commits/91134c1aaea8c60a5f929f623e480f9dd985ab1d)

2023-07-28 18:05 UTC, mgaseta commented on frontend/src/api-service/applicantAgenciesAPI.ts
> +const getApplicantAgencies = (getEditedAgencies: boolean) => {
Updated this, the parameter is no longer necessary, see [this](https://github.com/bcgov/nr-spar/pull/381/commits/91134c1aaea8c60a5f929f623e480f9dd985ab1d) commit

2023-08-03 17:59 UTC, craigyu approved these changes
The create seedlot page is looking really good now with this PR, a lot more professional, bye bye strong seeds orchard

2023-08-03 18:00 UTC, merged