Feat/cypress tests
bcgov/nr-spar pull request #388
Opened 2023-08-02 23:26 UTC by ArthurEncr

# Description

Run cypress locally with existing tests
add Dashboard rendering test
Seedlot main page rendering test

Fixes # [359](https://github.com/bcgov/nr-spar/issues/359)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# How to test?

- Export all environment variables (on terminal: export CYPRESS_USERNAME=[USERNAME] and same for password)
- Run the login file test with: yarn `cy:run --spec cypress/e2e/smoke-test/[TEST FILE]` or `npm run cy:open` and select the test

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

2023-08-08 17:12 UTC, craigyu requested changes
I have 1 test suite failing and 1 test stuck in pending 
![image](https://github.com/bcgov/nr-spar/assets/25162561/820fc883-0b8d-422b-8c1f-b6fb9ec8a3a5)


Error:
![image](https://github.com/bcgov/nr-spar/assets/25162561/d89004f8-d81a-4d75-af2a-cc2e96aece66)

Pending:
![image](https://github.com/bcgov/nr-spar/assets/25162561/b69d2a8e-955a-4381-89ee-c205c3c3689e)

@mgaseta do you have the same errors?

2023-08-08 17:14 UTC, craigyu commented
@ArthurEncr Please include the GitHub issue number in your branch name in the future :)

2023-08-16 17:46 UTC, craigyu commented
Let's reopen this PR when it's done.

2023-09-12 20:29 UTC, RMCampos commented
Maybe we should highlight which task is this PR related? For now, we'll have only `login-page.cy.ts` passing, right?

cc: @ArthurEncr @craigyu @mgaseta

2023-09-12 20:30 UTC, RMCampos reviewed
Are we delievering only login page tests?

2023-09-13 13:42 UTC, mgaseta requested changes
Nice job :100: :ninja: ! Added only a few small markups.
But the tests are not concise yet... Sometimes they pass, other times they fail... Maybe it's because of the internet connections instabilities and we need to adjust some timeouts.

2023-09-14 14:45 UTC, ArthurEncr commented on frontend/cypress/e2e/smoke-test/login-page.cy.ts
> +  // });
The test was in an infinite waiting state and the user was never disconnected, so I thought it would be better to comment on this part _until_ this was fixed in the project. It can be seen in Craig's comments below:
> https://github.com/bcgov/nr-spar/pull/388#pullrequestreview-1567788150

2023-09-14 16:08 UTC, ArthurEncr commented on frontend/cypress/e2e/smoke-test/aclass-seedlot-registration.cy.ts
> +  //   // Click on Complete registration
OK!

2023-09-18 18:54 UTC, mgaseta approved these changes
All the changes are looking good to me!
There is just an issue with tests being intermittent, the timeouts helped a little, but the bug is still there, but it doesn't seems to be a SPAR related...

2023-09-18 19:32 UTC, RMCampos approved these changes
LGTM. All tests passing here.

⚠️ I was thinking of the issue here, about receiving timeout at the login. One option would be to restart the login process: getting back to the landing page and hitting the login button again. That should fix the issue. We should tackle this fix in a separate PR.

2023-09-19 16:55 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/aclass-seedlot-registration.cy.ts
> +    // To do - validate after to be fixed
the toggle is working now

2023-09-19 17:53 UTC, craigyu commented
I'm trying to add [cy.session()](https://docs.cypress.io/api/commands/session) to our test config

2023-09-19 17:57 UTC, craigyu commented
I'll start another ticket for the issues I commented, let's merge this one! Good job Arthur!

2023-09-19 17:57 UTC, craigyu approved these changes

2023-09-19 17:59 UTC, merged