Feat/365 fetch parent tree by species
bcgov/nr-spar pull request #405
Opened 2023-08-16 00:12 UTC by craigyu

# Description
Implements #365 

Added a new endpoint under `Orchards` for both `./backend` and `./oracle-api`
`GET`: `/api/orchards/parent-trees/vegetation-codes/{vegCode}`
where backend's endpoint serves as a proxy that relays data from oracle-api to endpoint callers

#### Additional changes:
- added a new package `ModelMapper` from `org.modelmapper.ModelMapper` that allows us to convert entity to dto fairly easily, but readability is debatable 

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
unit tests

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

2023-08-16 01:17 UTC, craigyu commented
i dont know why sonar cloud is so damn fixated on my end point variable, WTF, it's literally how we do it everywhere else 🤬

2023-08-16 20:55 UTC, craigyu commented
Converted to Draft to adjust return values

2023-08-16 22:43 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/repository/ParentTreeRepository.java
> +  List<ParentTreeNumberProj> findAllNonRetParentTreeWithVegCode(String vegCode);
@thiagosanchezenc how does this look?

2023-08-17 12:16 UTC, thiagosanchezenc commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/repository/ParentTreeRepository.java
> +  List<ParentTreeNumberProj> findAllNonRetParentTreeWithVegCode(String vegCode);
That´s great @craigyu !

2023-08-17 14:51 UTC, mgaseta requested changes
Nice work! :1st_place_medal: :100: 
Added only 2 comments, nothing too serious.
Very complex changes, but it seems ok for me. We need a more precise review from the BE Master @RMCampos

2023-08-17 16:56 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpoint.java
> +      throw new ResponseStatusException(HttpStatus.BAD_REQUEST, e.getMessage(), e);
yup we definitely should

2023-08-17 16:58 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpoint.java
> +          String vegCode) {
The default is `required = true` I believe

2023-08-17 17:04 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpoint.java
> +          String vegCode) {
fixed this and the issue below in [one commit](https://github.com/bcgov/nr-spar/pull/405/commits/3ac45be12b1753def9bd284cdaa99f3f53b329e2)

2023-08-17 17:05 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpoint.java
> +      throw new ResponseStatusException(HttpStatus.BAD_REQUEST, e.getMessage(), e);
fixed this and the issue above in [one commit](https://github.com/bcgov/nr-spar/pull/405/commits/3ac45be12b1753def9bd284cdaa99f3f53b329e2)

2023-08-17 17:05 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpoint.java
> +      throw new ResponseStatusException(HttpStatus.BAD_REQUEST, e.getMessage(), e);
I also changed the http status to internal server error since it's catching an exception from service

2023-08-21 20:33 UTC, RMCampos requested changes
Great job 🥇 some minnor fixes, though.

2023-08-21 20:33 UTC, RMCampos commented on oracle-api/pom.xml
> +		</dependency>
I'm not sure it's a good idea adding a dependency only for mapping. I created here a quick sample of a class that could do it for us (copying same fields given their names), thake a look here: https://gist.github.com/RMCampos/408dc6c3023b7ab15b0e81b7cdab5397

2023-08-21 20:33 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/dto/ParentTreeGeneticInfoDto.java
> +    this.parentTreeGeneticQualities = new ArrayList<>();
Same here. List.of, if possible 😄

2023-08-22 18:12 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpoint.java
> +      throw new VegCodeNotFoundException();
will remove

2023-08-22 19:42 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/exception/VegCodeNotFoundException.java
> +/** This class represents a user not found and will trigger a RuntimeException. */
the file is removed [here](https://github.com/bcgov/nr-spar/pull/405/commits/ded443475f9e01a768c859f0e36580c894e867f6)

2023-08-22 19:42 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpoint.java
> +    }
[removed](https://github.com/bcgov/nr-spar/pull/405/commits/ded443475f9e01a768c859f0e36580c894e867f6)

2023-08-22 19:54 UTC, craigyu commented on backend/src/test/java/ca/bc/gov/backendstartapi/endpoint/OrchardEndpointTest.java
> +    OrchardSpuDto parentTreeDto = new OrchardSpuDto(orchardId, "ACT", 1L, new ArrayList<>());
[List of change](https://github.com/bcgov/nr-spar/pull/405/commits/f57da421ba9eccce2eb56ac6749231c2fedfed8f)

2023-08-22 19:55 UTC, craigyu commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/dto/ParentTreeGeneticInfoDto.java
> +    this.parentTreeGeneticQualities = new ArrayList<>();
[List.of() change](https://github.com/bcgov/nr-spar/pull/405/commits/f57da421ba9eccce2eb56ac6749231c2fedfed8f)

2023-08-23 19:08 UTC, craigyu commented on backend/src/test/java/ca/bc/gov/backendstartapi/provider/OracleApiProviderTest.java
> +    Assertions.assertFalse(parentTreeDtoList.isEmpty());
[Done](https://github.com/bcgov/nr-spar/pull/405/commits/369090e36260595c82d7dca1d5daedbcc0a9ee02)

2023-08-24 19:23 UTC, RMCampos approved these changes
Such a great work! Thanks @craigyu 🥇 Approved! ✅

2023-08-24 19:53 UTC, merged