Feat/403 create endpoint to validate location codes
bcgov/nr-spar pull request #410
Opened 2023-08-16 19:37 UTC by mgaseta

# Description

Creating a new endpoint that returns a client location based on the client number and location code.
This will be used to validate location codes provided by the user on the necessary forms of the frontend. 

Fixes #403 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manually tested via swagger and ran unit tests.

Here are some valid examples to test it on swagger:
Client Number: 00012797. Location Code: 00.
Client Number: 00149081. Location Code: 10.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2023-08-18 17:14 UTC, craigyu approved these changes
Nicely done! 
![image](https://github.com/bcgov/nr-spar/assets/25162561/c7db7f3e-487f-4968-8110-c681adf1a947)

2023-08-21 17:25 UTC, RMCampos requested changes
Great job. Only minor changes related to JavaDocs. 💯 🥇 

Also, how about updating all references to **forest client** as **ForestClient**? I think this can make it more clear, that's another products.

2023-08-21 17:25 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +          @Pattern(regexp = "^\\d{8}$", message = "The value must an 8-digit number")
I think you missed **be** in **The value must...**

2023-08-21 17:25 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +      @PathVariable("number")
Maybe we could use a meaningful name, like `clientNumber` ?

2023-08-21 17:25 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +   * @param number the number that identifies the client to fetch the location
I think there's a preposition thing here 🤣 when I read, it sounds it's missing **from** in the end. [to fetch the location *from*]

2023-08-21 17:25 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +   * @return the forest client location
We could make a better use of JavaDoc, pointing out what will be returned (class). Like `@return {@link ForestClientLocationDto} containing client and location data.`

2023-08-21 17:25 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/provider/ForestClientApiProvider.java
> +   * @return a single location for a forest client
Same here. Improve docs 😄

2023-08-21 17:25 UTC, RMCampos commented on backend/src/test/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpointTest.java
> +        .andExpect(status().isNotFound());
👍🏻 good job

2023-08-21 17:25 UTC, RMCampos commented on backend/src/test/java/ca/bc/gov/backendstartapi/provider/ForestClientApiProviderTest.java
> +    Assertions.assertEquals(HttpStatus.NOT_FOUND, exc.getStatusCode());
👍🏻 awesome

2023-08-21 17:25 UTC, RMCampos commented on backend/src/test/java/ca/bc/gov/backendstartapi/service/ForestClientServiceTest.java
> +    Assertions.assertEquals(ForestClientExpiredEnum.N,
👍🏻

2023-08-21 19:51 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +          @Pattern(regexp = "^\\d{8}$", message = "The value must an 8-digit number")
Clinical eye :detective: :eyes: 
Fixed https://github.com/bcgov/nr-spar/pull/410/commits/59e43eb7d69f503b0c65962d1a34e6732a4cbcf0

2023-08-21 19:54 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +   * @param number the number that identifies the client to fetch the location
Re-wrote the whole sentence, it makes more sense now (I think hahahah :stuck_out_tongue:)
Fix here https://github.com/bcgov/nr-spar/pull/410/commits/59e43eb7d69f503b0c65962d1a34e6732a4cbcf0

2023-08-21 19:54 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +   * @return the forest client location
Much better this way, thanks!
Fix here: https://github.com/bcgov/nr-spar/pull/410/commits/59e43eb7d69f503b0c65962d1a34e6732a4cbcf0

2023-08-21 19:56 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/provider/ForestClientApiProvider.java
> +   * @return a single location for a forest client
Aye aye.
Fixed here: https://github.com/bcgov/nr-spar/pull/410/commits/59e43eb7d69f503b0c65962d1a34e6732a4cbcf0

2023-08-21 19:58 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +      @PathVariable("number")
Makes sense.
Fixed here: https://github.com/bcgov/nr-spar/pull/410/commits/350d7cc863e369071e6266ae974969fad7d33350

2023-08-28 18:14 UTC, RMCampos approved these changes
Great job!! 🥇 💯 🎉

2023-08-28 18:19 UTC, merged