Fix/377 fix dashboard card v2
bcgov/nr-spar pull request #437
Opened 2023-08-28 19:03 UTC by craigyu

# Description
Implements #377 

### Frontend
- Allows users to favourite and highlight an activity.
Currently supports 3 activity, new activity need to added to `frontend/src/config/FavouriteActivitiyMap.ts`
    1. Seedlots
    2. My Seedlots
    3. Create A Class Seedlot
- updated url to seedlot related addr from `seedlot` to plural `seedlots` so it's consistent with the page title
- removed mocked fav activity endpoint from mock-server
- removed FavActivity test as it is an e2e test that requires a mock-server, it should be tested with Cypress
    - mock-server should be phased out gradually as it is hard/cumbersome to maintain and update both the actual backend and a mocked backend
- Fixed a bug where the tooltip is covered by the side-nav in narrower windows
    -  ![Image](https://github.com/bcgov/nr-spar/assets/25162561/931ed39a-b3a5-47d3-b6b5-4da4a537b9ed)
- Centred and resized fav icon (heart) as specified on Figma (1rem)
    - ![image](https://github.com/bcgov/nr-spar/assets/25162561/42980705-ead2-49aa-8ce0-2964bd6dab5a)

### Backend
- Altered the `favourite_activity` table with migration file `V19`
    - Dropped the column `enabled` since it's no longer useful, we always delete un-favourited activity so there is no use of it
    - Added audit columns `entry_timestamp` and `update_timestamp`
    - Added triggers to the columns above
- Adjusted tests to work with changes

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Manual end to end test

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

2023-08-31 15:05 UTC, mgaseta requested changes
Very good job! :1st_place_medal: :100: 
Added only a few small markups.

2023-08-31 15:05 UTC, mgaseta commented on frontend/src/views/Seedlot/MySeedlots/index.tsx
> +        }
Very nice, this page was missing the empty section for a long time!

2023-08-31 17:09 UTC, craigyu commented on frontend/src/types/FavActivityTypes.ts
> +  type: string,
replaced `,` with `;` inside the `/types` folder
https://github.com/bcgov/nr-spar/pull/437/commits/3d4a131c3df4825489e22719039c4897721f7cdc

2023-08-31 17:10 UTC, craigyu commented on frontend/src/config/FavouriteActivitiyMap.ts
> +    image: 'QuadrantPlot',
Yes I did, she said it's fine? we can chat about that in the dev meeting

2023-08-31 17:13 UTC, craigyu commented on frontend/src/api-service/favouriteActivitiesAPI.ts
> +      const acitivityList = Object.keys(FavouriteActivityMap);
nice catch, fixed https://github.com/bcgov/nr-spar/pull/437/commits/0f1598fb492ada6906ce2e41dcc772e3c99ee530

2023-08-31 17:54 UTC, craigyu commented on frontend/src/config/FavouriteActivitiyMap.ts
> +    image: 'QuadrantPlot',
ok so after discussing about it at the daily, I'm going to change that to the side menu one.
Will also fix the problem where the text isn't displayed in full
![image](https://github.com/bcgov/nr-spar/assets/25162561/30651f94-cbc7-4c94-bd93-0ab0a9dd3b08)

2023-09-01 06:36 UTC, craigyu commented on frontend/src/config/FavouriteActivitiyMap.ts
> +    image: 'QuadrantPlot',
![image](https://github.com/bcgov/nr-spar/assets/25162561/8866013c-ec38-4758-b150-b64fb276753d)

Ok, so I changed the Seedlot icon to the same one on the side menu, but I also changed the My Seedlot icon, because it's the same one as the Seedlings on the side menu. The table one is quite fitting 😜. Will confirm with the Chief Design Officer

[0dcf351](https://github.com/bcgov/nr-spar/pull/437/commits/0dcf3512b5ce1cad6d661908891c9386190ee445)
cc: @mmarsoleta

2023-09-01 12:16 UTC, mmarsoleta commented on frontend/src/config/FavouriteActivitiyMap.ts
> +    image: 'QuadrantPlot',
looks good!

2023-09-01 12:52 UTC, mgaseta approved these changes
Nice job! :1st_place_medal:

2023-09-01 17:37 UTC, merged