feat: create seedlot number api
bcgov/nr-spar pull request #440
Opened 2023-08-31 16:59 UTC by RMCampos

# Description

Create Seedlot number API.

Fixes #237 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This change was tested locally and with Unit tests.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2023-09-07 16:49 UTC, craigyu requested changes
🌱 Great job! Everything works as expected. 🌱
Just need to add an extra field in the SeedlotCreateDto

2023-09-07 16:49 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedlotCreateDto.java
> +public record SeedlotCreateDto(
Let's add another field `geneticClassCode`, currently it can be null

2023-09-07 16:49 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +    // !? validateNewSeelot(createDto);
remove the comment?

2023-09-07 21:48 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedlotCreateDto.java
> +public record SeedlotCreateDto(
Good catch. Added here: https://github.com/bcgov/nr-spar/pull/440/commits/7273e9496b70b7ad386a126db2befe382505abc5

2023-09-13 15:45 UTC, craigyu approved these changes

2023-09-13 15:46 UTC, merged