Feat/424 validate location code on frontend
bcgov/nr-spar pull request #472
Opened 2023-09-12 14:00 UTC by mgaseta

# Description

Added location code validation to all necessary places.
- Create A Class Seedlot form
- Collection Step form
- Ownership Step form
- Interim Step form
- Extraction and Storage Step form

Notable changes:
- Disable location code input, if no agency is selected
- Limited the digits on each input to 2
- Show the correct error message according to the issue
- Validate the value entered

You may notice some that steps need refactoring... (Non-related with the new changes) But this PR is too big already, we can refactor when working on validations for each step.

Fixes #424 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manually tested.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

2023-09-18 21:24 UTC, craigyu requested changes
Really nice work!  💪😎👍
All inputs are working with informative status for users.

I ignored the brain overload code smells, but we should change the operator as suggested.
![image](https://github.com/bcgov/nr-spar/assets/25162561/214effb1-131e-4f3e-bbf9-648bfb4ba09d)

![image](https://github.com/bcgov/nr-spar/assets/25162561/18226fcf-cde2-48f5-9b90-448c4f04e8bb)

What should we do with this situation, 3 is between 0-99, but we want 03, perhaps we should format it for user when the number is less than 10?

2023-09-20 11:49 UTC, mgaseta commented
@craigyu 

Fixed operator: https://github.com/bcgov/nr-spar/pull/472/commits/04114210e1ad8c55413c1a993cf7eb581ca416e5

For the single location code character, I added the zero to the left on the blur function, it looks good, but maybe we need some validation from @SLDonnelly and the UX team.

Fixed https://github.com/bcgov/nr-spar/pull/472/commits/ecaaaf5db49f8707c392bcaaf9f7e457d9f416c6 and https://github.com/bcgov/nr-spar/pull/472/commits/3c6432c5818df601b0c14f038ed1288869ebcf07

2023-09-20 16:49 UTC, RMCampos approved these changes
Great job! 🥇 💯 🎉 

I left some non-blocking thoughts and questions. Feel free to merge ❤️

2023-09-20 16:49 UTC, RMCampos commented on frontend/src/components/ApplicantInformationForm/index.tsx
> +              helperText={locHelper}
question (non-blocking): can we have a better name for the helper text? 😆

2023-09-20 16:49 UTC, RMCampos commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx
> +        newValidObj.isLocationCodeInvalid = false;
question (non-blocking): If no value, then`isLocationCodeInvalid` shouldn't be true?

2023-09-20 16:49 UTC, RMCampos commented on frontend/src/components/SeedlotRegistrationSteps/ExtractionAndStorageStep/definitions.ts
> +    locHelper: string
question (non-blocking): same here? A better name always help :)

2023-09-20 16:49 UTC, RMCampos commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +      locationCode = `0${locationCode}`;
thought: here we could have `locationCode.toString().padStart(2, '0')`

2023-09-20 19:17 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/CollectionStep/index.tsx
> +        newValidObj.isLocationCodeInvalid = false;
Actually, no, the value is for the agency field, so if the location code was invalid but the user clears the agency field, then the location code must be cleared also and remove the invalid status.

2023-09-20 19:18 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ExtractionAndStorageStep/index.tsx
> +      locationCode = `0${locationCode}`;
Nice, I'll try that!

2023-09-20 19:19 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ExtractionAndStorageStep/index.tsx
> +          newValidObj.isExtractorCodeInvalid = isInvalid;
It's the same case as the other one, when setting an empty value to the agency, clears the location code and removed invalid status.

2023-09-20 19:56 UTC, mgaseta commented on frontend/src/components/ApplicantInformationForm/index.tsx
> +              helperText={locHelper}
For sure, fixed here: https://github.com/bcgov/nr-spar/pull/472/commits/c23553932e0f7ff40a421664c76b28364790c306
Nice catch ;)

2023-09-20 19:56 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ExtractionAndStorageStep/definitions.ts
> +    locHelper: string
Fixed here: https://github.com/bcgov/nr-spar/pull/472/commits/c23553932e0f7ff40a421664c76b28364790c306

2023-09-20 19:57 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ExtractionAndStorageStep/index.tsx
> +      locationCode = `0${locationCode}`;
Waaaay fancier :wine_glass: :woman_dancing: 
Fix in this commit: https://github.com/bcgov/nr-spar/pull/472/commits/de07f326fb598aabac77746d59fa15c85a44f1f1

2023-09-20 19:58 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +      locationCode = `0${locationCode}`;
Fixed here: https://github.com/bcgov/nr-spar/pull/472/commits/de07f326fb598aabac77746d59fa15c85a44f1f1

2023-09-20 23:27 UTC, craigyu approved these changes
Approved! Waiting for @RMCampos to resolve the conversations or further comments then we can merge

2023-09-22 14:46 UTC, merged