Copy backend changes
bcgov/nr-spar pull request #48
Opened 2023-05-04 05:58 UTC by DerekRoberts

2023-05-04 20:38 UTC, DerekRoberts commented on backend/database/Dockerfile
> +# RedHat UBI 8 with nodejs 14
Not used by OpenShift/Kubernetes.  Optional for us.  Dimissing.

2023-05-04 20:38 UTC, DerekRoberts commented on backend/backend/Dockerfile
> +FROM maven:3.8.7-eclipse-temurin-17 AS build
Not used by OpenShift/Kubernetes. Optional for us. Dimissing.

2023-05-05 13:53 UTC, RMCampos requested changes
Good job! 🥳 Thanks!

Reviewed:
- Codebase ✅ 
- All tests passing ✅ 
- All checkstyle passing ✅ 
- Running locally works fine ✅ 
- Running with docker composer works fine ✅ 
- pom.xml file outdated ⚠️

2023-05-05 13:53 UTC, RMCampos commented on backend/pom.xml
We have newer dependencies version in the old repo. Since they are already tested and working, I think we should include them here.

2023-05-05 16:08 UTC, DerekRoberts commented on backend/pom.xml
This sure looks like the pom file from bcgov/nr-spar-backend.  Which deps are stale?

2023-05-05 20:29 UTC, RMCampos submitted a review, later dismissed
Great job! 🥇 Everything working!

2023-05-08 01:54 UTC, closed without merging