feat: complete smp mix tab partial implementation
bcgov/nr-spar pull request #483
Opened 2023-09-18 20:30 UTC by craigyu

# Description
Implements: #435 

### Requirements
1. The table 
        a. User should be able to type in a parent tree number 
        b. User should be able to add a row
        c. User should be able to delete a row
        d. Proportion should be calculated on the fly
        e. Uploaded file should populate table
        f. Invalid data from uploaded file should trigger errors
2. The info section
        a. Working input display: Number of SMP parents from outside and Total volume (ml)

### Testing:
Here is a simple csv file for testing upload: [SMP_Mix_Volume_template_TEST.csv](https://github.com/bcgov/nr-spar/files/12653271/SMP_Mix_Volume_template_TEST.csv)
Best used with species FDC and orchard 405

### Note:
The current page detects invalid parent tree (input becomes red) but it does not display any message or notification box. All the input related validation/error handling should be done in a separate ticket.

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Manual

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

2023-09-18 20:36 UTC, craigyu commented
trying to fix the build problem

2023-09-21 20:39 UTC, mgaseta requested changes
Really good job! :1st_place_medal: :trophy:
Added a few comments, but nothing serious.

2023-09-21 20:39 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/constants.tsx
> +    description: 'Weighted Weighted animal browse resistance (deer)',
`Weighted` duplicated.

2023-09-21 20:39 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                                )
Add a tab here, don't know how lint let this one pass :P

2023-09-21 20:39 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                          setSlicedMixRows
Tab here too.

2023-09-21 20:39 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> -      }
Nice to see this gone :1st_place_medal:

2023-09-21 20:39 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
> +
Maybe adding this const to the constants file?

2023-09-25 20:59 UTC, RMCampos approved these changes
Great job 🔝 🥇 LGTM

Left a comment though, quick suggestion, feel free to dismiss.

2023-09-25 20:59 UTC, RMCampos commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +      setDisableOptions(disabled);
suggestion (non-blocking): how about using the above expression as the argument?

2023-09-26 19:45 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +      setDisableOptions(disabled);
resolved on rocket chat

2023-09-26 19:49 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                          setSlicedMixRows
![image](https://github.com/bcgov/nr-spar/assets/25162561/5e0d0ef5-6ddf-49de-a5eb-d6e7bd5f102a)

🥲

2023-09-26 19:51 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
> +
I was debating on where this one should go and I think having it in utils makes more sense since it acts more as a function rather than a constant. The rowTemplate is coming from `./constants` and this function makes a copy of it then return a fresh one

2023-09-26 19:55 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/constants.tsx
> +    description: 'Weighted Weighted animal browse resistance (deer)',
typo fixed https://github.com/bcgov/nr-spar/pull/483/commits/92413de78806210e76d0c7c598dfb18d6969da08

2023-09-27 11:58 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                                )
![Screenshot from 2023-09-27 08-56-50](https://github.com/bcgov/nr-spar/assets/105936322/03b9db9d-03e0-4f2b-a4f4-9cf2a4fbe468)

That's sad, it looks a bit odd without the extra tab, but I guess it's okay.

2023-09-27 11:58 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +                          setSlicedMixRows
![Screenshot from 2023-09-27 08-56-50](https://github.com/bcgov/nr-spar/assets/105936322/03b9db9d-03e0-4f2b-a4f4-9cf2a4fbe468)

2023-09-27 12:03 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
> +
Hmmm, it makes sense. Is just that is a "static" function (in a way that it will always return the same value), so I thought the best place to be was in constant, but no harm on keeping it on utils. :)

2023-09-27 12:04 UTC, mgaseta approved these changes
Nice job! :1st_place_medal: :100:

2023-09-28 00:05 UTC, merged