feat: integrate ne
bcgov/nr-spar pull request #489
Opened 2023-09-20 17:01 UTC by craigyu

# Description
Implements #478

A simple PR that populates the info section with the `neValue` from the existing `calculate-all` endpoint

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2023-09-21 11:51 UTC, mgaseta requested changes
Nice job! :1st_place_medal: :rocket: 
Added only a few markups.

2023-09-21 11:51 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
> +  res: AxiosResponse,
Why use the full response here? Wouldn't it be better to just get data directly?

2023-09-21 11:51 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +  const [popSizeAndDiversityConfig, setPopSizeAndDiversity] = useState(
Maybe a huge name, but just to maintain the pattern, changing the set function to `setPopSizeAndDiversityConfig`.

2023-09-21 11:51 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
> +  const newPopAndDiversityConfig = { ...popSizeAndDiversityConfig };
Is the spread operator enough here? It looks like the value you are changing on line 359 is on a second layer, so maybe using `structuredClone` is more safe here.

2023-09-26 19:25 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
> +  const newPopAndDiversityConfig = { ...popSizeAndDiversityConfig };
I try to not use `structuredClone` too liberally since deep copying takes more resources, if the spread operator works and in this case it does, we should trust the spread operator.

2023-09-26 19:28 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +  const [popSizeAndDiversityConfig, setPopSizeAndDiversity] = useState(
gross but ok! 😛 https://github.com/bcgov/nr-spar/pull/489/commits/7040b057e2de925256be4743600bbc117cdd7050

2023-09-26 19:38 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
> +  res: AxiosResponse,
good suggestion! also updated a similar function in this same commit   
https://github.com/bcgov/nr-spar/pull/489/commits/dfdefc85f5f6a9737f77ae899abead9bd8c3a658

2023-09-27 12:09 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/index.tsx
> +  const [popSizeAndDiversityConfig, setPopSizeAndDiversity] = useState(
Agree it's gross hahahaha, but is for the best!

2023-09-27 12:10 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/ParentTreeStep/utils.ts
> +  const newPopAndDiversityConfig = { ...popSizeAndDiversityConfig };
Hmmm, I see, if the spread operator is working fine then it is ok!

2023-09-27 12:11 UTC, mgaseta approved these changes
LGTM! :1st_place_medal: :robot:

2023-09-27 16:05 UTC, merged