Fix/490 add IBM plex mono font face
bcgov/nr-spar pull request #492
Opened 2023-09-20 22:27 UTC by craigyu

# Description
Fixes: #490

A not so elegant solution to remove the font errors

2023-09-21 11:59 UTC, mgaseta requested changes
Agree that it's not as fancy as having the solution on the theme package... But at least solves our issues, good job!
Added only a few questions and a suggestion to make it less verbose.

2023-09-21 11:59 UTC, mgaseta commented on frontend/package.json
> +    "@bcgov-nr/nr-fsa-theme": "^1.2.0",
Why downgrading the theme version here?

2023-09-21 11:59 UTC, mgaseta commented on frontend/src/styles/custom.scss
> +  }
Can't we find font files for these fonts? At least `@font-face` won't be so huge...

2023-09-21 20:40 UTC, mgaseta commented on frontend/package.json
> +    "@bcgov-nr/nr-fsa-theme": "^1.2.0",
Oh, my bad hahaha. Nice then.

2023-09-26 19:02 UTC, craigyu commented on frontend/src/styles/custom.scss
> +  }
these are from @carbon's css file, using their resources to serve fonts is probably better

2023-09-26 19:02 UTC, craigyu commented on frontend/src/styles/custom.scss
> +  }
let me try if importing node module's css works

2023-09-26 19:08 UTC, craigyu commented on frontend/src/styles/custom.scss
> +  }
nope, doesn't work ^
I think this the "best" quick solution here, ideally something should be done on the theme package side

2023-09-26 20:24 UTC, mgaseta commented on frontend/src/styles/custom.scss
> +  }
Yeah, I agree, thanks for putting in the effort to try to reduce the code.

2023-09-26 20:25 UTC, mgaseta approved these changes
LGTM!

2023-09-26 20:49 UTC, merged