feat: replace Keycloak by FAM on FE
bcgov/nr-spar pull request #530
Opened 2023-09-29 14:10 UTC by RMCampos

# Description

Replace Keycloak by FAM.

Note that:
- Although this PR mess with `backend` this is only required to get it working until task #481 is finished.
- All tests pass, howerver one can see an error like this one below, already existing before this change:
![image](https://github.com/bcgov/nr-spar/assets/2219519/6cdd100b-4389-4f66-94bf-2c7666c3c7b9)

Fixes #480 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Testes locally and with unit tests;

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2023-09-29 21:49 UTC, craigyu commented
![image](https://github.com/bcgov/nr-spar/assets/25162561/fca7d1f2-7618-4c84-b00b-4ccfcde2d4e6)

Cypress is failing because FAM returned error, is it due to the PR frontend url?

2023-09-29 21:59 UTC, DerekRoberts commented
@craigyu I'm pretty sure there are issues with FAM and the PRs having different subdomains.  We can use different paths instead, if that solves the problem.  @franTarkenton solved a smilar issue with KeyCloak a while back by having domains added and removed in the workflows.  Any ideas?

2023-09-30 00:03 UTC, craigyu commented
@DerekRoberts Not sure how using different paths will work but we can try, is it as secure?

2023-09-30 00:07 UTC, DerekRoberts commented
> @DerekRoberts Not sure how using different paths will work but we can try, is it as secure?

@craigyu Security shouldn't change.  If FAM hates pr1.silva.gov.bc.ca, maybe it would like silva.gov.bc.ca/pr1 instead?  Just a suggestion, not necessarily a solution.

2023-10-02 16:15 UTC, RMCampos commented
> ![image](https://user-images.githubusercontent.com/25162561/271726114-fca7d1f2-7618-4c84-b00b-4ccfcde2d4e6.png)
> 
> Cypress is failing because FAM returned error, is it due to the PR frontend url?

Yup! Already asked to Catherine M. be adding this new PR URL. As soon that happen, we should be able to log in and out.

2023-10-02 16:17 UTC, RMCampos commented
> > @DerekRoberts Not sure how using different paths will work but we can try, is it as secure?
> 
> @craigyu Security shouldn't change. If FAM hates pr1.silva.gov.bc.ca, maybe it would like silva.gov.bc.ca/pr1 instead? Just a suggestion, not necessarily a solution.

If I got it right, even a URL like that should be mapped before hand. No wildcards at all.

2023-10-03 14:38 UTC, mgaseta requested changes
Really good job! :100: :rocket: 
Added only some questions and suggestions.

2023-10-03 14:38 UTC, mgaseta commented on frontend/src/contexts/AuthProvider.tsx
> +      localStorage.setItem(FAM_LOGIN_USER, JSON.stringify(famUser));
Is it safe enough to leave this information on local storage? At a first glance, I think it's ok, but maybe we need to discuss a bit more.

2023-10-03 14:38 UTC, mgaseta commented on frontend/src/index.tsx
> +window.global ||= window;
Had to do some research to understand this, but it makes sense! Just a suggestion, but maybe we can add it to another file and import it here. Like suggested [here](https://stackoverflow.com/questions/72114775/vite-global-is-not-defined/73208485#73208485).

2023-10-03 17:47 UTC, RMCampos commented
> > > @DerekRoberts Not sure how using different paths will work but we can try, is it as secure?
> > 
> > 
> > @craigyu Security shouldn't change. If FAM hates pr1.silva.gov.bc.ca, maybe it would like silva.gov.bc.ca/pr1 instead? Just a suggestion, not necessarily a solution.
> 
> If I got it right, even a URL like that should be mapped before hand. No wildcards at all.

@craigyu @DerekRoberts FAM was updated with PR URLs, but we need to update Caddy security config. Maybe Derek can help me on this one?
![image](https://github.com/bcgov/nr-spar/assets/2219519/9a7281ea-9f93-4981-98ec-acb94434158b)

2023-10-03 17:47 UTC, mgaseta commented
Also found this warning on the console, just thought it was worth mentioning.
![Screenshot from 2023-10-03 10-13-13](https://github.com/bcgov/nr-spar/assets/105936322/f8c3056f-8e2e-4fea-b451-7a59bf99e250)

2023-10-05 14:59 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/config/SecurityConfig.java
> +    /*
Yeah, probably habit. Removed here: https://github.com/bcgov/nr-spar/commit/78d2dbe4e4038e29f260974fb6fc0379834ea96a

2023-10-05 16:11 UTC, DerekRoberts commented on backend/src/main/java/ca/bc/gov/backendstartapi/provider/OracleApiProvider.java
> +      int size = list == null ? 0 : list.size();
I hate ternary!  It's always so hard to read and remember.

2023-10-05 18:37 UTC, RMCampos commented on frontend/src/contexts/AuthProvider.tsx
> +  const sanitizedLastName = lastName.includes(' ') ? lastName.split(' ')[1].trim() : lastName;
I don't think so. The last name will be a single word or in some cases, like my name "de Campos".

2023-10-05 18:41 UTC, RMCampos commented on frontend/src/contexts/AuthProvider.tsx
> +      localStorage.setItem(FAM_LOGIN_USER, JSON.stringify(famUser));
Yeah, we can have a discussion on the best approach for that. We could use the backend and store a cookie for example.

2023-10-05 18:52 UTC, RMCampos commented on frontend/src/index.tsx
> +window.global ||= window;
Good catch. Done here https://github.com/bcgov/nr-spar/commit/bcf86766c8b64f1010d64de8227042704f2c7b30

2023-10-19 03:22 UTC, craigyu commented
![image](https://github.com/bcgov/nr-spar/assets/25162561/db0ef9b3-29f8-41bc-afdf-fcd9be2c7a77)

I'm seeing this after logging out, probably another FAM issue.

2023-10-19 03:26 UTC, DerekRoberts commented
> ![image](https://user-images.githubusercontent.com/25162561/276471142-db0ef9b3-29f8-41bc-afdf-fcd9be2c7a77.png)
> 
> I'm seeing this after logging out, probably another FAM issue.

Could also be the logout redirect URL.  We can investigate tomorrow!  @craigyu 

@jazzgrewal did this, in case it's transferrable and relevant.
```
const redirectSignOut =
  env.VITE_REDIRECT_SIGN_OUT && env.VITE_REDIRECT_SIGN_OUT.trim() !== ""
    ? env.VITE_REDIRECT_SIGN_OUT
    : `${logoutDomain}/clp-cgi/logoff.cgi?retnow=1&returl=${retUrl}?redirect_uri=${redirectUri}/`;
```

https://github.com/bcgov/nr-results-exam/blob/789c098daeabacd9298958160d820413d72e85f1/frontend/src/aws-exports.js#L8

2023-10-24 23:48 UTC, craigyu approved these changes
Hello FAM!

2023-10-24 23:51 UTC, craigyu commented
we can arguably remove `ProtectedRoute` altogether, but i don't mind the extra layer

2023-10-25 03:05 UTC, DerekRoberts commented
Looks like we're getting close finally!  Just some SonarCloud coverage errors.  We have a parallel issue with Cypress coverage, so if that's the cause it's okay to skip or wait on that one.  @craigyu

2023-10-25 19:22 UTC, craigyu commented
Closed to merge things into the staging branch

2023-10-25 19:22 UTC, closed without merging