IGNORE-TEST: testing cypress behaviour on GHA
bcgov/nr-spar pull request #541
Opened 2023-10-04 23:33 UTC by craigyu

# Description

Please provide a summary of the change and the issue fixed. Please include relevant context. List dependency changes.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2023-10-06 18:33 UTC, mgaseta requested changes
LGTM! :1st_place_medal: 
Added only a couple of question.

2023-10-06 18:33 UTC, mgaseta commented on .github/workflows/pr-open.yml
> -          path: /home/runner/work/nr-spar/nr-spar/frontend/cypress/screenshots
Will we stop uploading failure's data?

2023-10-06 18:33 UTC, mgaseta commented on .github/workflows/pr-open.yml
> +          parameters: -p ZONE=${{ github.event.number }}
Why this change? It doesn't make sense (for me) to put only this parameter on this line. I'm adding only this comment but the same goes for similar changes on this file.

2023-10-10 18:34 UTC, craigyu commented on .github/workflows/pr-open.yml
> -          path: /home/runner/work/nr-spar/nr-spar/frontend/cypress/screenshots
We upload videos on each run so the screenshots is quite useless

2023-10-12 17:23 UTC, craigyu commented
![image](https://github.com/bcgov/nr-spar/assets/25162561/162f3dbc-cb86-4cfb-b6d4-c21da476aa57)

Coverage and dup detection seem to be working

2023-10-12 17:26 UTC, craigyu commented on .github/workflows/pr-open.yml
> +          parameters: -p ZONE=${{ github.event.number }}
fixed here https://github.com/bcgov/nr-spar/pull/541/commits/c3e0abd6ab092c2ef9740756f88be47259d4861e

2023-10-13 14:39 UTC, RMCampos approved these changes
LGTM

2023-10-16 13:00 UTC, mgaseta approved these changes
LGTM! :100:

2023-10-16 16:39 UTC, merged