feat/favourite-activity-test-created
bcgov/nr-spar pull request #544
Opened 2023-10-06 19:25 UTC by ArthurEncr

# Description

Favorites activity test added to dashboard page tests
- Favorite each page (Seedlots, Create A class and My seedlots) and check if the shortcut is working
- Test highlight and delete the cards
- Test if the empty section is showing

Fixes [#528](https://github.com/bcgov/nr-spar/issues/528)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How to test?

- Export all environment variables (on terminal: export CYPRESS_USERNAME=[USERNAME] and same for password)
- Run the login file test with: yarn `cy:run --spec cypress/e2e/smoke-test/[TEST FILE]` or `npm run cy:open` and select the test

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2023-10-09 22:57 UTC, mgaseta requested changes
Nice work!

![Screenshot from 2023-08-31 12-02-48](https://github.com/bcgov/nr-spar/assets/105936322/b3afbee7-17dd-45c1-aef0-d6fddb92f5a4)

Added only some minor markups and started some discussions.

2023-10-09 22:57 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
> +import { FIVE_SECONDS, HALF_SECOND, TWO_SECONDS } from '../../constants';
You can remove the `FIVE_SECONDS`, it's not being used.

2023-10-09 22:57 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
> +  it('fav activity is working proprely', () => {
Typo here, `proprely` should be `properly`.

2023-10-09 22:57 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
> +  it('fav activity is working proprely', () => {
IMO this `it` is too big... Can we break it into smaller pieces? For instance, one `it` to make sure the card is working, another to see if the card is correctly appearing, and so on. What do you think? Tagging @RMCampos and @craigyu to get their inputs too.

2023-10-09 22:57 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
> +      .find('.bx--popover-container')
Should we make something similar to the theme package and create a global utils for the class prefix? I think it's a good a idea, but the test can become too verbose... What do you think? Tagging @RMCampos and @craigyu too.

2023-10-09 22:57 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
> +    // Check if seedlot card is appearing at fauvorites activities
Typo on `favourites`.

2023-10-09 22:57 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
> +    // Check if Create A Class Seedlot card is appearing at fauvorites activities
Typo on `favourites`.

2023-10-09 22:57 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
> +    // Check if My Seedlot card is appearing at fauvorites activities
Typo on `favourites`.

2023-10-12 17:56 UTC, craigyu commented
![image](https://github.com/bcgov/nr-spar/assets/25162561/d7a5beff-7d0d-4011-a2cc-2fcd290f7904)
Your tests still use `cy.wait()`, please read the description that I tagged you in #532

2023-10-12 18:00 UTC, craigyu commented
Please do not bundle test together.
Each add a fav activity and verify the card is showing should be inside its own `it()`, instead of all three bundled together. Same thing for deleting.

2023-10-12 18:01 UTC, craigyu requested changes
A test is failing.

2023-10-17 17:32 UTC, mgaseta approved these changes
LGTM! :1st_place_medal: :100: :test_tube:

2023-10-18 19:11 UTC, craigyu requested changes

2023-10-19 21:19 UTC, craigyu requested changes

2023-10-19 21:19 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
> +      .click();
Two things, this comment applies to the tests below as well:
1. Can we select the button by finding it using text? The current way is clicking on the last option, in the future if we want to add another button, then this test might click on the wrong button.
2. How do we know the deletion worked? I know we are checking if an empty section is rendering, but we should still check if the deleted card is gone. The reason is that if this test passed, we assume that the delete seedlot fav card is working according to the test title, but in actuality we don't know that for sure from this test alone. Let's say we added a third button as mentioned in the first point, and this test is no longer clicking on the delete button, the test will still pass.

2023-10-19 21:20 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
> +      .click();
btw I apologize for all the trickled in request changes 😬

2023-10-20 14:14 UTC, ArthurEncr commented on frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
> +      .click();
1 - Very valid point, I made the change

2 - I added one more check to see if the number of cards is changing ;)

2023-10-23 16:38 UTC, craigyu approved these changes
Great job Arthur!

2023-10-23 16:38 UTC, merged