Feat/504 create api to retrieve a single seedlot by its number
bcgov/nr-spar pull request #549
Opened 2023-10-09 21:37 UTC by mgaseta

# Description

Created an api to retrieve information of a single seedlot from Postgre database.
This an initial version of the API so that task #475 gets unblocked as soon as possible. 

Fixes #504 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Ran unit tests and tested locally.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2023-10-12 16:52 UTC, craigyu commented
Looking good! But I think it's missing a test for the new service :P

2023-10-13 14:51 UTC, RMCampos approved these changes
Awesome! Good job. 👍🏻 LGTM

2023-10-13 14:51 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +  @GetMapping(path = "/{seedlotNumber}")
suggestion (non-blocking): when creating a mapping (GetMapping, PostMapping, etc) and there's only one argument, it will be considered the path. You don't need to add `path = ...`. You can safely remove it.

2023-10-16 17:40 UTC, craigyu requested changes
Just leaving a comment here as a reminder 😛
"9.1% Coverage on New Code (is less than 80%)"

2023-10-17 13:31 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +  @GetMapping(path = "/{seedlotNumber}")
For some reason, when removing it, the unit test fails... I'll leave as is, since is non-blocking :)

2023-10-18 17:19 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +    log.debug("Next class {} seedlot number: {}", seedlotNumber);
what does this mean?

2023-10-18 17:57 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +    log.debug("Next class {} seedlot number: {}", seedlotNumber);
I'm not sure. But we can remove it. I'll do it.

2023-10-18 17:58 UTC, craigyu approved these changes

2023-10-18 18:00 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +    log.debug("Next class {} seedlot number: {}", seedlotNumber);
Removed here: https://github.com/bcgov/nr-spar/pull/549/commits/0de8943db6347c063d96935feffe793e2aa03a4d

2023-10-18 18:24 UTC, merged