Feat/505 create api to retrieve all seedlots by user
bcgov/nr-spar pull request #556
Opened 2023-10-17 13:00 UTC by mgaseta

# Description

Created an API to make a paginated search for seedlots for an user.

Fixes #505 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Manually tested and ran unit tests.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2023-10-18 18:47 UTC, RMCampos reviewed
Only a small change, adding a page validation. Great job Matheus 🥇

2023-10-18 18:47 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +    Pageable sortedPageable = PageRequest.of(
issue: we need to prevent the user from sending `pageSize` equals zero. Adding a quick validations here should do the trick.

2023-10-18 20:26 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +    Pageable sortedPageable = PageRequest.of(
Done here: https://github.com/bcgov/nr-spar/pull/556/commits/c092f5a276eb043e9c0898b6722d1fb51c4d15e8

2023-10-18 20:27 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +          int page,
Done here: https://github.com/bcgov/nr-spar/pull/556/commits/025e8a642dbc20550cb70a6ce932b3e08bbe72eb

2023-10-20 00:22 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +  @GetMapping(path = "/search-seedlots/{userId}")
Not a big fan of this path name, can we have `/api/seedlots/users/{userId}` instead? 
since this is under the seedlots endpoint, it'll be `path = "/users/{userId}`. What do you think?

2023-10-20 00:26 UTC, craigyu requested changes
Good job with the pagination! Left a couple comments :D

2023-10-20 00:26 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +      })
Will a 404 be returned if a user has no seedlots? It looks like an empty array will be returned which is consistent to our other endpoints.

2023-10-23 14:33 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +  @GetMapping(path = "/search-seedlots/{userId}")
Yep. Much more REST compliance! Nice catch!

2023-10-23 14:58 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +      })
Good catch! Nope, this doc is wrong. We'll return an empty list yes. Updating now..

2023-10-23 15:03 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +  @GetMapping(path = "/search-seedlots/{userId}")
Here https://github.com/bcgov/nr-spar/pull/556/commits/c7f404cef2f18b90774078a1d44e8bd35bb82b75

2023-10-23 15:03 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +      })
Here https://github.com/bcgov/nr-spar/pull/556/commits/b5a8a969f2768589ad56a212504049987fa43dca

2023-10-24 17:18 UTC, craigyu approved these changes

2023-10-25 13:31 UTC, RMCampos requested changes
Great job @mgaseta 💯 only a few comments/questions.

2023-10-25 13:31 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +   * @return a list of {@link Seedlot}
suggestion (non-blocking): improve these lines of documentation.

2023-10-25 13:31 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +  @GetMapping(path = "/users/{userId}")
question: can we remove "path"?

2023-10-25 13:31 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/repository/SeedlotRepository.java
> +   * @param userId a string wih the user id
typo: `wih` instead of `with`

2023-10-25 13:31 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +        Sort.by("AuditInformation_UpdateTimestamp"));
question: Is this "Sort" function ASC or DESC? I believe we want it here to be "DESC", having the latest first.

2023-10-25 13:48 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +        Sort.by("AuditInformation_UpdateTimestamp"));
Default sorting directions is `Direction.ASC`. I'll change the sort direction.

2023-10-25 13:50 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +   * @return a list of {@link Seedlot}
Yep! https://github.com/bcgov/nr-spar/pull/556/commits/b2a587ce250a8a7e1421e4f447311f7d2aca900e

2023-10-25 13:51 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +  @GetMapping(path = "/users/{userId}")
Yes! https://github.com/bcgov/nr-spar/pull/556/commits/be841d62bfa8bc3c9288dad2c1c6fd292def636c

2023-10-25 13:51 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +        Sort.by("AuditInformation_UpdateTimestamp"));
Fixed here! https://github.com/bcgov/nr-spar/pull/556/commits/c358062270af26bdad5b5f17ae9e4f93a353e087

2023-10-25 13:52 UTC, RMCampos approved these changes
LGTM 👍🏻

2023-10-25 18:12 UTC, merged