feat: replace jwt decode and roles to use fam authorization on be
bcgov/nr-spar pull request #585
Opened 2023-10-27 21:20 UTC by RMCampos

# Description

Updates both `backend` and `oracle-api` to be able to decode FAM Cognito token.

Fixes #481 

## Type of change

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Strongly tested locally.

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

## Further comments

2023-10-30 19:10 UTC, craigyu requested changes
Great work! I think a userId is needed for the User object, we are storing userId only and that's the only way we can distinguish whether the user is using idir or bceid on the DB

2023-10-30 19:10 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelper.java
> +                IdentityProvider.fromClaim(provider).orElseThrow(),
can we have the userId in here? i think the `idpUsername` does not contain the `@idir` or `@bceid` string at the end.

2023-10-30 19:10 UTC, craigyu commented on backend/src/test/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelperTest.java
> +    builder.claim("custom:idp_display_name", "Baggings, Bilbo LWRS:EX");
nice 🧙‍♂️

2023-11-06 14:59 UTC, mgaseta approved these changes
Really nice work! :100: :1st_place_medal: 
Besides Craig's comment, I added only a small non-blocking suggestion.

2023-11-06 14:59 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelper.java
> +            jwtPrincipal.getClaimAsString("custom:idp_display_name"); // de Campos, Ricardo WLRS:EX
Suggestion (non-blocking): for extra security, maybe it's better to remove real data from the comments.

2023-11-06 14:59 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelper.java
> +        // Usually only IDIR contains comma. E.g.: de Campos, Ricardo WLRS:EX
Suggestion (non-blocking): for extra security, maybe it's better to remove real data from the comments.

2023-11-06 14:59 UTC, mgaseta commented on backend/src/test/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelperTest.java
> +    builder.claim("custom:idp_display_name", "Lord Sauron of Mordor");
Sauron is watching.

![giphy](https://github.com/bcgov/nr-spar/assets/105936322/95c71fd5-0efe-4577-a192-123ada17e977)

2023-11-08 20:16 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelper.java
> +                IdentityProvider.fromClaim(provider).orElseThrow(),
Done here! https://github.com/bcgov/nr-spar/pull/585/commits/7ea3008c687b03face7611aa2f6b221d3a28ec61

2023-11-08 20:16 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelper.java
> +            jwtPrincipal.getClaimAsString("custom:idp_display_name"); // de Campos, Ricardo WLRS:EX
Nice! Thanks. Done! https://github.com/bcgov/nr-spar/pull/585/commits/24d2ce531bc59094974b3b68c0465d7bbb6ab278

2023-11-08 20:17 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelper.java
> +        // Usually only IDIR contains comma. E.g.: de Campos, Ricardo WLRS:EX
Done here! https://github.com/bcgov/nr-spar/pull/585/commits/15bdb6974bb396367e08d8231671d1396b8f8db3

2023-11-08 20:17 UTC, RMCampos commented on backend/src/test/java/ca/bc/gov/backendstartapi/security/UserAuthenticationHelperTest.java
> +    builder.claim("custom:idp_display_name", "Lord Sauron of Mordor");
I hope he is! We're getting there 🧙🏻‍♂️

2023-11-08 21:49 UTC, craigyu approved these changes

2023-11-08 21:50 UTC, merged