fix: tests descriptions fixed
bcgov/nr-spar pull request #587
Opened 2023-10-30 14:40 UTC by ArthurEncr

# Description

Updated test descriptions to start with verbs like "should"
Fixes #[561](https://github.com/bcgov/nr-spar/issues/561)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have already been accepted and merged

## Further comments

2023-11-02 21:45 UTC, craigyu requested changes

2023-11-02 21:45 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/dashboard-page.cy.ts
> +  it('should have been able to favourite the seedlots page', () => {
Please avoid the wording of "should have been" since it is used "to express what should have happened, but did not happen".

2023-11-02 21:45 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/login-page.cy.ts
> +  it('should been able to log in with BCeID and validate user role', () => {
similar here, maybe it can be something like `it('can log in with BCeID and Validate user roles')`. Feel free to use the word should too.

2023-11-06 14:12 UTC, mgaseta approved these changes
Besides Craig's comments, LGTM!

2023-11-09 00:34 UTC, craigyu approved these changes

2023-11-09 01:36 UTC, merged