Feat/573 integrate get all recent seedlots
bcgov/nr-spar pull request #593
Opened 2023-11-02 16:27 UTC by craigyu

# Description
Sorry for the short description, short on time from being on the interview panel. 

Fixes #573 and some of #554 

- Integrated get all seedlots and get sedlot by ID endpoints for the seedlot flow.
- Added a simple 404 page for temporary use, approved by @mmarsoleta 
- Moved some folders around, mainly moving stuff from `/components` to `/views`. Reason:
    - Lots of these 'components' cannot be (or not designed to be) reused for other screens. They are screen dependant.
    - Having them in the components folder makes the folder too big.
    - Having them inside each view's folder makes maintenance much easier, as devs don't have to scroll up and down all the time in the file explorer. 

### Things that need to be done still
- Refactor the My Seedlot table, the current component in `views/MySeedlots/SeedlotDataTable` should be deleted. Refactor and use `components/SeedlotTable` instead. 
- Make agency an object instead of string in registration steps, so it's easier to get the code of an angency later 

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

2023-11-03 00:16 UTC, DerekRoberts approved these changes

2023-11-06 20:56 UTC, mgaseta requested changes
Really, REALLY nice job! :1st_place_medal: :100:  

Added a bunch of markups and questions, but nothing too major (I think).

Some general thoughts:

- This PR was waaaaaaaaay to big, took me half a day to review it and probably I left a bunch of things pass by. Although I understand the importance of every change, they should have been broken in separate PRs, for instance, updating the agency API has no relation with integrating the get all recent seedlots task.

- This a personal opinion, but the imports should follow an order pattern, I know it doesn't matter (besides from the obvious ones), but it makes the code look way more organized.

- We need to look out for using too many outside libraries and packages, it's okay for now, but it can become troublesome on the long run of the app.
 
- The agency field is already being updated in this separate PR: https://github.com/bcgov/nr-spar/pull/602

2023-11-06 20:56 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotDetails/ApplicantInformation/index.tsx
> +                <TextInput
Why using `TextInputs` here and not only texts? Is this going to editable at some point or is just a design decision? Don't see any big problem (maybe for accessibility), just wondering.

2023-11-06 20:56 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotDetails/FormProgress/index.tsx
> +            : <SeedlotRegistrationProgress progressStatus={initialProgressConfig} />
Shouldn't the steps be clickable? I guess it would very tricky and we would have to change a lot of things, but it was designed like that at a certain point, did that change?

2023-11-06 20:56 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotDetails/SeedlotSummary/index.tsx
> +        );
Maybe it's better to create a separate function to display the status, maybe even in a utils, since it's being used in a lot of places. And then render only the "normal" values, it'll even save prevent this ternary operation to run every render.

2023-11-06 20:56 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotDetails/index.tsx
> +
This would look way better in a constants.ts file :)

2023-11-06 20:56 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotDetails/styles.scss
> +    margin-right: -2.5rem;
Negative margins :nauseated_face: (but I get it...)

2023-11-07 18:06 UTC, craigyu commented
> Really, REALLY nice job! 🥇 💯
> 
> Added a bunch of markups and questions, but nothing too major (I think).
> 
> Some general thoughts:
> 
> * This PR was waaaaaaaaay to big, took me half a day to review it and probably I left a bunch of things pass by. Although I understand the importance of every change, they should have been broken in separate PRs, for instance, updating the agency API has no relation with integrating the get all recent seedlots task.
> * This a personal opinion, but the imports should follow an order pattern, I know it doesn't matter (besides from the obvious ones), but it makes the code look way more organized.
> * We need to look out for using too many outside libraries and packages, it's okay for now, but it can become troublesome on the long run of the app.
> * The agency field is already being updated in this separate PR: [Feat/588 modularize client selection and location code #602](https://github.com/bcgov/nr-spar/pull/602)
> * @craigyu mentioned that React Query have new version that changes a bunch of things, I was a little worried with it but now, seeing these new changes, I'm really worried hahaha

Thanks for the great in-depth review!
Here are my responses on the points you raised:
- yes it's too big, this was discussed in the retro, in the future I will organize a group review session for big PR.
- I agree, although I think it offers little value but having things organized is always good and pleasant to look at.
- Agreed on this one as well, I added `luxon` to replace `moment`, we should move away from using `moment` as it is not even recommended by the moment devs themselves anymore. I will create a ticket to remove the usage of `moment` in our app. https://momentjs.com/docs/ 
- Let's get your #602 merged in first and I'll resolve the conflicts here
- I started to avoid using callbacks from react query such as `onSuccess` and `onError`, it will make the transition less painful. 

The rest of your comments will be addressed individually.

2023-11-07 20:00 UTC, craigyu commented on frontend/src/App.tsx
> +          <Route path="/404" element={<FourOhFour />} />
nothing is sensitive on this page, a lot of things have changed regarding how we handle routes in the FAM staging PR, so let's just leave this as it is and put it inside the `signed` routes upon conflict resolutions with FAM.

2023-11-07 20:03 UTC, craigyu commented on frontend/src/utils/SeedlotUtils.ts
> +  return code;
In the case that there isn't a match with the vegCode list, I think it's more useful and informative to at least display some sort of relative information than an empty string.

2023-11-07 20:06 UTC, craigyu commented on frontend/src/views/FourOhFour/index.tsx
haha, yea I intended this to be like a fun, easter-egg-ish page. It is very temporary since it will be replaced by an official one soon™️, I got the go-ahead from Michelly too so it should be fine :D

2023-11-07 20:13 UTC, craigyu commented on frontend/src/views/Seedlot/SeedlotDetails/index.tsx
> +
I thought about the constants file approach, but the `onClickFunction` part stopped me from doing so. I'll make it so it it provides a path string instead of a function.

2023-11-07 20:30 UTC, craigyu commented on frontend/src/views/Seedlot/SeedlotDetails/SeedlotSummary/index.tsx
> +        );
I agree with the part of reducing the amount of condition checks, but I'm not sure about having `utils` or `constants` in every component. Would that mean we cannot have functions defined inside a component? It is easier to look at one file than two imo. Perhaps we should have a soft rule that says `utils` or `constants` is needed when the file has more than 150 lines of code? 
In addition, the render function here doesn't really fit the definition of a utility function, it's more of a functional component, I'll come up with something...

2023-11-07 20:33 UTC, craigyu commented on frontend/src/views/Seedlot/SeedlotDetails/FormProgress/index.tsx
> +            : <SeedlotRegistrationProgress progressStatus={initialProgressConfig} />
Good find, it didn't change, we should have a separate ticket for that. We probably need a step number in the query params, sounds like a 2 pointer ticket.

2023-11-07 20:38 UTC, craigyu commented on frontend/src/views/Seedlot/SeedlotDetails/ApplicantInformation/index.tsx
> +                <TextInput
I asked Michelly the same question since the Figma file is using inputs. She's neutral on this matter (plain text vs inputs). I opted for using inputs since it's easier to have the style consistent. As long as it's readOnly I reckon it won't cause problems for a11y. 

![image](https://github.com/bcgov/nr-spar/assets/25162561/6257cc96-6571-42e1-b727-888a1016de63)

2023-11-07 20:42 UTC, craigyu commented on frontend/src/App.tsx
> +          <Route path="/404" element={<FourOhFour />} />
oh right, also by putting it inside the protected, it'll be rendered inside the layout component, which will show the side nav and headers, looks really awful

2023-11-07 21:00 UTC, craigyu commented on frontend/src/utils/SeedlotUtils.ts
> + * Generate a species label in the from of `{code} - {description}`.
idk how you can catch these, eagle eyes

2023-11-07 21:31 UTC, craigyu commented on frontend/src/views/Seedlot/SeedlotDetails/index.tsx
> +
actually I can't, since the onClick function in the ComboButton can do more than just navigating. So we'll have to pass the navigation functions here, and that requires the `useNavigate()` hook, which can only be defined and used inside a component.

2023-11-07 21:33 UTC, craigyu commented on frontend/src/api-service/seedlotAPI.ts
> +  return api.get(url).then((res) => res.data);
https://github.com/bcgov/nr-spar/pull/593/commits/6edfd6cd97378a4a664661ba02ad007f65ffe42d

2023-11-07 21:33 UTC, craigyu commented on frontend/src/api-service/vegetationCodeAPI.ts
> +    // Else return an array of objs for dropdown/combobox
https://github.com/bcgov/nr-spar/pull/593/commits/6edfd6cd97378a4a664661ba02ad007f65ffe42d

2023-11-07 21:33 UTC, craigyu commented on frontend/src/views/FourOhFour/styles.scss
> +    min-width: 350px;
https://github.com/bcgov/nr-spar/pull/593/commits/6edfd6cd97378a4a664661ba02ad007f65ffe42d

2023-11-07 21:35 UTC, craigyu commented on frontend/src/views/Seedlot/SeedlotDetails/SeedlotSummary/index.tsx
> +        );
adopted the idea here for file structure: https://legacy.reactjs.org/docs/faq-structure.html

https://github.com/bcgov/nr-spar/pull/593/commits/bb9fb34673681f73fe5c4987bf2c5eabe8542c91

2023-11-08 18:56 UTC, mgaseta commented on frontend/src/App.tsx
> +          <Route path="/404" element={<FourOhFour />} />
Yep, it makes sense, no problem then. Maybe when we create a different design for it we can reconsider this point.

2023-11-08 18:59 UTC, mgaseta commented on frontend/src/views/FourOhFour/index.tsx
Nice, good to know.

2023-11-08 20:20 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotDetails/SeedlotSummary/index.tsx
> +        );
Nice work!

2023-11-08 20:21 UTC, mgaseta approved these changes
Thanks for fixing the markups, LGTM! :rocket:

2023-11-08 21:47 UTC, merged