Feat/500 patch seedlot applicant info
bcgov/nr-spar pull request #665
Opened 2023-11-16 17:45 UTC by craigyu

# Description
Closes #500
See issue thread for details

### Changelog
#### Back-end
- Implemented a new patch endpoint under `/seedlots`
- Updated tests

##  What gif/image best describes this PR or how it makes you feel?

<img src="https://media3.giphy.com/media/quQijRpxpy7UQ/giphy.gif"/>

2023-11-22 18:28 UTC, mgaseta commented on backend/src/test/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpointTest.java
> +        new SeedlotApplicationPatchDto("groot@wood.com", "PlanetX", false, false);
<img src="https://media1.giphy.com/media/xUySTXEp8EhA9PG8j6/giphy.gif"/>

2023-11-22 18:31 UTC, mgaseta reviewed
Everything LGTM!
But there is only tests for bad scenarios, shouldn't be added tests for "happy paths" too?

2023-11-22 21:54 UTC, craigyu commented
> Everything LGTM! But there is only tests for bad scenarios, shouldn't be added tests for "happy paths" too?

added! ready to be reviewed again

2023-11-23 11:45 UTC, mgaseta approved these changes
Nice job! :1st_place_medal: :100:

2023-11-23 17:37 UTC, RMCampos requested changes
Great job! 🥇  Just a few questions/suggestions 😄

2023-11-23 17:37 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +                });
praise: nice 👍🏻

2023-11-23 17:37 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +  public Seedlot patchApplicantionInfo(String seedlotNumber, SeedlotApplicationPatchDto patchDto) {
question: how about improving this method name too? Maybe `patchApplicantInformation`?

2023-11-23 17:37 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +    // To be registered indicator
suggestion: remove comment

2023-11-23 21:29 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotService.java
> +    // To be registered indicator
This comment is to show people that the `intended for crown land` indicator is also called `to be registered` indicator. I improved the comment here hoping it would be more apparent. 
https://github.com/bcgov/nr-spar/pull/665/commits/c95a61c8d3b8b6de1e028cad90d33db8f6db50d7

2023-11-23 21:30 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +      path = "/{seedlotNumber}/application-info")
As discussed in the meeting, the word "info" is widely used so this should be ok 🤓

2023-11-23 21:31 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +  public ResponseEntity<Seedlot> patchApplicantAndSeedlotInfo(
https://github.com/bcgov/nr-spar/pull/665/commits/92231132cb6415ed4e16a30472cd54e81b21534d
Updated here

2023-11-27 17:44 UTC, RMCampos approved these changes
LGTM 🌟

2023-11-27 17:56 UTC, merged