Feat/596 implement edit applicant info screen
bcgov/nr-spar pull request #691
Opened 2023-11-29 02:02 UTC by craigyu

# Description
Will complete description tmr
Closes #(issue)

### Changelog
#### New
-

#### Changed
-

#### Removed
-

### How was this tested?
- [ ] 🧠 Not needed
- [ ] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

2023-11-30 20:14 UTC, RMCampos approved these changes
LGTM. Nice refactoring with the form input type thing 🤯

2023-11-30 20:14 UTC, RMCampos commented on frontend/src/components/LotApplicantAndInfoForm/SeedlotInformation.tsx
> +            vegCodeQuery.isFetching
praise: nice 👍🏻

2023-11-30 22:15 UTC, mgaseta requested changes
Nice work!
Added a few markups and questions only.
<img src="https://media0.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif"/>

2023-11-30 22:15 UTC, mgaseta commented on frontend/src/views/Seedlot/EditAClassApplication/index.tsx
> +        />
The breadcrumb and title are not correctly padded (not sure if this is a word >.<).
Figma:
![Screenshot from 2023-11-30 19-08-03](https://github.com/bcgov/nr-spar/assets/105936322/af75808f-5fdd-4610-b806-3146d1b6faa1)

Current:
![Screenshot from 2023-11-30 19-08-31](https://github.com/bcgov/nr-spar/assets/105936322/4c3ac741-d41c-490f-90fc-dc18323d09ae)

2023-11-30 22:15 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx
> +  }, [forestClientQuery.isFetched]);
Nice!
<img src="https://media3.giphy.com/media/yJFeycRK2DB4c/giphy.gif"/>

2023-12-04 17:54 UTC, craigyu commented on frontend/src/components/ApplicantAgencyFields/index.tsx
> +              if (!e.target.readOnly) {
removed the second condition by accident, adding it back

2023-12-04 17:56 UTC, craigyu commented on frontend/src/components/ApplicantAgencyFields/index.tsx
> +              if (!e.target.readOnly) {
fixed https://github.com/bcgov/nr-spar/pull/691/commits/0a6875a0a236940ebc05d6f49e1358ab8f410285

2023-12-04 18:06 UTC, craigyu commented on frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx
> +  }, [forestClientQuery.isFetched]);
Thank you. I'm trying to use `useQuery` this way so our potential transition to tanstack query v5 will be slightly easier

2023-12-04 18:15 UTC, craigyu commented on frontend/src/views/Seedlot/EditAClassApplication/index.tsx
> +        />
https://github.com/bcgov/nr-spar/pull/691/commits/7689e2a9c777d8cddd7c2a1c3dbb4d9d57b9f385 

Fixed, added margin-top instead of padding, the bottom 0.5 is already there inside the PageTitle component so I didn't do anything about that.

2023-12-04 18:16 UTC, craigyu commented on frontend/src/views/Seedlot/CreateAClass/index.tsx
> +    // Vaidate location code
https://github.com/bcgov/nr-spar/pull/691/commits/7689e2a9c777d8cddd7c2a1c3dbb4d9d57b9f385

fixed

2023-12-04 18:17 UTC, craigyu commented on frontend/src/types/FormInputType.ts
> +export type OptionsInputType = FormInputType & { value: MultiOptionsObj };
LOL, <img src="https://media4.giphy.com/media/oC1kMe9KSU3cZKLH17/giphy.gif" width="100px"/> been watching The Office lately?

2023-12-04 18:24 UTC, craigyu commented on frontend/src/views/Seedlot/EditAClassApplication/index.tsx
> +        />
good find, I always thought it was looking slightly weird

2023-12-04 22:26 UTC, mgaseta commented on frontend/src/components/LotApplicantAndInfoForm/SeedlotInformation.tsx
> +          <h2>Seedlot information</h2>
Oh, ok, my bad, but shouldn't they be in a constants file? Hahaha 
We can discuss it better later, it's a non-blocking issue.

2023-12-04 22:26 UTC, mgaseta commented on frontend/src/types/FormInputType.ts
> +export type OptionsInputType = FormInputType & { value: MultiOptionsObj };
For sure!

2023-12-04 22:29 UTC, mgaseta approved these changes
Great job! :100: :1st_place_medal: 
(I'll not leave an Office gif this time...)

2023-12-04 23:03 UTC, merged