Feat/453 step 4 validation fe
bcgov/nr-spar pull request #699
Opened 2023-12-05 23:44 UTC by craigyu

# Description
Closes #453

### Changelog
#### Changed
- Refactored input types on Orchard step, didn't change the type for boolean fields as it appears to be useless to use it here. 
- Changed Male Gametic option selection to combobox after discussing with Sabina, Michelly and Andrea. 
- Updated some input labels according to the new design
- Fixed a bug where if a parent tree contains an orchard ID that is not present in the Orchard-Spu table, then the endpoint will crash.
    - ![MicrosoftTeams-image (9)](https://github.com/bcgov/nr-spar/assets/25162561/592a2072-87fd-4994-9df5-b666db948492)
    - Here orchard id 001 does not exist for species FDI
    - You can reproduce an error on our current test environment by having an FDI seedlot, then try to fetch parent trees by species in step 5, a 500 error will be thrown
- Optimized the `updateProgressStatus` function by adding a `prevStepNum` param, we will only check the validity and completeness of a step if the user just click out of the that step. This prevents every step getting checked when a user changes step.

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media4.giphy.com/media/JGMaGy5beukJ96I5Xw/giphy.gif" width="200"/>

2023-12-11 18:11 UTC, mgaseta requested changes
Nice work, added only a few comments.

2023-12-11 18:11 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +                  <NumberInput
Why not add the min/max props here?

2023-12-11 19:37 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +            id="female-gametic-combobox"
oooh, good point

2023-12-11 19:46 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +                  <NumberInput
Because the carbon input will automatically validate the value, and we don't have any control over it. (it doesn't change the `isInvalid` variable for us)

2023-12-11 19:55 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/index.tsx
> +                  <NumberInput
Yeah, that makes sense. No problems then.

2023-12-12 19:09 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/OrchardStep/definitions.ts
> +  hasPollenContamination: boolean,
updated! https://github.com/bcgov/nr-spar/pull/699/commits/bf3138cbef2244d68941ae6a34152b971fadd0d2

2023-12-12 19:53 UTC, mgaseta approved these changes
LGTM!
<img width="300" src="https://media3.giphy.com/media/Jt4y4zi519V6asgGhA/giphy.gif"/>

2023-12-12 21:42 UTC, merged