feat: create seedlot submission post endpoint
bcgov/nr-spar pull request #701
Opened 2023-12-06 21:35 UTC by RMCampos

# Description
Closes #557 

### Changelog
#### New
- Seedlot methods and services to save the seedlot form.

#### Changed
- None

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests (will add soon)

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media1.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

2023-12-13 19:29 UTC, mgaseta requested changes
Really REALLY nice work!
Added only 1 markup.
<img width="200" src="https://media0.giphy.com/media/ely3apij36BJhoZ234/giphy-downsized-medium.gif"/>

2023-12-14 23:41 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotCollectionMethodService.java
> +      }
In the saving form step functions for step 1, 2, 4 and 5, there exist this find existing entries then delete them before inserting mechanism, why is this needed? Theoretically, there shouldn't be any existing entries with a seedlot number that hasn't been submitted before. 
It makes sense if this will also be used for editing submitted seedlot form later, but I think it is better to update the existing records than delete then insert the records, that way the audit information can be preserved.

2023-12-15 00:25 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SeedlotCollectionMethodService.java
> +      }
Please correct me if I'm wrong. It looks like there is a flaw with this approach if it's used for editing as well (assuming this is why it's checking for duplicate/existing rows). 

Take Saving Ownership step for example, the current logic does the following:
1. Check if the `seedlot_owner_quantity` for existing rows with the provided `seedlot_number`, and put them in to a list (`soqList`)
2. If this list is empty, insert the new rows
3. If this list is NOT empty
4. Collect the IDs of these rows (`existingOwnerQtyIdList`)
5. Compare the `existingOwnerQtyIdList` with the list from the endpoint request `formStep2List`
6. Delete the IDs in `existingOwnerQtyIdList` that are not in the `formStep2List`
7. If there are more rows in `formStep2List` that aren't in `existingOwnerQtyIdList`, insert them. 

The flaw happens in step 6&7, we are assuming the existing rows that we don't delete have the same data as the submitted, but that might not be true. For instance, `original_pct_owned` or `original_pct_rsrvd` could be different.

I think there are two solutions:
1. We don't check for duplicate, this endpoint is used strictly for form submission. Create another endpoint for editing.
2. We delete every existing rows that has the same seedlot number, then re-insert everything from the `formStep2List`

2023-12-15 00:29 UTC, craigyu requested changes
👏 Great job, this was a mammoth undertaking with tons of interaction with different tables. 
I do have a couple concerns regarding the logic as commented.

2023-12-18 23:22 UTC, craigyu commented
A new branch will be created based off of this branch for issue [#714](https://github.com/bcgov/nr-spar/issues/714)

2023-12-18 23:22 UTC, closed without merging

2023-12-19 00:08 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedlotFormInterimDto.java
> +        String intermStrgLocn,
turns out this column doesn't even exist in our database, haha