fix: click on overlay closes menus
bcgov/nr-spar pull request #728
Opened 2023-12-28 14:47 UTC by ArthurEncr

# Description
Closes #726 

### Changelog
#### New
- Overlay fixed. Now when it's clicked should closes the side menus.

### How was this tested?
- [x] 🧠 Not needed
- [ ] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

2023-12-28 22:19 UTC, mgaseta requested changes
Nice job! :100: :1st_place_medal: 

Added only a few markups.

Maybe not necessary for now, but pressing the `Esc` key should also close the menus, try looking that up and if it's easy enough use this task to implement it, if not, we can create a new one.

<img width="300" src="https://media2.giphy.com/media/3o7abKhOpu0NwenH3O/giphy.gif"/>

2023-12-28 22:19 UTC, mgaseta commented on frontend/src/components/BCHeader/index.tsx
> +    if (rightPanel.notifications === true) { closeRightPanel('notifications'); } else { closeRightPanel('myProfile'); }
Use multiple lines to declare this if, it is more readable and keeps the code pattern.

2023-12-28 22:19 UTC, mgaseta commented on frontend/src/components/BCHeader/index.tsx
> +                isSideNavExpanded === true ? onClickSideNavExpand : null
Tab is looking odd here... The content should be only a tab (2 spaces) ahead of the `onClick` declaration, same goes for the closing bracket, it should on the same column of the `onClick`.

2023-12-28 22:19 UTC, mgaseta commented on frontend/src/components/BCHeader/index.tsx
> +
Remove this empty line.

2023-12-28 22:19 UTC, mgaseta commented on frontend/src/components/BCHeader/index.tsx
> +                  onKeyDown={handleClosePanel}
On `onKeyDown` event, we need to make sure that the only interactive keys are space and enter, assistive tools often uses other keys to navigate thru the page and these keys should not interact with the page.

2024-01-02 18:53 UTC, RMCampos requested changes
Great job! Thank you 💯 . I left two small requests, though. :-)

2024-01-02 18:53 UTC, RMCampos commented on frontend/src/components/BCHeader/index.tsx
> +    if (rightPanel.notifications === true) { closeRightPanel('notifications'); } else { closeRightPanel('myProfile'); }
nitpick: I think you can safely replace `if (rightPanel.notifications === true)` by `if(rightPanel.notifications)` since TS is more reliable than JS 😄

2024-01-02 18:53 UTC, RMCampos commented on frontend/src/components/BCHeader/index.tsx
> +                isSideNavExpanded === true ? onClickSideNavExpand : null
nitpick: same here. No need to compare with `true` since `isSideNavExpanded` is a boolean. Wait.. That's an `any` 😢 

Maybe we improve this piece of code, and replace `{ isSideNavExpanded, onClickSideNavExpand }: any` by `{ isSideNavExpanded: boolean, onClickSideNavExpand: Function }`? Or a simple interface.

2024-01-05 20:09 UTC, craigyu requested changes
Working nicely! 

I strongly recommend you to start using the auto-indent function on VSC, it will format things for you.
https://code.visualstudio.com/docs/editor/codebasics#_formatting
The image below shows the edits you'll need to make, but it's a non-issue. 
![image](https://github.com/bcgov/nr-spar/assets/25162561/0e4e70c7-45aa-4c0e-9287-37924068455b)

2024-01-05 20:09 UTC, craigyu commented on frontend/src/components/BCHeader/index.tsx
> +
Put this inside the `definitions.ts` file

2024-01-05 20:50 UTC, mgaseta approved these changes
LGTM! :100: :1st_place_medal: 
Added only 2 non-blocking enhancements.

2024-01-05 20:50 UTC, mgaseta commented on frontend/src/components/BCHeader/index.tsx
> +          onClick={isSideNavExpanded === true ? onClickSideNavExpand : null}
You can safely remove the `=== true`, the variable type is a `boolean`, so there is no need for it.

2024-01-05 20:50 UTC, mgaseta commented on frontend/src/components/BCHeader/index.tsx
> +                isSideNavExpanded === true ? onClickSideNavExpand : null
Same here.

2024-01-08 21:13 UTC, craigyu approved these changes

2024-01-09 19:53 UTC, RMCampos approved these changes
LGTM

2024-01-10 06:27 UTC, merged