Feat/718 create and integrate get interim facility types endpoint
bcgov/nr-spar pull request #733
Opened 2024-01-03 18:28 UTC by mgaseta

# Description
Closes #718 

### Changelog
#### New
- New facility type endpoint on `oracle-api`
- Integration of the endpoint on the FE

#### Changed
- Changed a test case on `OrchardEndpointTest.java` to remove annoying warning
- Wrong file name for `fundingSourcesAPI.ts` file

#### Removed
- Nothing

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?
<img width="250" src="https://media0.giphy.com/media/MdA16VIoXKKxNE8Stk/giphy.gif"/>

2024-01-09 21:31 UTC, RMCampos requested changes
Great job! 💯 just small changes before shipping this up!

2024-01-09 21:31 UTC, RMCampos commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +    facilityTypes.push(facilityTypes.splice(facilityTypes.indexOf(otherType[0]), 1)[0]);
praise: Nice 👍🏻

2024-01-09 21:31 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/FacilityTypesEndpoint.java
> +@Slf4j
chore: remove log4j and use new class `SparLog`. Just replace `log.info(...)` by `SparLog.info(...)`;

2024-01-09 21:31 UTC, RMCampos commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/FacilityTypesEndpoint.java
> +    log.info("Fetching all valid facility types");
chore: remove log4j and use new class `SparLog`. Just replace `log.info(...)` by `SparLog.info(...)`;

2024-01-10 06:12 UTC, craigyu requested changes
Good job! 👍 and apologies for the late review.

I found a way to crash the app.
Clicking on a seedlot on the seedlot dashboard page will lead to a crashed blank page with the following error:

![image](https://github.com/bcgov/nr-spar/assets/25162561/8e5f2895-d327-45a2-be3a-77e01b542ec9)

This is due to the facility types being fetched only on the seedlot form view container. When the FormReview is loaded with the InterimStep component, the FacilityType is undefined.

One solution is to add a guard on the `renderFacilityTypes` function:
```javascript
const renderFacilityTypes = () => {
    // Change order of the array to set the
    // OTH value on the last position
    if (facilityTypes.length) {
      const otherType = facilityTypes.filter((types: MultiOptionsObj) => types.code === 'OTH');
      facilityTypes.push(facilityTypes.splice(facilityTypes.indexOf(otherType[0]), 1)[0]);

      return facilityTypes.map((type: MultiOptionsObj) => (
        <RadioButton
          id={`facility-type-radio-btn-${type.code.toLowerCase()}`}
          key={type.code}
          labelText={type.label}
          value={type.code}
        />
      ));
    }
    return null;
  };
```
However, it's probably better to just fetch the data on the component (InterimStep's index.tsx) level. Basically moving that `useQuery()` from the view to component. 
It'd be nicer to implement some Carbon component skeleton at the facility type input area while the query is fetching.

2024-01-10 06:24 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +    facilityTypes.push(facilityTypes.splice(facilityTypes.indexOf(otherType[0]), 1)[0]);
I would add a check here just in case the `otherType` is empty after filtering for some unexpected reason. 
something like
```javascript
const otherType = facilityTypes.filter((types: MultiOptionsObj) => types.code === 'OTH');

if (otherType.length) {
    facilityTypes.push(facilityTypes.splice(facilityTypes.indexOf(otherType[0]), 1)[0]);
}
```

2024-01-10 14:06 UTC, mgaseta commented on oracle-api/src/main/java/ca/bc/gov/backendstartapi/endpoint/FacilityTypesEndpoint.java
> +    log.info("Fetching all valid facility types");
Fixed here: https://github.com/bcgov/nr-spar/pull/733/commits/664a7ecadeee79e5df439cda573407c11778ecc0

2024-01-10 14:08 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +    facilityTypes.push(facilityTypes.splice(facilityTypes.indexOf(otherType[0]), 1)[0]);
Fixed here: https://github.com/bcgov/nr-spar/pull/733/commits/94e6c57125ac14b069adc6999f0645b2796c50f5

2024-01-10 14:15 UTC, mgaseta commented
> Good job! 👍 and apologies for the late review.
> 
> I found a way to crash the app. Clicking on a seedlot on the seedlot dashboard page will lead to a crashed blank page with the following error:
> 
> ![image](https://private-user-images.githubusercontent.com/25162561/295464340-8e5f2895-d327-45a2-be3a-77e01b542ec9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTU3NDcsIm5iZiI6MTcwNDg5NTQ0NywicGF0aCI6Ii8yNTE2MjU2MS8yOTU0NjQzNDAtOGU1ZjI4OTUtZDMyNy00NWEyLWJlM2EtNzdlMDFiNTQyZWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE0MDQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NjVkNDAwNGM3NTJmYzNkMjAyMGQ5NmVjYTQ2MTQ3YzVmNDM4NTBlMDI4NTNkNWVmNzAzOTg0NDQzYWY3NmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3yiwJYjCT4XFaHHUplyIPTeMwRROP4g-umRD5q6Lnxo)
> 
> This is due to the facility types being fetched only on the seedlot form view container. When the FormReview is loaded with the InterimStep component, the FacilityType is undefined.
> 
> One solution is to add a guard on the `renderFacilityTypes` function:
> 
> ```js
> const renderFacilityTypes = () => {
>     // Change order of the array to set the
>     // OTH value on the last position
>     if (facilityTypes.length) {
>       const otherType = facilityTypes.filter((types: MultiOptionsObj) => types.code === 'OTH');
>       facilityTypes.push(facilityTypes.splice(facilityTypes.indexOf(otherType[0]), 1)[0]);
> 
>       return facilityTypes.map((type: MultiOptionsObj) => (
>         <RadioButton
>           id={`facility-type-radio-btn-${type.code.toLowerCase()}`}
>           key={type.code}
>           labelText={type.label}
>           value={type.code}
>         />
>       ));
>     }
>     return null;
>   };
> ```
> 
> However, it's probably better to just fetch the data on the component (InterimStep's index.tsx) level. Basically moving that `useQuery()` from the view to component. That way you can implement some Carbon component skeletons at the facility type input area while the query is fetching.

Couldn't reproduce this error... But changed the data fetch to the component either way :)

Just a note here, we still load some data direct on the view that will only be used in a certain step, maybe we need to rethink those too.

Ready for review here: https://github.com/bcgov/nr-spar/pull/733/commits/94e6c57125ac14b069adc6999f0645b2796c50f5

2024-01-10 16:51 UTC, craigyu requested changes
just one more thing 😬

2024-01-10 16:51 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +            }
The skeletons do not appear when the query is loading, the following edit should fix it:
![image](https://github.com/bcgov/nr-spar/assets/25162561/633fa4d1-4e3c-479d-be05-5a920dad2b48)

Also, since facility types are relatively static, we can cache the value to prevent fetching on every component mount: 
![image](https://github.com/bcgov/nr-spar/assets/25162561/25659952-1133-48b1-bbe9-3b07fef3c803)

2024-01-10 16:58 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationSteps/InterimStep/index.tsx
> +            }
Fixed here: https://github.com/bcgov/nr-spar/pull/733/commits/eb824a03d06c4272c7015360203cec80641a10d0

2024-01-10 19:30 UTC, craigyu approved these changes

2024-01-10 20:22 UTC, merged