Feat/604 create endpoints to store and retrieve form json
bcgov/nr-spar pull request #741
Opened 2024-01-04 20:49 UTC by craigyu

# Description
Closes #604 

### Changelog
#### New
- 2 migration files
    1. add triggers to tables introduced in V21 and V22
    2. add new table `seedlot_registration_a_class_save`
- 3 endpoints
    1. ![image](https://github.com/bcgov/nr-spar/assets/25162561/ae0671e8-810f-4b6c-a8ec-7bf3c763f7c3)
    2. ![image](https://github.com/bcgov/nr-spar/assets/25162561/2d20b5c4-647d-4818-9781-f03657d3cf39)
    3. ![image](https://github.com/bcgov/nr-spar/assets/25162561/439ed749-7222-4955-a175-9285c8b8cdba)
- Related tests

### How was this tested?
- [ ] 🧠 Not needed
- [ ] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media0.giphy.com/media/T1tbHt3uEgc6IW4yr7/giphy.gif" width="200"/>

2024-01-04 20:53 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/entity/embeddable/AuditInformation.java
> +  @Column(name = "entry_timestamp", nullable = true, updatable = false)
this and `update_timestamp` can be null because the DB triggers will automatically set a value.

2024-01-09 21:42 UTC, RMCampos requested changes
Good job 💯 some comments though :)

2024-01-09 21:42 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SaveSeedlotFormService.java
> +
chore: can we have one or more log lines here to be able to track possible issues later? Tip: Pick `SparLog.info` instead of `log.info`.

2024-01-09 21:42 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SaveSeedlotFormService.java
> +    ObjectMapper mapper = new ObjectMapper();
chore: same here. If possible, add a log message.

2024-01-09 21:42 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SaveSeedlotFormService.java
> +    ObjectMapper mapper = new ObjectMapper();
chore: same here. If possible, add a log message.

2024-01-10 06:32 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SaveSeedlotFormService.java
> +
Done! not sure why github doesn't show this quoted file is outdated, but the changes are pushed.

2024-01-10 06:34 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/SaveSeedlotFormService.java
> +
https://github.com/bcgov/nr-spar/pull/741/commits/a4d735de8eb97befae5c0b46c41ae97528befa22
https://github.com/bcgov/nr-spar/pull/741/commits/305d7aae03de0663bfa5b7d9f63d516c6780b72b

2024-01-10 19:41 UTC, mgaseta approved these changes
LGTM! :1st_place_medal:

2024-01-10 21:40 UTC, RMCampos approved these changes
LGTM great job! 🥇

2024-01-10 22:09 UTC, merged