fix: width adjusted at empty section container
bcgov/nr-spar pull request #742
Opened 2024-01-05 14:02 UTC by ArthurEncr

# Description
Closes #735 

### Changelog
#### New
- Adjusted width at empty section of seedlot table 

#### Changed
- Nothing

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

2024-01-05 18:39 UTC, craigyu requested changes
https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=6582-116390&mode=design&t=nnfnHZQ9VvHAf47D-4

Working as expected! 
but there has a been a design change to the icon/pictogram of the empty section, should be a quick update

2024-01-09 13:33 UTC, mgaseta approved these changes
Other than Craig's markup, LGTM!

2024-01-09 22:05 UTC, RMCampos approved these changes
LGTM 🚀

2024-01-10 06:16 UTC, craigyu requested changes
![image](https://github.com/bcgov/nr-spar/assets/25162561/a2fec077-e987-42c7-8459-92070736df9a)

Did you forget to push your changes by any chance? let's add that hot coffee mug ☕️

2024-01-10 14:11 UTC, ArthurEncr commented
> ![image](https://private-user-images.githubusercontent.com/25162561/295467221-a2fec077-e987-42c7-8459-92070736df9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4OTU4NDcsIm5iZiI6MTcwNDg5NTU0NywicGF0aCI6Ii8yNTE2MjU2MS8yOTU0NjcyMjEtYTJmZWMwNzctZTk4Ny00MmM3LTg0NTktOTIwNzA3MzZkZjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDE0MDU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NTA0MWQwNzFmODA5YWVmMmJhYzkzNDgzMDE3NjFiOWJkMGM5MTM5MTEzYmQwZjIyOTg0NzYxMGJhZWI0MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HyDPOQhZP3uc8F60fUVddoRjfYZ1ou0WHmsCUDBxMK4)
> 
> Did you forget to push your changes by any chance? let's add that hot coffee mug ☕️

A hot coffee for Craig (I guess I forgot then, I just made another push)

2024-01-10 16:40 UTC, craigyu requested changes

2024-01-10 16:40 UTC, craigyu commented on frontend/src/components/EmptySection/styles.scss
> +  color: colors.$blue-60;
Please change the colour of this icon only for that page, changing it for this component will affect other pages that use it, such as:

![image](https://github.com/bcgov/nr-spar/assets/25162561/2c0d8b9b-d75c-4915-9fb2-d8a9a0dcab7e)

You can probably do that by adding a color override in  `frontend/src/components/SeedlotTable/styles.scss` under `.empty-recent-seedlots`

2024-01-10 16:41 UTC, craigyu commented on frontend/src/components/EmptySection/styles.scss
> +  color: colors.$blue-60;
@mmarsoleta should we change the colour for empty icon/pictogram for all empty sections or just for the empty seedlot table?

2024-01-10 17:21 UTC, mmarsoleta commented on frontend/src/components/EmptySection/styles.scss
> +  color: colors.$blue-60;
For all the empty states' icons, we will be using the blue color for now on.  Thank you for asking!

2024-01-10 19:29 UTC, merged