Fix/773 frontend responsiveness complete seedlot register
bcgov/nr-spar pull request #797
Opened 2024-01-23 17:10 UTC by ArthurEncr

# Description
Closes #(issue)

### Changelog
#### New
- New breadcrumb component to edit and complete seedlot register screen, now when using small screens the middle breadcrumb should transform into an overflow menu

#### Changed
- Registration steps vertical on small screens (320px)

#### Removed
- Nothing

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

I still haven't found the solution for the bug related to not showing step 6 on medium screens (672px)

###  What gif/image best describes this PR or how it makes you feel?

2024-01-24 11:49 UTC, mgaseta requested changes
Nice job!
Added a some comments to improve the new component and other small fixes.

2024-01-24 11:49 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationBreadcrumb/index.tsx
> +import React from 'react';
Nice work, but how about making this component work for all breadcrumbs?
You can create a type with display name and path and pass to the component an array of this new type, then map this array and create the breadcrumb. (Just a way to do it, there are probably others)

2024-01-24 11:49 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss
> +  }
Adjust indentation here.

2024-01-24 11:49 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss
> +
Also, add a new parent class to these styles, so we can make sure the styles are only being applied to this component.

2024-01-24 11:49 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss
> +  .bx--breadcrumb{
Change `bx` to use the var from design token variables you imported.

2024-01-24 11:49 UTC, mgaseta commented on frontend/src/components/SeedlotRegistrationBreadcrumb/styles.scss
> +}
Add new line at EOF.

2024-01-24 11:49 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx
> +import SeedlotRegistrationBreadcrumb from '../../../components/SeedlotRegistrationBreadcrumb';
Add this import with the other component imports, should be a few lines up.

2024-01-24 16:38 UTC, ArthurEncr commented on frontend/src/components/SeedlotRegistrationBreadcrumb/index.tsx
> +import React from 'react';
Right! im going to start to work on that! :)

2024-01-25 20:08 UTC, ArthurEncr commented
**New component called "BCBreadcrumb" Created!** 
_Behavior:_ An array with all breadcrumbs (with respective names and paths) must be passed through props to the component. On mobile devices, all breadcrumb items that are not the first and last will enter the overflow menu.

2024-01-25 21:10 UTC, mgaseta requested changes
Thanks for the changes!
Added some markups.
Also, a lot of these issues are listed on the IDE as errors, maybe something with your IDE or with ESLint? We can take a look at it if you want.

2024-01-25 21:10 UTC, mgaseta commented on frontend/src/components/BCBreadcrumb/index.tsx
> +const BCBreadcrumb = ({breadcrumbData}:BCBreadcrumbProps) => {
Change the name here, no need for the `BC` prefix (maybe something like `DisplayBreadcrumb`), also add spaces between the `{` and `breadcrumbData`.

2024-01-25 21:10 UTC, mgaseta commented on frontend/src/components/BCBreadcrumb/index.tsx
> +  const lastBreadcrumb = breadcrumbData.length - 1
Add `;`

2024-01-25 21:10 UTC, mgaseta commented on frontend/src/components/BCBreadcrumb/index.tsx
> +  const overflowData = breadcrumbData.slice(1, lastBreadcrumb)
Add `;`

2024-01-25 21:10 UTC, mgaseta commented on frontend/src/components/BCBreadcrumb/index.tsx
> +  if (breadcrumbData.length >= 3) {
I don't think this if needs to be here, add this validation as a ternary operation inside the breadcrumb component.
Also, there are a lot of indentation issues on these tags... Please attend to them.

2024-01-25 21:10 UTC, mgaseta commented on frontend/src/components/BCBreadcrumb/index.tsx
> +  ;
???

2024-01-25 21:10 UTC, mgaseta commented on frontend/src/views/Seedlot/EditAClassApplication/index.tsx
> +]
Missing `;` and wrong indentation.

2024-01-25 21:10 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx
> +
Missing `;` and wrong indentation.

2024-01-25 21:10 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx
> +import BCBreadcrumb from '../../../components/BCBreadcrumb';
Change this import to a few lines up (with the other component imports).

2024-01-25 21:20 UTC, mgaseta commented on frontend/src/views/Seedlot/EditAClassApplication/index.tsx
> +        <BCBreadcrumb breadcrumbData={EditAClassApplicationBreadcrumbs}/>
Missing space between last prop and `/>`

2024-01-29 16:51 UTC, mgaseta requested changes
Waaaaay better, nice that you fixed your IDE issues.
Added only a few more mark ups.

2024-01-29 16:51 UTC, mgaseta commented on frontend/src/views/Seedlot/EditAClassApplication/index.tsx
> +  ];
You can add this const to a `constant.ts` file.

2024-01-29 16:51 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx
> +  ];
You can add this const to a `constant.ts` file too.
Also, change the name of the const to something more related to the component.

2024-01-29 16:51 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotRegistrationForm/index.tsx
> +import DisplayBredcrumb from '../../../components/DisplayBreadcrumb';
Import name is wrong, it'll work because you are exporting default on the component, but for better consistence, use the correct name.

2024-01-29 16:51 UTC, mgaseta commented on frontend/src/components/DisplayBreadcrumb/index.tsx
> +        ) : null}
I don't think that you need these two ternary checks, maybe there is a way to transform them into a single one? This way we can also avoid to use styles like `display: none` maybe we can discuss that over a call or in the dev collab meeting.

2024-01-29 16:51 UTC, mgaseta commented on frontend/src/components/DisplayBreadcrumb/index.tsx
> +  const overflowData = breadcrumbData.slice(1, lastBreadcrumb);
Maybe changing the name of this variable is a good idea, most of the times it won't be related to overflow data.

2024-01-29 20:46 UTC, RMCampos approved these changes
Very nice job! 💯 

Regarding Matheus's comment, all good.

2024-02-05 18:32 UTC, ArthurEncr commented on frontend/src/components/DisplayBreadcrumb/index.tsx
> +        {(breadcrumbData.length >= 3 && window.innerWidth <= 671)
Before I was using 320px there, but Matheus told me to count the values below the medium size screen (672) as small

2024-02-05 18:33 UTC, ArthurEncr commented on frontend/src/components/DisplayBreadcrumb/index.tsx
> +    }[];
OK

2024-02-05 18:35 UTC, ArthurEncr commented on frontend/src/components/DisplayBreadcrumb/styles.scss
> +}
I'm using ".#{vars.$bcgov-prefix}--breadcrumb" to change the styles, because some styles come by default in carbon components and I wanted to change this behavior. I'm not sure how to use the grid system to have this same effect.
​

2024-02-05 21:59 UTC, craigyu commented on frontend/src/components/DisplayBreadcrumb/styles.scss
> +}
I see, you're right, please disregard this comment.

2024-02-05 22:01 UTC, DerekRoberts commented on frontend/src/components/DisplayBreadcrumb/styles.scss
> +}
And this comment too!  Absolutely no value!  ;)

2024-02-05 22:38 UTC, craigyu commented on frontend/src/components/DisplayBreadcrumb/styles.scss
> +}
the problem with this is that the default behaviour will happen again in medium sized window. A style applied to the entire component will be just fine.

2024-02-05 22:53 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationProgress/index.tsx
> +    vertical={window.innerWidth <= SMALL_SCREEN_WIDTH}
this doesn't actually work, will update this to use the hook I created.

2024-02-05 22:54 UTC, craigyu approved these changes

2024-02-06 12:27 UTC, mgaseta approved these changes
Great job @craigyu and @ArthurEncr !
Added only a few non-blocking questions.

2024-02-06 12:27 UTC, mgaseta commented on frontend/src/components/Breadcrumbs/constants.ts
> +export const DEFAULT_MAX_CRUMBS = 4;
Do we need a default for max crumbs? What if a page got more than 4? Or is this a design rule?

2024-02-06 12:27 UTC, mgaseta commented on frontend/src/components/Breadcrumbs/styles.scss
> +  .#{vars.$bcgov-prefix}--breadcrumb{
Sorry for nitpicking, but there is a missing space between the class and the `{`.

2024-02-06 12:27 UTC, mgaseta commented on frontend/src/hooks/UseWindowSize.tsx
Nice hook!

2024-02-06 12:27 UTC, mgaseta commented on frontend/src/views/Seedlot/EditAClassApplication/utils.ts
Why use an utils file here? The function will return pretty much the same result, shouldn't this be on constants.ts?

2024-02-06 17:58 UTC, craigyu commented on frontend/src/components/Breadcrumbs/constants.ts
> +export const DEFAULT_MAX_CRUMBS = 4;
there's no rule for this, but if we want to use overflow menu we need to have some sort of upper limit, carbon design guide says breadcrumbs should not be more than 1 line, so I made this one up. 
In practicality this means more than 4 crumbs will have their middle ones sandwiched between 2 at the start and 2 at the end.

2024-02-06 17:59 UTC, mgaseta requested changes
Actually... It doesn't seem to be working properly.
Here is a print of a small screen:
![Screenshot from 2024-02-06 14-57-35](https://github.com/bcgov/nr-spar/assets/105936322/6eb9033d-5848-49fb-bc8b-411f7c5b42ae)
The progress bar is not on vertical...

2024-02-06 18:00 UTC, craigyu commented on frontend/src/views/Seedlot/EditAClassApplication/utils.ts
My argument is that it is a function that returns an object depending on a parameter, so strictly speaking it is not a constant.

2024-02-06 18:00 UTC, mgaseta commented on frontend/src/components/Breadcrumbs/constants.ts
> +export const DEFAULT_MAX_CRUMBS = 4;
Hmmm, ok that sounds good to me. Thanks for the clarification s2!

2024-02-06 18:04 UTC, craigyu commented
> Actually... It doesn't seem to be working properly. Here is a print of a small screen: ![Screenshot from 2024-02-06 14-57-35](https://private-user-images.githubusercontent.com/105936322/302730796-6eb9033d-5848-49fb-bc8b-411f7c5b42ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNDI2NjMsIm5iZiI6MTcwNzI0MjM2MywicGF0aCI6Ii8xMDU5MzYzMjIvMzAyNzMwNzk2LTZlYjkwMzNkLTU4NDgtNDlmYi1iYzhiLTQxMWY3YzViNDJhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxNzU5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWM4NDk3YTcxOTU2ZWNkMGM4OTk3Y2NiOTU5NTJmNTU3YTE1ZGEzNDM0Zjk1ZDIxYzJiMjdkMjNiYTE1ZGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lpBQUgYC1AH3azZUhxKt9iPqv7HKvMaQWe6Z7k_36lQ) The progress bar is not on vertical...

I just replaced Arthur's code here with the hook I made, I will update it to different limit.
![image](https://github.com/bcgov/nr-spar/assets/25162561/b9fc79de-1ff3-4cd8-bc10-c2d5773ff885)

2024-02-06 18:53 UTC, mgaseta commented on frontend/src/views/Seedlot/EditAClassApplication/utils.ts
Yeah, that do makes sense... It's just weird to see a function that returns almost exactly the same thing every time on the `utils.ts`. But that's ok, I will get use to it.

2024-02-06 18:54 UTC, mgaseta approved these changes
Approved!!
(Sorry for taking so long with this one).
<img size="250" src="https://media0.giphy.com/media/FoH28ucxZFJZu/giphy.gif"/>

2024-02-06 20:17 UTC, mgaseta approved these changes
Nice new changes!
Added only a small markup.

2024-02-06 21:02 UTC, craigyu commented on frontend/src/views/Seedlot/SeedlotRegFormClassA/styles.scss
> +      .bx--actionable-notification__action-button {
auto formatting sold me out

2024-02-06 23:39 UTC, merged