Feat/499 create component structure for client search modal on fe
bcgov/nr-spar pull request #799
Opened 2024-01-23 22:23 UTC by mgaseta

# Description
Closes #499

Added some mock data and a few checks so it can be fully tested.
- For error message, type 'error' on the search bar
- For all data, type 'all' on the search bar (pagination and scroll tests)
- For empty check, search for non-existent data

### Changelog
#### New
- Added modal for client search

#### Changed
- Renamed files and types

#### Removed
- Removed duplicated type.

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?
<img width="300" src="https://media0.giphy.com/media/CKk1SEx4ORTSFYFR2a/giphy.gif"/>

2024-01-26 04:12 UTC, craigyu requested changes
Kudos for making it work on all screens! 

Found one bug that needs some attention:
![image](https://github.com/bcgov/nr-spar/assets/25162561/8f2d789a-2d3a-49ca-bfec-443f8383fff3)

This error shows up when you try to set a client from the modal when the default checkmark is checked. Note that this will only show up once, you might need to refresh your page to make it show up again.

Also I'm not sure if people should be able to set a client when the default is checked

2024-01-26 04:12 UTC, craigyu commented on frontend/src/api-service/forestClientsAPI.ts
> +};
+1 point for realism 😆

2024-01-29 16:33 UTC, mgaseta commented
@craigyu Fixed the bug and confirmed with Michelly about showing the link only when the "Default" option is not checked.
Design comment [here](https://www.figma.com/file/rFkWfep2NnJMdXku4GTXTN?node-id=429:447359&mode=dev#682094518).
Fexied [here](https://github.com/bcgov/nr-spar/pull/799/commits/a28761742df3d8fccd008abb8a15f465384e34c6)

2024-01-29 20:54 UTC, RMCampos approved these changes
Good job! 🥇 Just one small suggestion.

Works great!

2024-01-29 20:54 UTC, RMCampos commented on frontend/src/components/ApplicantAgencyFields/ClientSearchModal/ClientSearchFields.tsx
> +            href="#"
suggestion (non-blocking): can we have something else here, that doesn't change the URL?

2024-01-30 04:10 UTC, craigyu commented on frontend/src/components/ApplicantAgencyFields/ClientSearchModal/ClientSearchFields.tsx
> +            href="#"
sorry for hijacking the PR, I need this merged so I can avoid conflict with my current task.
https://github.com/bcgov/nr-spar/pull/799/commits/9a426dc34598ee58e81f02f88c0b531714735404

I changed the carbon Link element here to a react-router-dom one as it provides better functionality with our routing.

Also changed the other hyperlink style text to button since all it does is opening the modal.

Fixed a box-shadow issue on disabled button.

Adjusted the validation logic for the linkage between collection step and interim step, basically interim step should always follow the value set in collector step if use default is checked. we don't need to validate those fields as users need to fix the value in collection step before they are able to submit the form. Without this adjustment, it works kinda weird with the smart save feature.

2024-01-30 04:11 UTC, craigyu approved these changes

2024-01-30 04:14 UTC, merged