Feat/498 create api to fetch client search paginated screen
bcgov/nr-spar pull request #808
Opened 2024-01-26 00:46 UTC by craigyu

# Description
Closes #498
Writing the description later :D 

### Changelog
#### New
-

#### Changed
-

#### Removed
-

### How was this tested?
- [ ] 🧠 Not needed
- [ ] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

2024-01-29 17:00 UTC, mgaseta approved these changes
LGTM!
Nice job!
<img width="300" src="https://media0.giphy.com/media/3WCNY2RhcmnwGbKbCi/giphy.gif"/>

2024-01-29 21:17 UTC, RMCampos requested changes
Great job! 🚀 Only a few suggestions and issues.

2024-01-29 21:17 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +              description = "If it should fetch all client locations.")
suggestion: add `required = false` if this is not required.

2024-01-29 21:17 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/ForestClientService.java
> +        "Fetching {} Forest Clients by its number {}", clientNumber, shouldFetchAll ? "all" : "10");
issue: `clientNumber` should switch place with `shouldFetchAll`. They are in the wrong order.

2024-01-29 21:17 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/ForestClientService.java
> +    if (!type.equals("acronym") && !type.equals("client_number") && !type.equals("client_name")) {
suggestion: you can have a more readable condition here, something like `if (!List.of("acronym", "client_number", "client_name").contains(type)) { ... }`

2024-01-29 21:17 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/ForestClientService.java
> +        });
praise: nice 👍🏻

2024-01-29 21:17 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/ForestClientService.java
> +        });
praise: nice 👍🏻

2024-01-29 21:17 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +          String query) {
suggestion: same here. Add required true or false.

2024-01-29 21:56 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +              description = "If it should fetch all client locations.")
i had that before, then I read that it default to required so I removed it, but yes I agree having it make it more readable.

2024-01-29 22:03 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/ForestClientService.java
> +        "Fetching {} Forest Clients by its number {}", clientNumber, shouldFetchAll ? "all" : "10");
oops

2024-01-29 22:04 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/ForestClientService.java
> +        "Fetching {} Forest Clients by its number {}", clientNumber, shouldFetchAll ? "all" : "10");
https://github.com/bcgov/nr-spar/pull/808/commits/4c3c08f2c6313a2de8d97d61e9b8bce0367999d3

2024-01-29 22:04 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +          String query) {
https://github.com/bcgov/nr-spar/pull/808/commits/823d5abb9bc99e9b3dc92f060a2712ddfef7f7a7

2024-01-29 22:05 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +              description = "If it should fetch all client locations.")
updated: https://github.com/bcgov/nr-spar/pull/808/commits/823d5abb9bc99e9b3dc92f060a2712ddfef7f7a7

2024-01-29 22:05 UTC, craigyu commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/ForestClientService.java
> +    if (!type.equals("acronym") && !type.equals("client_number") && !type.equals("client_name")) {
good idea: https://github.com/bcgov/nr-spar/pull/808/commits/7f1b58e44721d620439620a5569d85f2aa49eb30

2024-01-30 13:57 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +          String query) {
Thank you!

2024-01-30 13:58 UTC, RMCampos approved these changes
LGTM 🚀 

<img width="200" src="https://media0.giphy.com/media/AIt35N6MJs3qWWk9dL/giphy.gif"/>

2024-01-30 14:01 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/ForestClientEndpoint.java
> +              description = "If it should fetch all client locations.")
Thank you!

2024-01-30 14:02 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/ForestClientService.java
> +        "Fetching {} Forest Clients by its number {}", clientNumber, shouldFetchAll ? "all" : "10");
Thank you!

2024-01-30 14:02 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/service/ForestClientService.java
> +    if (!type.equals("acronym") && !type.equals("client_number") && !type.equals("client_name")) {
Thank you!

2024-01-30 16:57 UTC, merged