Feat/806 update seedlot get endpoint to fetch parent tree information
bcgov/nr-spar pull request #877
Opened 2024-02-28 19:57 UTC by mgaseta

# Description
Closes #806

### Changelog
#### New
- New endpoint to fetch all data related to a seedlot, including the parent trees and calculations results
- New "getAll" functions to provide information for the endpoint

#### Changed
- Nothing :)

#### Removed
- Nothing :)

### How was this tested?
- [ ] 🧠 Not needed
- [ ] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?
<img width="250" src="https://media2.giphy.com/media/PGewdlXwLPhVVQYoLO/giphy.gif"/>

2024-02-29 17:44 UTC, RMCampos requested changes
Great job 💯 a few requests and thoughts, though.

2024-02-29 19:57 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedlotAhClassFormDto.java
> +public record SeedlotAhClassFormDto(
I agree, it's very weird... But this will only be useful for A-Class, right? So, we need a more specific name...

2024-02-29 19:57 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +  @GetMapping("/a-class-form-full/{seedlotNumber}")
Fixed here: https://github.com/bcgov/nr-spar/pull/877/commits/cac365034310e098ba00516009f69d4d0ffdad63

2024-02-29 19:57 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/endpoint/SeedlotEndpoint.java
> +      summary = "Fetch a single seedlot information and respective parent tree data",
Fixed here: https://github.com/bcgov/nr-spar/pull/877/commits/cac365034310e098ba00516009f69d4d0ffdad63

2024-03-01 15:01 UTC, RMCampos requested changes
Great job! Let's improve that wordy and we're ready 💯

2024-03-01 15:01 UTC, RMCampos commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedlotAhClassFormDto.java
> +public record SeedlotAhClassFormDto(
That's a good question. At this point it's hard to know. Maybe yes, but maybe not. How about then `SeedlotAclassFullFormDto` ? We could "cheat" and turn "a-class" in a single word: Aclass.

2024-03-01 16:24 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedlotAhClassFormDto.java
> +public record SeedlotAhClassFormDto(
That sounds good, I will do that.

2024-03-01 16:28 UTC, mgaseta commented on backend/src/main/java/ca/bc/gov/backendstartapi/dto/SeedlotAhClassFormDto.java
> +public record SeedlotAhClassFormDto(
Fixed here: https://github.com/bcgov/nr-spar/pull/877/commits/8aa99cf5f9d79bf45d5d871ec934fd7da0e9323d

2024-03-01 16:41 UTC, RMCampos approved these changes
🏆 

<img width="200" src="https://media4.giphy.com/media/73Y6EEJqbyGovenlLE/giphy.gif"/>

2024-03-01 17:26 UTC, merged