Fix/882 frontend responsiveness updates
bcgov/nr-spar pull request #890
Opened 2024-03-07 18:01 UTC by craigyu

# Description
Closes #882, #774 #772 #769 #768

To make PR review easier, I have tagged the issue number in each commit. 

Note that for #774, I can't find the problem of "No edit button" Arthur is referring to. 
And for #772, the table is cut in half but users can scroll horizontally, so I think that's the best and desired behaviour. 

### Changelog
#### New
- New Small Card component, currently being used on the Seedlot Dashboard page. Ideally the Main dashboard's favourite activity cards should use it as well, but too much refactoring is required for that so it'll be something for the future, or a test subject for a potential new team member. 

#### Changed
- Only styles are changed, some elements have been changed to `<Column>` from `<div>`. Nothing functional is changed. 

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media3.giphy.com/media/wotqBCVmRVn2w/giphy.gif" width="200"/>

2024-03-08 17:53 UTC, RMCampos commented
I spotted a horizontal scrollbar, with your change, at the Seedlots page. Can we take a look?

![image](https://github.com/bcgov/nr-spar/assets/2219519/0e59b8c2-6b98-4882-939c-7039ff89f612)

2024-03-08 18:00 UTC, RMCampos requested changes
Great job 🚀 only that horizontal scrollbar issue.

2024-03-11 12:37 UTC, mgaseta requested changes
Nice and clean job!
Added only a few markups, nothing major.

2024-03-11 12:37 UTC, mgaseta commented on frontend/src/components/Card/StandardCard/styles.scss
> +  margin-bottom: 1.25rem;
Nice!

2024-03-11 12:37 UTC, mgaseta commented on frontend/src/components/FavouriteActivities/index.tsx
> +          <button className="tooltip-button" type="button" aria-label="tooltip-button">
The aria-label prop needs to be more descriptive :)

2024-03-11 12:37 UTC, mgaseta commented on frontend/src/components/FavouriteActivities/index.tsx
>                  inside each page"
Not sure if it's a git issue, but indentation looks odd here.

2024-03-11 18:05 UTC, craigyu commented
> 01b925d

https://github.com/bcgov/nr-spar/pull/890/commits/01b925df9aba44e9a94260353375b2061a280ee0 fixed

2024-03-11 18:05 UTC, craigyu commented
> Great job 🚀 only that horizontal scrollbar issue.

https://github.com/bcgov/nr-spar/pull/890/commits/01b925df9aba44e9a94260353375b2061a280ee0
 
fixed

2024-03-11 18:07 UTC, craigyu commented on frontend/src/components/FavouriteActivities/index.tsx
> +          <button className="tooltip-button" type="button" aria-label="tooltip-button">
https://github.com/bcgov/nr-spar/pull/890/commits/8dc9996f0931169072d733319f7cb556f97d4b90 fixed here, a toggle tip is more appropriate here but let's not worry about it now https://react.carbondesignsystem.com/?path=/story/components-toggletip--playground

2024-03-11 18:09 UTC, craigyu commented on frontend/src/components/FavouriteActivities/index.tsx
>                  inside each page"
https://github.com/bcgov/nr-spar/pull/890/commits/8dc9996f0931169072d733319f7cb556f97d4b90

it looks odd but that how it looks on VSC, I formatted it again because it's over 100 characters on that row. Not sure why eslint doesn't pick these up. Looks like it's allowing over 100 characters as long as it's a string value.

2024-03-11 18:22 UTC, RMCampos approved these changes
Great job! 🚀

2024-03-11 18:37 UTC, mgaseta approved these changes
LGTM! Nice job!
<img width="250" src="https://media4.giphy.com/media/KINEZBEHHJxzEYQ4Dv/giphy.gif"/>

2024-03-11 22:30 UTC, merged