Fix/use smallcard for fav activity cards 2
bcgov/nr-spar pull request #911
Opened 2024-03-15 00:49 UTC by ngunner15

# Description

Refactor Favourite Card Component to use Small Card Component for smaller screens

Closes [#898](https://github.com/bcgov/nr-spar/issues/898)

### Changelog
#### New
None

#### Changed
Favourite Card Component
Small Card Component

#### Removed
None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExdHlrcHJqeDR0MGMzNDJzZTVicHo3dDQ5c29pZ2d4ZzgzbjlqczVjNiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xUySTUZ8A2RJBQitEc/giphy.gif" width="200"/>

2024-03-18 15:53 UTC, DerekRoberts requested changes
Hey, I didn't know you were helping on SPAR!  Welcome and thanks.  :)

848 files have been changed, mostly file permissions.  Please correct those or provide an explanation.

2024-03-18 17:16 UTC, craigyu commented
@ngunner15 props on having great commit history, made things a lot easier

2024-03-19 20:19 UTC, mgaseta requested changes
Great first PR @ngunner15 ! Congrats!
Added some comments and requested a few changes, but nothing too major.

2024-03-19 20:19 UTC, mgaseta commented on frontend/src/components/Card/FavouriteCard/index.tsx
> +  );
Nice improvement!

2024-03-19 20:19 UTC, mgaseta commented on frontend/src/components/Card/SmallCard/index.tsx
> +    <Tile className={`${favClassName} small-card`} tabIndex={favTabIndex} onClick={() => navigate(path)}>
Changing the tab index is not a good practice... It can mess up the order of the elements, which affect keyboard-only users and users that require screen readers. We need to make sure to not change them and leave the correct order on the DOM. You can read more [here](https://dequeuniversity.com/rules/axe/4.4/tabindex#:~:text=Here%20are%20some%20of%20the,the%20tab%20order%20only%20once.). 
Please, remove this prop.

2024-03-19 20:19 UTC, mgaseta commented on frontend/src/components/Card/SmallCard/index.tsx
> +  header, actionBtn, path, isIcon, image, favClassName, favTabIndex
Not sure about this `favClassName` prop, it is showing as `undefined` on other places that not the favourite cards (i.e. Seedlot Dashboard cards), since this class name is not applying anything specific (at least for now), I think you can remove it.
![Screenshot from 2024-03-19 17-13-41](https://github.com/bcgov/nr-spar/assets/105936322/68f5433c-70cd-409e-8a32-07e72fb5540b)

![Screenshot from 2024-03-19 17-05-34](https://github.com/bcgov/nr-spar/assets/105936322/fabd5a77-874e-44fa-bdec-35222478e9f3)

2024-03-19 20:19 UTC, mgaseta commented on frontend/src/components/Card/SmallCard/styles.scss
> +  fill: #FFF;
When setting the color for components, please use the ones on the theme package. You can import it on your stylesheet by adding the line: `@use '@bcgov-nr/nr-theme/design-tokens/colors.scss' as colors;`, also, there are a lot of stylesheets on the code that you can take a look and see how we are using it. Please fix all the occurrences in this file :)

2024-03-21 22:38 UTC, ngunner15 commented on frontend/src/components/Card/FavouriteCard/index.tsx
> +  );
Thanks

2024-03-25 23:13 UTC, craigyu requested changes
not sure how but you have 848 files changed again 😂

2024-03-26 00:07 UTC, ngunner15 commented
@craigyu I reverted those changes. The file permissions are back to the original.

2024-03-26 00:55 UTC, DerekRoberts commented
@ngunner15 We should solve your permissions issues.  That's unlikely to be the best solution for most local Docker issues.

2024-03-26 12:52 UTC, mgaseta approved these changes
LGTM! Nice job! :1st_place_medal: :100:

2024-03-26 16:28 UTC, ngunner15 commented
@DerekRoberts That was my bad 😅, I was trying to run the project on my local, that's why I had to change those permissions. While running on docker there is no permission issue.

2024-03-26 17:55 UTC, craigyu approved these changes

2024-03-26 19:26 UTC, merged