feat: handle test login for business bceid between legacy and new spar
bcgov/nr-spar pull request #912
Opened 2024-03-18 14:41 UTC by RMCampos

# Description
Closes #446 

### Changelog
#### New
- None

#### Changed
- Frontend `AuthProvider`;

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

No post-deployments tasks.

###  What gif/image best describes this PR or how it makes you feel?

<img width="200" src="https://media0.giphy.com/media/81xwEHX23zhvy/giphy.gif"/>

2024-03-18 16:11 UTC, craigyu approved these changes
<img src="https://media3.giphy.com/media/l0MYu2xpvAHEEoY2k/giphy.gif" width="100"/>

2024-03-18 16:13 UTC, craigyu requested changes
oops, Cypress failed

2024-03-18 19:36 UTC, RMCampos commented
> oops, Cypress failed

It looks like the username/pasword are not correct. Can you double check?

I've extracted this from the failing videos:
![image](https://github.com/bcgov/nr-spar/assets/2219519/1b055082-5834-4c73-a248-d0c4758864a8)

2024-03-18 20:30 UTC, craigyu commented
> > oops, Cypress failed
> 
> It looks like the username/pasword are not correct. Can you double check?
> 
> I've extracted this from the failing videos: ![image](https://private-user-images.githubusercontent.com/2219519/313813080-1b055082-5834-4c73-a248-d0c4758864a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3OTQwMzEsIm5iZiI6MTcxMDc5MzczMSwicGF0aCI6Ii8yMjE5NTE5LzMxMzgxMzA4MC0xYjA1NTA4Mi01ODM0LTRjNzMtYTI0OC1kMGM0NzU4ODY0YTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMThUMjAyODUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjZjNzYwNDEzMGRjYjBkNGFjMThmMGJkZjY4ZmNlN2FjOGYzNGE0ZWUwZTBhN2NlZDk2YjkxYWIwNmEyZTY3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0ehWSoe1vt2_ysdv0e7Mz-qxAjWiKge5vmEdjRMazuk)

It works fine on test and local :/

Maybe it's the environment change?

2024-03-19 13:58 UTC, mgaseta requested changes
Besides the failing Cypress tests, everything LGTM!

2024-03-19 19:29 UTC, craigyu approved these changes

2024-03-19 19:45 UTC, mgaseta approved these changes
Nice work!

2024-03-19 19:51 UTC, merged