Feat/916 cypress test on seedlot detail page
bcgov/nr-spar pull request #919
Opened 2024-03-20 23:22 UTC by ngunner15

# Description
Closes #916 

### Changelog
#### New
-frontend/cypress/e2e/smoke-test/edit-applicant-seedlot-info.cy.ts,
-frontend/cypress/e2e/smoke-test/seedlot-detail.cy.ts,
-frontend/cypress/fixtures/default-seedlot-detail.json,
-frontend/cypress/fixtures/user_seedlots.json,
-frontend/cypress/fixtures/applicant-info-change.json,
-frontend/cypress/fixtures/forest-clients.json,
frontend/cypress/fixtures/seedlot-source.json

#### Changed
-frontend/cypress.config.ts,
-frontend/cypress/e2e/smoke-test/seedlot-main-page.cy.ts,
-frontend/cypress/support/e2e.ts,

#### Removed
-

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcHE3OXJ4bTRhd295ZXNpaHYwZ2M2d2lvZGg0cXpyNm56NmpwZ2tkbCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/B4xdycvhDq7qM3cdh2/giphy.gif" width="200"/>

2024-03-20 23:32 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/seedlot-detail.cy.ts
I tested the title and button functionality.
If we want to add more tests I can add tests on all the fields of this page.

2024-03-21 21:24 UTC, DerekRoberts requested changes
Wow, we need this so badly!

Please don't forget to include the tests in our workflows.  Want a hand?

2024-03-21 21:42 UTC, ngunner15 commented
@DerekRoberts How can I include the tests in the workflow?

2024-03-21 22:04 UTC, DerekRoberts approved these changes
Sorry @ngunner15!  Tests are already loaded.  Now approved.  :)

2024-03-21 22:32 UTC, merged