Feat/817 development of seedlot review step 1   applicant and seedlot information
bcgov/nr-spar pull request #922
Opened 2024-03-21 22:43 UTC by craigyu

# Description
Closes #817 

Apologies for the huge PR.
A lot of refactoring and components were needed to achieve this.
I'm happy with the results, it's possible for that TSC super user 🦖 to edit Pending seedlots after all.

### Changelog
#### New
- Dev tools for dev/local env only 🙌, it's available on the profile side menu
    <img width="205" alt="image" src="https://github.com/bcgov/nr-spar/assets/25162561/c0c9d3dc-3e7f-49e6-9444-2879ff9abda4">
- Seedlot Review Access button, note that no RBAC is implemented as it'll make testing harder
    <img width="352" alt="image" src="https://github.com/bcgov/nr-spar/assets/25162561/5099757f-03ec-408b-bcaa-07b9c3d825ac">

- Seedlot Review View page setup along with applicant and seedlot implemented
    `frontend/src/views/Seedlot/SeedlotReview/index.tsx`
    <img width="488" alt="image" src="https://github.com/bcgov/nr-spar/assets/25162561/16a55614-3b6e-4f70-8cca-194f0770cebb">

- `<Divider />` component for a horizontal line, it's using `<Row>` from carbon instead of `<hr>` from html, might have better with responsiveness
    <img width="945" alt="image" src="https://github.com/bcgov/nr-spar/assets/25162561/cd547cf6-1526-4df0-afda-e93e25edbc15">

- `<RowGap />` component for the grey row gap, using this is easier than setting the background to grey
    <img width="455" alt="image" src="https://github.com/bcgov/nr-spar/assets/25162561/0c3cea67-3099-4ded-86df-209fd2c4f0ff">

- `<EmailDisplay />` component for displaying and copying an email
    <img width="242" alt="image" src="https://github.com/bcgov/nr-spar/assets/25162561/368fb5c4-7e33-43f6-b924-d8e0343dc536">
    <img width="199" alt="image" src="https://github.com/bcgov/nr-spar/assets/25162561/9f4f0af4-7190-4326-be08-14792b960ab3">
-  `<DetailSection />` A section wrapper that provides a white container with rounded border and paddings. Intended for Seedlot Detail page, can be used elsewhere.

#### Changed
- Removed famLoginUser from local storage as it's not needed. To get JWT or other user info, use the dev tool.
- Refactored the `index.tsx` and `App.tsx`, the goal was to simplify the `index.tsx` file as conventionally it should be a specifying the root rendering element. 
- Refactored the logic for `SeedlotRegFormClassA`, separated the context out to `ContextContainerClassA` so it can be shared with Seedlot Review. Although some of the logic in `ContextContainerClassA` is not needed for the review page (yet), it is better to keep it there for now.
- Refactored the hierarchy for Edit Applicant Info page so it can be used in the review page as well.  
- Minor name changes

#### Removed
- None

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [ ] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media2.giphy.com/media/RHQ7SEQACHtfnu3eaV/giphy-downsized-medium.gif" width="200"/>

2024-03-21 23:50 UTC, DerekRoberts approved these changes
That's a hilarious amount of work for minimal visible change!  Glad it's done.  ;)

2024-03-25 20:21 UTC, RMCampos approved these changes
Some optional things. That's a lot of work! Very nice job 🥇 

<img width="200" src="https://media4.giphy.com/media/FzzmLlMXc8ooM/giphy.gif"/>

2024-03-25 20:21 UTC, RMCampos commented on frontend/index.html
> +  <meta name="description" content="BC Seed Planning and Registry 2.0" />
👍🏻

2024-03-25 20:21 UTC, RMCampos commented on frontend/src/App.tsx
> +    </ClassPrefix>
Refactored from index.tsx file to here. 👍🏻

2024-03-25 20:21 UTC, RMCampos commented on frontend/src/components/Divider/styles.scss
> +  height: 1px;
question (non-blocking): is px fine? Or should we change to rem?

2024-03-25 20:21 UTC, RMCampos commented on frontend/src/components/MyProfile/index.tsx
> +                  <PanelSectionName title="Dev Zone" light />
Nice 👍🏻

2024-03-25 20:50 UTC, craigyu commented on frontend/src/components/Divider/styles.scss
> +  height: 1px;
oof, good catch

2024-03-25 20:54 UTC, craigyu commented on frontend/src/components/Divider/styles.scss
> +  height: 1px;
https://github.com/bcgov/nr-spar/pull/922/commits/58d5338ee2824feca450f3e31b8ac68c5e407df4

2024-03-25 21:46 UTC, mgaseta requested changes
Phew, that was a lot... A LOT OF AMAZING CHANGES! Nice job @craigyu !
Added only a fez mark-ups, but nothing critical!

2024-03-25 21:46 UTC, mgaseta commented on frontend/src/components/LotApplicantAndInfoForm/index.tsx
> +import Divider from '../Divider';
Add this import together with the other components imports.

2024-03-25 21:46 UTC, mgaseta commented on frontend/src/components/MyProfile/index.tsx
> +                  </SideNavLink>
<img width="200" src="https://media3.giphy.com/media/kwcRp24Wz4lZm/giphy.gif"/>

2024-03-25 21:46 UTC, mgaseta commented on frontend/src/components/ReadOnlyInput/index.tsx
> +import { TextInput, TextInputSkeleton } from '@carbon/react';
Change this import to line 2 :)

2024-03-25 21:46 UTC, mgaseta commented on frontend/src/config/FavouriteActivitiyMap.ts
>    unkown: {
Non-related to the changes, but there is a typo here...

2024-03-25 21:46 UTC, mgaseta commented on frontend/src/views/Seedlot/ContextContainerClassA/context.tsx
Don't even have a GIF for this, nice job! Context FTW!

2024-03-25 21:46 UTC, mgaseta commented on frontend/src/views/Seedlot/ContextContainerClassA/index.tsx
> +  resDataToState
Just a suggestion: break this import in to less lines, maybe like 4 items per line, like on lines 11 - 14.

2024-03-25 21:46 UTC, mgaseta commented on frontend/src/views/Seedlot/EditAClassApplication/index.tsx
> +import EditAClassApplicationForm from './Form';
Adjust import order.

2024-03-25 21:46 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotDetails/FormProgress/index.tsx
> +            {seedlotStatusCode === 'SUB' ? 'Check your seedlot' : 'Edit seedlot form'}
We agreed to change "Check" to "View", right?

2024-03-25 21:46 UTC, mgaseta commented on frontend/src/views/Seedlot/SeedlotReview/context.ts
> +/* eslint-disable @typescript-eslint/no-unused-vars */
This can be safely removed, right?

2024-03-25 22:53 UTC, craigyu commented on frontend/src/config/FavouriteActivitiyMap.ts
>    unkown: {
lol found more typos from me on this word, good eyes

2024-03-25 22:55 UTC, craigyu commented on frontend/src/views/Seedlot/ContextContainerClassA/index.tsx
> +  resDataToState
ok, did 3 per line

2024-03-25 23:11 UTC, craigyu commented
@mgaseta 
Tried to fix everything in this commit https://github.com/bcgov/nr-spar/pull/922/commits/55e79f7f34266a5750ffb648169066a26bb8a1b0

but then I forgot one thing so it's here https://github.com/bcgov/nr-spar/pull/922/commits/2809ba72f280baa8769db581707dac13710e34fc

2024-03-26 12:54 UTC, mgaseta approved these changes
LGTM! Great job! :1st_place_medal: :rocket:

2024-03-26 18:11 UTC, merged