Feat/916 cypress test on seedlot detail page
bcgov/nr-spar pull request #924
Opened 2024-03-21 22:50 UTC by craigyu

# Description
Recreated from #919 
Closes #916 

### Changelog
#### New
-frontend/cypress/e2e/smoke-test/edit-applicant-seedlot-info.cy.ts,
-frontend/cypress/e2e/smoke-test/seedlot-detail.cy.ts,
-frontend/cypress/fixtures/default-seedlot-detail.json,
-frontend/cypress/fixtures/user_seedlots.json,
-frontend/cypress/fixtures/applicant-info-change.json,
-frontend/cypress/fixtures/forest-clients.json,
frontend/cypress/fixtures/seedlot-source.json

#### Changed
-frontend/cypress.config.ts,
-frontend/cypress/e2e/smoke-test/seedlot-main-page.cy.ts,
-frontend/cypress/support/e2e.ts,

#### Removed
-

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExcHE3OXJ4bTRhd295ZXNpaHYwZ2M2d2lvZGg0cXpyNm56NmpwZ2tkbCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/B4xdycvhDq7qM3cdh2/giphy.gif" width="200"/>

2024-03-21 23:04 UTC, craigyu commented on backend/src/main/resources/application.properties
> +spring.docker.compose.enabled = false
@RMCampos @mgaseta  out of the scope of this PR but can we keep this one as false? having it as true make backend bug out when using docker compose

2024-03-21 23:52 UTC, DerekRoberts approved these changes

2024-03-25 13:05 UTC, RMCampos commented on backend/src/main/resources/application.properties
> +spring.docker.compose.enabled = false
Sure thing! I probably forgot to commit this change. Feel free to! Thanks @craigyu

2024-03-25 23:30 UTC, craigyu commented on frontend/cypress/fixtures/default-seedlot-detail.json
> +      "entryUserId": "IDIR@CYU",
my bad, could you remove my ID here and other places with something else?

2024-03-26 13:36 UTC, mgaseta requested changes
Nice job, added only a few mark-ups!

2024-03-26 13:36 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/edit-applicant-seedlot-info.cy.ts
> +  it('should edit a seedlot applicant info', () => {
Not sure if all these tests should be only in one `it`, maybe we can discuss breaking it in more pieces so it's easy to track possible issues.

2024-03-26 13:36 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/seedlot-detail.cy.ts
> +   * Dashboard page should load correctly.
Specify this comment to "Seedlot Dashboard" just so it doesn't get confused with the main dashboard.

2024-03-26 13:36 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/seedlot-main-page.cy.ts
> +      .should('have.text', '63001');
Change this seedlot number, so it's not repeated, so we can simulate a real scenario he best way possible.

2024-03-26 13:36 UTC, mgaseta commented on frontend/cypress/fixtures/user_seedlots.json
> +    "id": "63001",
Change repeated seedlot id.

2024-03-26 13:38 UTC, RMCampos approved these changes
Great job @ngunner15 💯 

Besides @mgaseta comments, all good! 

As for the `application.properties` file change, I'm ok either way, with or without env vars.

2024-03-26 18:17 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/edit-applicant-seedlot-info.cy.ts
> +  it('should edit a seedlot applicant info', () => {
I know a long test is not ideal but I couldn't think of a better way either, as each step depends on the previous one, such as saving an edit depends on editing an input. Having multiple `it`s will cause the page to load again unless we turn off test isolation and it is not recommended. 

https://stackoverflow.com/questions/64128366/cypress-is-there-a-way-for-an-it-test-to-begin-where-the-last-it-test-ende

2024-03-26 18:31 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/seedlot-detail.cy.ts
> +});
More tests are needed within each `it`, we need to verify the seedlot information for that specific seedlot is rendered, things like button and section title is not unique to each seedlot, so aside from testing those, it's better to test other fields as well, such as seedlot number, species, agency name, location code, etc. 

In order to have a more thorough test, I would suggest to field every field is rendered correctly for each section.

2024-03-26 18:39 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/seedlot-detail.cy.ts
> +});
![image](https://github.com/bcgov/nr-spar/assets/25162561/dabb1d7a-ba5a-4fe7-a0a5-47d7892a2248)

**Seedlot Summary**
- [ ] seedlot number
- [ ] seedlot class
- [ ] seedlot species
- [ ] status
- [ ] created at
- [ ] last updated
- [ ] approved at

**See where you are in the registration process**
- [ ] verify each step's name is rendered 

**Check your applicant and seedlot information**
- [ ] Applicant agency
- [ ] Applicant location code
- [ ] Email address
- [ ] Seedlot species
- [ ] Specify A-class source
- [ ] To be registered at the Tree Seed Centre?
- [ ] Collected from a location within B.C.?

**Avoid** hard coding the value for comparison, import the same fixture that is used for api mocking, then compare the value that way.

2024-03-26 18:47 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/edit-applicant-seedlot-info.cy.ts
> +  it('should edit a seedlot applicant info', () => {
Hmmm, that makes sense, let's leave like this then,  it's just sad to see a giant test like this hahaha.

2024-03-26 23:28 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/seedlot-detail.cy.ts
> +});
Thanks @craigyu 💯 for the detailed info about each test.

2024-03-27 20:27 UTC, mgaseta requested changes
Good job! Very nice improvements!
Added only one markup that needs to applied to a bunch of places (sorry)

2024-03-27 20:27 UTC, mgaseta commented on frontend/cypress/e2e/smoke-test/seedlot-detail.cy.ts
> +      .children('.bx--row')
Please, replace `bx` by the prefix constant, `bx` stands for the default prefix of all BC Gov/Carbon components.
This is important because if one day someone has the (not so) brilliant idea to change the prefix, all these tests will break, if we use the constant, only one place will have to be adjusted.

`dashboard-page.cy.ts` file is using the prefix, you can take a look there.

2024-03-27 20:47 UTC, DerekRoberts commented on frontend/cypress/e2e/smoke-test/seedlot-detail.cy.ts
> +      .children('.bx--row')
^ this is a really good point!

2024-03-27 22:50 UTC, craigyu commented
37.55% -> 47.23%, great stuff @ngunner15 !

2024-03-27 22:51 UTC, craigyu commented
@mgaseta I've checked that he's updated as per your request, merging this in

2024-03-27 22:51 UTC, merged