Feat/new tests
bcgov/nr-spar pull request #95
Opened 2023-05-09 20:45 UTC by ArthurEncr

# Description

new tests created:
TitleAccordion 
ApplicantInformation
SeedlotActivityHistory  
SeedlotRegistrationProgress 
FormProgress 
ComboButton 
CreateAClass 

Fixes # [[FSADT2-639](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-639)]

in addition, a submit modal style fix (fixes [FSADT2-651](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-651) )

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

2023-05-09 21:45 UTC, DerekRoberts submitted a review, later dismissed
Looks promising!

Please make sure all tests pass before marking a pull request as ready.  This one has just been changed to draft.

2023-05-10 13:50 UTC, ArthurEncr commented
> Looks promising!
> 
> Please make sure all tests pass before marking a pull request as ready. This one has just been changed to draft.

I think this is an error in the backend, not in the front end tests.

2023-05-10 13:52 UTC, RMCampos requested changes
Good job 🥇 Just a minor fix about eslint.

2023-05-10 13:52 UTC, RMCampos commented on frontend/src/__test__/components/ApplicantInformation.test.tsx
> +/* eslint-disable no-undef */
If I'm not mistaken, we don't need this `eslint-disable` statement anymore. Craig did a cleaning the other day. It's safe to remove it.

2023-05-10 13:53 UTC, RMCampos commented on frontend/src/__test__/components/ApplicantInformation.test.tsx
> +/* eslint-disable no-undef */
Right @craigyu ?

2023-05-10 13:55 UTC, ArthurEncr commented on frontend/src/__test__/components/ApplicantInformation.test.tsx
> +/* eslint-disable no-undef */
> If I'm not mistaken, we don't need this `eslint-disable` statement anymore. Craig did a cleaning the other day. It's safe to remove it.

I just fixed that, removed it from all the tests that still had it.

2023-05-10 13:56 UTC, RMCampos commented
@DerekRoberts all tests are passing. However some warnings are logged in the console. May they they are sounding like errors or issues to the action? 🥲

2023-05-11 00:23 UTC, craigyu requested changes
Good work, just a couple changes, the combo box one can be annoying.
Maybe this helps: https://joshfrankel.me/blog/simulating-a-select-dropdown-change-in-jest/ 

Also don't forget to update the branch when you're done :)

2023-05-11 00:23 UTC, craigyu commented on frontend/src/__test__/components/ComboButton.test.tsx
> +    fireEvent.click(comboButtonElement[0]);
This does not test a select action, I changed line 40 to:
`expect(screen.getByText('Delete seedlot')).toBeInTheDocument();`
![image](https://github.com/bcgov/nr-spar/assets/25162561/54dc3767-801b-4a66-a65c-ddd901b01fe7)
Here's the value of `comboButtonElement`: 
<img width="425" alt="image" src="https://github.com/bcgov/nr-spar/assets/25162561/ea4db803-c97c-4d97-ad47-aa02d7ec264c">

2023-05-11 00:23 UTC, craigyu commented on frontend/src/components/SeedlotRegistrationSteps/SubmitModal/styles.scss
>  }
Please add an empty line at the end of file.

2023-05-11 18:04 UTC, ArthurEncr commented on frontend/src/__test__/components/ComboButton.test.tsx
> +    fireEvent.click(comboButtonElement[0]);
This test is just to see if the options are appearing when clicking on the combo button, not to test the click on the options. The test is working perfectly, and it should pass for you with the change to "Delete seedlot" because that is one of the 4 options that appear when you open the dropdown, but if you change it to any other text, the test will not pass. With just these two tests on this component, covarage is already in the green zone, but I can additionally do a test to test the click on the options if I find it relevant! About the console log, it's like that, it doesn't show the HTML content in the console, but it's there.

2023-05-12 00:15 UTC, DerekRoberts commented on frontend/src/components/SeedlotRegistrationSteps/SubmitModal/styles.scss
>  }
Why is this resolved?  That red circle with a line indicates no new line.

2023-05-12 04:13 UTC, DerekRoberts commented
JavaScript CI is for Frontend.  Please look at the warnings generated. @ArthurEncr 

https://github.com/bcgov/nr-spar/actions/runs/4953893270/jobs/8861866233?pr=95

2023-05-12 04:16 UTC, DerekRoberts requested changes
JavaScript CI is for Frontend.  Please look at the warnings generated.

https://github.com/bcgov/nr-spar/actions/runs/4953893270/jobs/8861866233?pr=95

2023-05-12 14:16 UTC, lucasbuenoencora requested changes
Great job :rocket: ! Just take a look at the markup on the CreateAClass.test.tsx file.

2023-05-12 14:16 UTC, lucasbuenoencora commented on frontend/src/__test__/views/CreateAClass.test.tsx
This test is generating an Axios warning, you can fix it using makeServer. Take a look at the FavouriteActivities.test.tsx on how to use the makeServer

2023-05-12 18:11 UTC, craigyu commented on frontend/src/__test__/components/ComboButton.test.tsx
> +    fireEvent.click(comboButtonElement[0]);
Sorry it's my bad, it does work, I understood it wrong🤡

2023-05-12 18:27 UTC, craigyu commented on frontend/src/__test__/views/CreateAClass.test.tsx
[resloved](https://github.com/bcgov/nr-spar/pull/95/commits/39b2bf8aef6d49e6695854d68c495fc8423d4c19)

2023-05-12 23:11 UTC, craigyu approved these changes
Good work

2023-05-12 23:12 UTC, merged