Feat/959 refactor dashboard and seedlot dashboard cypress tests
bcgov/nr-spar pull request #980
Opened 2024-04-09 22:54 UTC by ngunner15

# Description
Closes #[959](https://github.com/bcgov/nr-spar/issues/959)

### Changelog
#### New
-

#### Changed
- Dashboard Cypress test
- Seedlot dashboard Cypress test

#### Removed
- Mocked API calls on Dashboard Cypress test
- Mocked favourite data and its fixture
- Mocked seedlot rows and its fixture

### How was this tested?
- [ ] 🧠 Not needed
- [x] 👀 Eyeball
- [x] 🤖 Added tests

###  What gif/image best describes this PR or how it makes you feel?

<img src="https://giphy.com/gifs/rickandmorty-rick-and-morty-episode-210-3o85xLbmtO1CTYvwDC" width="200"/>

2024-04-09 23:17 UTC, DerekRoberts approved these changes
Tests!  We need these.  :)

2024-04-10 17:57 UTC, craigyu requested changes

2024-04-10 17:57 UTC, craigyu commented on frontend/src/components/NotificationsCentral/index.tsx
> +        /> */}
why was this one changed

2024-04-10 17:57 UTC, craigyu commented on frontend/cypress/fixtures/seedlot-main-page.json
Great job on using existing fixtures instead of hardcoding on the test

2024-04-10 17:57 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/seedlot-main-page.cy.ts
> +      .should('have.text', seedlotMainPageData.emptySectionSubtitle);
Let's separate these into their own test, add another `it("should display empty seedlot section")`, feel free to change the test name

2024-04-10 17:57 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/seedlot-main-page.cy.ts
> +      .should('have.text', seedlotMainPageData.emptySectionSubtitle);
and edit the name on line 24 `'should load and display seedlot main page correctly'`, maybe something like `should display seedlot dashboard page title`. This is an improvement, not something you missed, let's get it changed in this PR regardless :D

2024-04-10 18:13 UTC, craigyu commented on frontend/cypress/e2e/smoke-test/seedlot-main-page.cy.ts
>  describe('Seedlot Main page test', () => {
Rename this to `Seedlot Dashboard test', and the file name, don't forget to change the config at `frontend/cypress.config.ts`

2024-04-11 18:15 UTC, RMCampos requested changes
Great job 💯 Just remove some coments and we're good to go!

2024-04-11 18:15 UTC, RMCampos commented on frontend/cypress/e2e/smoke-test/seedlot-dashboard.cy.ts
> +  // });
issue: Can we remove these comments? Also in the second line, at the top.

2024-04-11 18:26 UTC, ngunner15 commented on frontend/cypress/e2e/smoke-test/seedlot-dashboard.cy.ts
> +  // });
We might need these tests in the future when we are testing from a database.

2024-04-15 20:16 UTC, craigyu approved these changes

2024-04-15 20:17 UTC, merged